import { Box, FormControlLabel, MenuItem, Switch, TextField } from "@mui/material";
import type { ClinicalCustomField, ClinicalRecordData } from "../../types/clinicalAnamnesis";
import ClinicalSection from "./ClinicalSection";
import StringListField from "./StringListField";

const grid={display:"grid",gridTemplateColumns:{xs:"1fr",md:"1fr 1fr"},gap:2};
const full={gridColumn:{md:"1/-1"}};
const statuses=[['NOT_INFORMED','Não informado'],['NO','Não'],['YES','Sim'],['FORMER','Anterior']] as const;

export default function ClinicalAnamnesisForm({data,onChange,customFields,readOnly=false}:{data:ClinicalRecordData;onChange:(data:ClinicalRecordData)=>void;customFields:ClinicalCustomField[];readOnly?:boolean}){
 const set=<K extends keyof ClinicalRecordData>(key:K,value:ClinicalRecordData[K])=>onChange({...data,[key]:value});
 const text=(key:keyof ClinicalRecordData,label:string,rows=3)=><TextField disabled={readOnly} label={label} multiline rows={rows} value={String(data[key]||"")} onChange={e=>set(key,e.target.value as never)} sx={full}/>;
 const list=(key:keyof ClinicalRecordData,label:string)=><StringListField disabled={readOnly} label={label} value={data[key] as string[]} onChange={v=>set(key,v as never)}/>;
 return <Box sx={{display:"grid",gap:2}}>
  <ClinicalSection title="Anamnese e históricos"><Box sx={grid}>{text("mainComplaint","Queixa principal")}{text("currentDiseaseHistory","História da doença atual")}{text("dentalHistory","Histórico odontológico")}{text("medicalHistory","Histórico médico")}{list("systemicDiseases","Doenças sistêmicas")}{list("medications","Medicamentos em uso")}{list("allergies","Alergias")}{list("previousSurgeries","Cirurgias anteriores")}{list("hospitalizations","Internações")}{text("relevantFamilyHistory","Antecedentes familiares relevantes")}</Box></ClinicalSection>
  <ClinicalSection title="Gestação e hábitos"><Box sx={grid}><FormControlLabel control={<Switch disabled={readOnly} checked={data.pregnancy.applicable} onChange={e=>set("pregnancy",{...data.pregnancy,applicable:e.target.checked})}/>} label="Gestação aplicável"/><TextField disabled={readOnly||!data.pregnancy.applicable} select label="Gestação" value={data.pregnancy.status} onChange={e=>set("pregnancy",{...data.pregnancy,status:e.target.value as ClinicalRecordData["pregnancy"]["status"]})}>{[['NOT_INFORMED','Não informado'],['NO','Não'],['YES','Sim'],['SUSPECTED','Suspeita']].map(x=><MenuItem key={x[0]} value={x[0]}>{x[1]}</MenuItem>)}</TextField><TextField disabled={readOnly||data.pregnancy.status!=="YES"} type="number" label="Semanas de gestação" value={data.pregnancy.weeks??""} onChange={e=>set("pregnancy",{...data.pregnancy,weeks:e.target.value?Number(e.target.value):undefined})}/><TextField disabled={readOnly} select label="Tabagismo" value={data.smoking.status} onChange={e=>set("smoking",{...data.smoking,status:e.target.value as ClinicalRecordData["smoking"]["status"]})}>{[['NOT_INFORMED','Não informado'],['NEVER','Nunca'],['CURRENT','Atual'],['FORMER','Anterior']].map(x=><MenuItem key={x[0]} value={x[0]}>{x[1]}</MenuItem>)}</TextField><TextField disabled={readOnly} label="Detalhes do tabagismo" value={data.smoking.details} onChange={e=>set("smoking",{...data.smoking,details:e.target.value})}/><TextField disabled={readOnly} select label="Uso de álcool" value={data.alcohol.status} onChange={e=>set("alcohol",{...data.alcohol,status:e.target.value as ClinicalRecordData["alcohol"]["status"]})}>{statuses.map(x=><MenuItem key={x[0]} value={x[0]}>{x[1]}</MenuItem>)}</TextField><TextField disabled={readOnly} label="Detalhes do uso de álcool" value={data.alcohol.details} onChange={e=>set("alcohol",{...data.alcohol,details:e.target.value})}/>{list("parafunctionalHabits","Hábitos parafuncionais")}</Box></ClinicalSection>
  <ClinicalSection title="Sinais vitais, riscos e alertas"><Box sx={grid}><TextField disabled={readOnly} type="number" label="Pressão sistólica (mmHg)" value={data.vitalSigns.systolic??""} onChange={e=>set("vitalSigns",{...data.vitalSigns,systolic:e.target.value?Number(e.target.value):undefined})}/><TextField disabled={readOnly} type="number" label="Pressão diastólica (mmHg)" value={data.vitalSigns.diastolic??""} onChange={e=>set("vitalSigns",{...data.vitalSigns,diastolic:e.target.value?Number(e.target.value):undefined})}/><TextField disabled={readOnly} type="number" label="Glicemia (mg/dL), quando informada" value={data.vitalSigns.glucoseMgDl??""} onChange={e=>set("vitalSigns",{...data.vitalSigns,glucoseMgDl:e.target.value?Number(e.target.value):undefined})}/><TextField disabled={readOnly} type="datetime-local" label="Data/hora da aferição" value={data.vitalSigns.measuredAt?.slice(0,16)||""} onChange={e=>set("vitalSigns",{...data.vitalSigns,measuredAt:e.target.value?new Date(e.target.value).toISOString():undefined})} slotProps={{inputLabel:{shrink:true}}}/>{list("riskConditions","Condições de risco")}{list("clinicalAlerts","Alertas clínicos")}{text("observations","Observações")}</Box></ClinicalSection>
  <ClinicalSection title="Exame clínico"><Box sx={grid}>{text("extraoralExam","Exame extraoral")}{text("intraoralExam","Exame intraoral")}{text("softTissues","Tecidos moles")}{text("tmj","ATM")}{text("occlusion","Oclusão")}{text("periodontalCondition","Condição periodontal")}{text("generalDentalCondition","Condição dentária geral")}</Box></ClinicalSection>
  <ClinicalSection title="Diagnóstico e plano inicial"><Box sx={grid}>{text("diagnosticHypothesis","Hipótese diagnóstica")}{text("diagnosis","Diagnóstico")}{text("initialClinicalPlan","Plano clínico inicial",4)}</Box></ClinicalSection>
  {customFields.length>0&&<ClinicalSection title="Campos configurados pela clínica"><Box sx={grid}>{customFields.map(field=>{const value=data.customFields[field.key]; if(field.fieldType==="BOOLEAN")return <FormControlLabel key={field.id} control={<Switch disabled={readOnly} checked={Boolean(value)} onChange={e=>set("customFields",{...data.customFields,[field.key]:e.target.checked})}/>} label={field.label}/>;return <TextField key={field.id} disabled={readOnly} required={field.required} select={field.fieldType==="SELECT"} type={field.fieldType==="NUMBER"?"number":field.fieldType==="DATE"?"date":"text"} multiline={field.fieldType==="TEXTAREA"} rows={field.fieldType==="TEXTAREA"?3:undefined} label={field.label} value={value??""} onChange={e=>set("customFields",{...data.customFields,[field.key]:field.fieldType==="NUMBER"?Number(e.target.value):e.target.value})} slotProps={field.fieldType==="DATE"?{inputLabel:{shrink:true}}:undefined}>{field.fieldType==="SELECT"?field.options.map(x=><MenuItem key={x} value={x}>{x}</MenuItem>):undefined}</TextField>})}</Box></ClinicalSection>}
 </Box>
}
