import { useEffect, useState } from 'react'
import { Alert, Button, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, Stack, TextField, Typography, useMediaQuery } from '@mui/material'
import { useTheme } from '@mui/material/styles'
import { SpecialtyClinicalApi } from '../services/SpecialtyClinicalApi'
import type { LaboratoryPendingState, LaboratoryResolutionAction } from '../types/specialtyClinical'

const actions:{value:LaboratoryResolutionAction;label:string}[]=[
 {value:'RECEIVED',label:'Recebido'},{value:'DELIVERED',label:'Entregue'},{value:'COMPLETED',label:'Concluído'},
 {value:'CANCELLED',label:'Cancelado'},{value:'RENEGOTIATED',label:'Prazo renegociado'},
 {value:'IMPROPER_ALERT',label:'Alerta improcedente'},{value:'DEMO_DATA',label:'Dado demonstrativo'}
]
export function LaboratoryResolutionPanel({laboratoryWorkId}:{laboratoryWorkId:string}){
 const theme=useTheme();const narrow=useMediaQuery(theme.breakpoints.down('sm'));const[state,setState]=useState<LaboratoryPendingState|null>(null);const[open,setOpen]=useState(false);const[action,setAction]=useState<LaboratoryResolutionAction>('COMPLETED');const[solution,setSolution]=useState('');const[reason,setReason]=useState('');const[observation,setObservation]=useState('');const[newDueDate,setNewDueDate]=useState('');const[error,setError]=useState('')
 const load=async()=>{try{setState(await SpecialtyClinicalApi.laboratoryPendingState(laboratoryWorkId))}catch(e:any){setError(e.message||'Falha ao carregar pendência')}}
 useEffect(()=>{void load()},[laboratoryWorkId])
 const start=async()=>{try{setState(await SpecialtyClinicalApi.beginLaboratoryPendingTreatment(laboratoryWorkId,{alertKind:'LABORATORY_OVERDUE'}))}catch(e:any){setError(e.message)}}
 const resolve=async()=>{try{const r=await SpecialtyClinicalApi.resolveLaboratoryPending(laboratoryWorkId,{action,alertKind:'LABORATORY_OVERDUE',solution,reason:reason||undefined,observation:observation||undefined,newDueDate:newDueDate||undefined});setState(r);setOpen(false);setSolution('');setReason('');setObservation('');setNewDueDate('')}catch(e:any){setError(e.message)}}
 if(!state&&!error)return null
 return <Stack gap={1} mt={1}>{error&&<Alert severity="error">{error}</Alert>}{state&&<Alert severity={state.state==='RESOLVED'?'success':state.state==='DISMISSED'?'info':'warning'}><Typography variant="body2"><b>Pendência laboratorial:</b> {state.state==='ACTIVE'?'ativa':state.state==='IN_TREATMENT'?'em tratamento':state.state==='RESOLVED'?'resolvida':'dispensada'}{state.protocolSeed?` • protocolo-base ${state.protocolSeed}`:''}</Typography>{state.solution&&<Typography variant="caption">{state.solution}</Typography>}</Alert>}{state?.active&&<Stack direction={{xs:'column',sm:'row'}} gap={1}><Button sx={{minHeight:44}} fullWidth={narrow} variant="outlined" onClick={()=>void start()}>Marcar em tratamento</Button><Button sx={{minHeight:44}} fullWidth={narrow} variant="contained" onClick={()=>setOpen(true)}>Resolver pendência</Button></Stack>}<Dialog open={open} onClose={()=>setOpen(false)} fullScreen={narrow} fullWidth maxWidth="sm"><DialogTitle>Resolver pendência laboratorial</DialogTitle><DialogContent><Stack gap={2} pt={1}><TextField select label="Solução" value={action} onChange={e=>setAction(e.target.value as LaboratoryResolutionAction)}>{actions.map(a=><MenuItem key={a.value} value={a.value}>{a.label}</MenuItem>)}</TextField><TextField required label="Solução adotada" value={solution} onChange={e=>setSolution(e.target.value)} multiline minRows={2}/>{['CANCELLED','RENEGOTIATED','IMPROPER_ALERT','DEMO_DATA'].includes(action)&&<TextField required label="Motivo" value={reason} onChange={e=>setReason(e.target.value)} multiline minRows={2}/>} {action==='RENEGOTIATED'&&<TextField required type="datetime-local" label="Novo prazo" value={newDueDate} onChange={e=>setNewDueDate(e.target.value)} InputLabelProps={{shrink:true}}/>}<TextField label="Observação" value={observation} onChange={e=>setObservation(e.target.value)} multiline minRows={2}/></Stack></DialogContent><DialogActions sx={{p:2,flexDirection:{xs:'column-reverse',sm:'row'},gap:1}}><Button fullWidth={narrow} sx={{minHeight:44}} onClick={()=>setOpen(false)}>Cancelar</Button><Button fullWidth={narrow} sx={{minHeight:44}} variant="contained" disabled={!solution.trim()} onClick={()=>void resolve()}>Confirmar resolução</Button></DialogActions></Dialog></Stack>
}
