import { Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, IconButton, MenuItem, Paper, TextField, Tooltip, Typography } from "@mui/material";
import EditIcon from "@mui/icons-material/Edit";
import DeleteOutlinedIcon from "@mui/icons-material/DeleteOutlined";
import { useEffect, useMemo, useState } from "react";
import type { ClinicalItemState, OdontogramMark, ToothSurface } from "../types/patientClinical";
import { listOdontogram, saveOdontogram, syncTreatmentFromOdontogram } from "../services/PatientClinicalService";

export type ToothMark = OdontogramMark;
const teeth=[18,17,16,15,14,13,12,11,21,22,23,24,25,26,27,28,48,47,46,45,44,43,42,41,31,32,33,34,35,36,37,38];
const findings=["Cárie","Restauração","Implante","Endodontia","Coroa","Núcleo metálico fundido","Dente ausente","Dente incluso","Aumento de coroa","Raspagem","Enxerto","Tracionamento","Tratamento periodontal","Prótese","Faceta","Anomalia/alteração","Outro"];

type Props={patientId?:string;patientName:string;onChange?:(marks:ToothMark[])=>void;selectionMode?:boolean;selectedIds?:string[];onSelectionChange?:(ids:string[])=>void};
export default function Odontogram({patientId,patientName,onChange,selectionMode=false,selectedIds=[],onSelectionChange}:Props){
 const resolvedId=patientId||patientName.toLowerCase().replace(/[^a-z0-9]/g,"-");
 const [marks,setMarks]=useState<ToothMark[]>([]); const [finding,setFinding]=useState("Cárie"); const [edit,setEdit]=useState<ToothMark|null>(null); const [editFinding,setEditFinding]=useState(""); const [editNote,setEditNote]=useState("");
 useEffect(()=>{const rows=listOdontogram(resolvedId);setMarks(rows);onChange?.(rows)},[resolvedId]);
 const save=(next:ToothMark[])=>{setMarks(next);saveOdontogram(resolvedId,next);syncTreatmentFromOdontogram(resolvedId,next);onChange?.(next)};
 const get=(tooth:number,surface?:ToothSurface,findingName?:string)=>marks.find(m=>m.tooth===tooth&&m.surface===surface&&(!findingName||m.finding===findingName));
 const toggle=(tooth:number,surface:ToothSurface)=>{const current=get(tooth,surface),now=new Date().toISOString();if(!current){const created:ToothMark={id:`m-${Date.now()}-${tooth}-${surface}`,tooth,surface,state:"pending",finding,createdAt:now,updatedAt:now};save([...marks,created]);if(selectionMode)onSelectionChange?.([...selectedIds,created.id]);return;}if(selectionMode){onSelectionChange?.(selectedIds.includes(current.id)?selectedIds.filter(id=>id!==current.id):[...selectedIds,current.id]);return;} openEdit(current)};
 const addFinding=(tooth:number)=>{const current=get(tooth,undefined,finding),now=new Date().toISOString();if(current){if(selectionMode){onSelectionChange?.(selectedIds.includes(current.id)?selectedIds.filter(id=>id!==current.id):[...selectedIds,current.id]);return;}openEdit(current);return;}save([...marks,{id:`m-${Date.now()}-${tooth}`,tooth,state:"pending",finding,createdAt:now,updatedAt:now}])};
 const openEdit=(m:ToothMark)=>{setEdit(m);setEditFinding(m.finding);setEditNote("")};
 const updateMark=(status?:ClinicalItemState)=>{if(!edit)return;const now=new Date().toISOString();const next:ToothMark[]=marks.map(m=>m.id===edit.id?{...m,finding:editFinding.trim()||m.finding,state:status||m.state,updatedAt:now,completedAt:(status||m.state)==="done"?now:undefined,correctionHistory:[...(m.correctionHistory||[]),{atISO:now,action:(status&&status!==m.state?"Status alterado":"Editado") as "Status alterado"|"Editado",previousFinding:m.finding,newFinding:editFinding.trim()||m.finding,note:editNote||undefined}]}:m);save(next);setEdit(null)};
 const removeMark=()=>{if(!edit)return;const now=new Date().toISOString();localStorage.setItem(`dentalpos.odontogram.audit.${resolvedId}`,JSON.stringify([...(JSON.parse(localStorage.getItem(`dentalpos.odontogram.audit.${resolvedId}`)||"[]")),{...edit,removedAt:now,note:editNote}]));save(marks.filter(m=>m.id!==edit.id));setEdit(null)};
 const color=(tooth:number,surface:ToothSurface)=>{const m=get(tooth,surface);if(!m)return"#fff";if(selectedIds.includes(m.id))return"#ffe082";return m.state==="done"?"#90caf9":"#ffcdd2"};
 const stats=useMemo(()=>({pending:marks.filter(m=>m.state==="pending").length,done:marks.filter(m=>m.state==="done").length}),[marks]);
 return <Box>
  <Box sx={{display:"flex",gap:1,alignItems:"center",mb:2,flexWrap:"wrap"}}><TextField select size="small" label="Achado/procedimento" value={finding} onChange={e=>setFinding(e.target.value)} sx={{minWidth:230}}>{findings.map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField><Chip label={`Pendentes: ${stats.pending}`} sx={{bgcolor:"#ffcdd2"}}/><Chip label={`Realizados: ${stats.done}`} sx={{bgcolor:"#90caf9"}}/>{selectionMode&&<Chip color="warning" label={`${selectedIds.length} selecionado(s)`}/>}</Box>
  <Typography variant="caption" color="text.secondary" sx={{display:"block",mb:1}}>Clique em uma marcação existente para corrigir, alterar status ou remover. Toda correção deixa registro de auditoria.</Typography>
  <Box sx={{display:"grid",gridTemplateColumns:{xs:"repeat(4,1fr)",sm:"repeat(8,1fr)",xl:"repeat(16,1fr)"},gap:1}}>{teeth.map((tooth,index)=><Paper key={tooth} variant="outlined" sx={{p:.7,textAlign:"center",borderTop:index===16?"3px solid":"1px solid",borderTopColor:index===16?"primary.main":"divider",position:"relative"}}><Typography sx={{fontWeight:900,fontSize:13}}>{tooth}</Typography><Box sx={{display:"grid",gridTemplateColumns:"repeat(3,18px)",gridTemplateRows:"repeat(3,18px)",justifyContent:"center",my:.5}}>{([["V",2,1],["M",1,2],["O/I",2,2],["D",3,2],["L/P",2,3]] as [ToothSurface,number,number][]).map(([surface,column,row])=><Tooltip key={surface} title={`${tooth} • ${surface}`}><Box onClick={()=>toggle(tooth,surface)} sx={{gridColumn:column,gridRow:row,bgcolor:color(tooth,surface),border:"1px solid #777",cursor:"pointer",boxShadow:selectedIds.includes(get(tooth,surface)?.id||"")?"0 0 0 2px #f9a825":undefined}}/></Tooltip>)}</Box><Button size="small" onClick={()=>addFinding(tooth)} sx={{fontSize:10,minWidth:0}}>+ marcador</Button>{marks.filter(m=>m.tooth===tooth&&!m.surface).slice(0,3).map(m=><Box key={m.id} sx={{display:"flex",alignItems:"center",justifyContent:"center"}}><Typography onClick={()=>selectionMode?onSelectionChange?.(selectedIds.includes(m.id)?selectedIds.filter(id=>id!==m.id):[...selectedIds,m.id]):openEdit(m)} sx={{fontSize:9,color:m.state==="done"?"primary.main":"error.main",fontWeight:800,cursor:"pointer",bgcolor:selectedIds.includes(m.id)?"warning.light":undefined,borderRadius:1}}>{m.finding}</Typography></Box>)}</Paper>)}</Box>
  <Dialog open={!!edit} onClose={()=>setEdit(null)} fullWidth maxWidth="sm"><DialogTitle>Corrigir marcação do odontograma</DialogTitle><DialogContent sx={{display:"grid",gap:2,pt:"12px!important"}}><Typography>Dente <b>{edit?.tooth}</b>{edit?.surface?` • Face ${edit.surface}`:""}</Typography><TextField select label="Achado/procedimento" value={editFinding} onChange={e=>setEditFinding(e.target.value)}>{findings.map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField><TextField multiline minRows={2} label="Motivo/observação da correção" value={editNote} onChange={e=>setEditNote(e.target.value)}/><Box sx={{display:"flex",gap:1,flexWrap:"wrap"}}><Button variant={edit?.state==="pending"?"contained":"outlined"} onClick={()=>updateMark("pending")}>Pendente</Button><Button color="success" variant={edit?.state==="done"?"contained":"outlined"} onClick={()=>updateMark("done")}>Realizado</Button></Box></DialogContent><DialogActions><IconButton color="error" onClick={removeMark}><DeleteOutlinedIcon/></IconButton><Button onClick={()=>setEdit(null)}>Cancelar</Button><Button variant="contained" startIcon={<EditIcon/>} onClick={()=>updateMark()}>Salvar correção</Button></DialogActions></Dialog>
 </Box>;
}
