import type { Appointment } from "../types/appointment";

export const appointments: Appointment[] = [
  {
    id: 1,
    patientName: "Maria Oliveira",
    professionalName: "Dr. Robson",
    procedure: "Avaliação implantodôntica",
    date: "02/08/2026",
    time: "08:00",
    room: "Consultório 1",
    status: "Confirmado",
  },
  {
    id: 2,
    patientName: "Carlos Pereira",
    professionalName: "Dr. Robson",
    procedure: "Prova de prótese",
    date: "02/08/2026",
    time: "09:00",
    room: "Consultório 2",
    status: "Aguardando",
  },
  {
    id: 3,
    patientName: "Fernanda Lima",
    professionalName: "Dra. Cássia",
    procedure: "Manutenção ortodôntica",
    date: "02/08/2026",
    time: "10:00",
    room: "Consultório 3",
    status: "Sala em preparação",
  },
  {
    id: 4,
    patientName: "João Ribeiro",
    professionalName: "Dr. Robson",
    procedure: "Cirurgia de implante",
    date: "02/08/2026",
    time: "11:00",
    room: "Centro cirúrgico",
    status: "Em atendimento",
  },
  {
    id: 5,
    patientName: "Ana Costa",
    professionalName: "Dra. Cássia",
    procedure: "Avaliação clínica",
    date: "02/08/2026",
    time: "14:00",
    room: "Consultório 4",
    status: "Agendado",
  },
];