import type { FinancialEntry } from "../types/financial";

export const financialEntries: FinancialEntry[] = [
  {
    id: 1,
    description: "Tratamento implantodôntico",
    category: "Implantodontia",
    personName: "Maria Oliveira",
    type: "Receita",
    status: "Pago",
    value: 8500,
    dueDate: "02/08/2026",
    paymentMethod: "PIX",
  },
  {
    id: 2,
    description: "Parcela de tratamento ortodôntico",
    category: "Ortodontia",
    personName: "Fernanda Lima",
    type: "Receita",
    status: "Pendente",
    value: 680,
    dueDate: "05/08/2026",
    paymentMethod: "Boleto",
  },
  {
    id: 3,
    description: "Compra de componentes protéticos",
    category: "Materiais",
    personName: "Fornecedor Dental",
    type: "Despesa",
    status: "Pendente",
    value: 4200,
    dueDate: "08/08/2026",
  },
  {
    id: 4,
    description: "Manutenção da autoclave",
    category: "Manutenção",
    personName: "Assistência Técnica",
    type: "Despesa",
    status: "Pago",
    value: 950,
    dueDate: "01/08/2026",
    paymentMethod: "Transferência",
  },
  {
    id: 5,
    description: "Prótese protocolo",
    category: "Prótese",
    personName: "Carlos Pereira",
    type: "Receita",
    status: "Vencido",
    value: 3200,
    dueDate: "30/07/2026",
    paymentMethod: "Boleto",
  },
];