import type { InventoryItem } from "../types/inventory";

export const inventoryItems: InventoryItem[] = [
  {
    id: 1,
    code: "W48-CM-25",
    name: "Multiple W48 Cone Morse 2,5 mm",
    category: "Componentes",
    supplier: "DentalPos Componentes",
    currentQuantity: 18,
    minimumQuantity: 20,
    unit: "unidades",
    batch: "W48250826",
    expirationDate: "02/08/2031",
    location: "Prateleira A1",
    unitCost: 35,
    status: "Estoque baixo",
  },
  {
    id: 2,
    code: "RES-A2-001",
    name: "Resina composta A2",
    category: "Materiais clínicos",
    supplier: "Fornecedor Dental",
    currentQuantity: 3,
    minimumQuantity: 10,
    unit: "seringas",
    batch: "RA2202607",
    expirationDate: "15/10/2026",
    location: "Armário Clínico 2",
    unitCost: 78.5,
    status: "Crítico",
  },
  {
    id: 3,
    code: "LUVA-M-100",
    name: "Luva de procedimento tamanho M",
    category: "Biossegurança",
    supplier: "Distribuidora Médica",
    currentQuantity: 42,
    minimumQuantity: 20,
    unit: "caixas",
    batch: "LM072026",
    expirationDate: "30/06/2030",
    location: "Almoxarifado",
    unitCost: 29.9,
    status: "Normal",
  },
  {
    id: 4,
    code: "TOX-100U",
    name: "Toxina botulínica 100 U",
    category: "Medicamentos",
    supplier: "Distribuidora Farmacêutica",
    currentQuantity: 6,
    minimumQuantity: 3,
    unit: "frascos",
    batch: "TB1002604",
    expirationDate: "20/09/2026",
    location: "Geladeira farmacêutica",
    unitCost: 690,
    status: "Vencimento próximo",
  },
  {
    id: 5,
    code: "CAFE-500",
    name: "Café torrado e moído 500 g",
    category: "Copa",
    supplier: "Supermercado",
    currentQuantity: 2,
    minimumQuantity: 4,
    unit: "pacotes",
    batch: "CF082026",
    expirationDate: "12/02/2027",
    location: "Armário da copa",
    unitCost: 24.9,
    status: "Estoque baixo",
  },
  {
    id: 6,
    code: "PAPEL-TOALHA",
    name: "Papel-toalha interfolhado",
    category: "Limpeza",
    supplier: "Fornecedor de limpeza",
    currentQuantity: 16,
    minimumQuantity: 10,
    unit: "pacotes",
    batch: "PT082026",
    location: "Depósito de limpeza",
    unitCost: 18.4,
    status: "Normal",
  },
];

export function calculateInventoryValue(
  items: InventoryItem[],
): number {
  return items.reduce(
    (total, item) =>
      total + item.currentQuantity * item.unitCost,
    0,
  );
}