const API_BASE = (import.meta.env.VITE_API_URL || "http://localhost:3000/api").replace(/\/$/, "");
function headers() { const token=localStorage.getItem("accessToken")||localStorage.getItem("token")||localStorage.getItem("dentalpos.accessToken")||localStorage.getItem("dentalpos.token"); const clinicId=localStorage.getItem("dentalpos.clinicId"); return {"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{ }),...(clinicId?{"X-Clinic-ID":clinicId}:{})}; }
async function request<T>(path:string,init?:RequestInit):Promise<T>{const r=await fetch(`${API_BASE}${path}`,{...init,headers:{...headers(),...(init?.headers||{})}});if(!r.ok){const b=await r.json().catch(()=>({}));throw new Error(b.error||`Erro HTTP ${r.status}`)}return r.status===204?undefined as T:r.json()}
export type TreatmentPlanningData={region?:string|null;phase?:string;priority?:string;alternative?:string|null;specialty?:string|null;professionalId?:string|null;professionalName?:string|null;estimatedMinutes?:number|null;laboratoryRequired?:boolean;laboratoryNotes?:string|null;examRequired?:boolean;surgeryRequired?:boolean;sequence?:number;dependsOn?:string[];cbhpoCode?:string|null;unitValue?:number;notes?:string|null};
export type TreatmentPlanItem={id:string;patientId:string;tooth:number|null;surfaces:string[];procedure:string;status:string;origin:string;planningData?:TreatmentPlanningData|null;createdAt:string;updatedAt:string};
export const getTreatmentPlan=(patientId:string)=>request<{items:TreatmentPlanItem[];progressPercent:number}>(`/patients/${encodeURIComponent(patientId)}/treatment-plan-v2`);
export const createTreatmentItem=(patientId:string,data:any)=>request<TreatmentPlanItem>(`/patients/${encodeURIComponent(patientId)}/treatment-plan-v2/items`,{method:"POST",body:JSON.stringify(data)});
export const updateTreatmentItem=(id:string,data:any)=>request<TreatmentPlanItem>(`/treatment-plan-v2/items/${encodeURIComponent(id)}`,{method:"PUT",body:JSON.stringify(data)});
export const importOdontogram=(patientId:string)=>request<{imported:number}>(`/patients/${encodeURIComponent(patientId)}/treatment-plan-v2/import-odontogram`,{method:"POST",body:"{}"});
export const getTreatmentPlanRevisions=(patientId:string)=>request<any[]>(`/patients/${encodeURIComponent(patientId)}/treatment-plan-v2/revisions`);
