export type FunnelStage =
  | "Lead"
  | "Contato"
  | "Agendado"
  | "Chegou"
  | "Triagem"
  | "Consulta"
  | "Planejamento"
  | "Orçamento"
  | "Negociação"
  | "Aprovado"
  | "Cirurgia"
  | "Prótese"
  | "Controle"
  | "Garantia"
  | "Recall"
  | "Indicação";