import { Response } from 'express'
import { AuthRequest } from '../middleware/auth'
import { getFinancialAlertResolutionStates, markFinancialAlertInProgress, resolveFinancialAlertFromOperation } from '../services/financialAlertResolutionService'

function context(req:AuthRequest){ if(!req.user) throw new Error('Não autenticado'); return { clinicId:req.user.clinicId, tenantId:req.user.tenantId, actorId:req.user.id, ipAddress:req.ip, userAgent:req.get('user-agent') } }
const entities = new Set(['FinancialEntry','Payment','Budget'])
const actions = new Set(['PAYMENT','SETTLEMENT','RENEGOTIATION','CANCELLATION','ADJUSTMENT','REVERSAL','DISMISSAL'])

export async function listResolutionStates(req:AuthRequest,res:Response){ try{const c=context(req);const ids=typeof req.query.ids==='string'?req.query.ids.split(',').map(x=>x.trim()).filter(Boolean):undefined;return res.json(await getFinancialAlertResolutionStates({clinicId:c.clinicId,tenantId:c.tenantId},ids))}catch(e){console.error(e);return res.status(500).json({error:'Erro ao listar estados de alertas financeiros.'})} }
export async function markInProgress(req:AuthRequest,res:Response){ try{const c=context(req),t=String(req.body.sourceEntityType||''),id=String(req.body.sourceEntityId||'');if(!entities.has(t)||!id)return res.status(400).json({error:'Entidade financeira de origem inválida.'});return res.json(await markFinancialAlertInProgress(c,t as any,id))}catch(e:any){return res.status(400).json({error:e?.message||'Erro ao colocar alerta financeiro em tratamento.'})} }
export async function resolveFromOperation(req:AuthRequest,res:Response){ try{const c=context(req),t=String(req.body.sourceEntityType||''),id=String(req.body.sourceEntityId||''),a=String(req.body.action||'');if(!entities.has(t)||!id)return res.status(400).json({error:'Entidade financeira de origem inválida.'});if(!actions.has(a))return res.status(400).json({error:'Ação financeira inválida.'});return res.json(await resolveFinancialAlertFromOperation(c,{sourceEntityType:t as any,sourceEntityId:id,action:a as any,reason:typeof req.body.reason==='string'?req.body.reason:undefined,replacementEntityType:req.body.replacementEntityType as any,replacementEntityId:typeof req.body.replacementEntityId==='string'?req.body.replacementEntityId:undefined,metadata:req.body.metadata&&typeof req.body.metadata==='object'?req.body.metadata:undefined}))}catch(e:any){return res.status(400).json({error:e?.message||'Erro ao resolver alerta financeiro.'})} }
