import type { Request, Response } from 'express'
import { prisma } from '../lib/prisma'
import { writeAudit } from '../services/auditService'

function requestContext(req: Request) {
  const user = (req as any).user || {}
  return { clinicId: user.clinicId as string, tenantId: user.tenantId as string, actorId: user.id as string | undefined }
}
function paramId(req: Request): string { const v=req.params.id; return Array.isArray(v)?v[0]:v }
function toDate(v:unknown):Date|undefined { if(!v)return undefined; return new Date(String(v)) }
async function getEmployee(clinicId:string,tenantId:string,employeeId:string){return prisma.hREmployee.findFirst({where:{id:employeeId,clinicId,tenantId}})}

export async function dashboard(req:Request,res:Response){const c=requestContext(req);const now=new Date(),start=new Date(now),end=new Date(now),next30=new Date(now);start.setHours(0,0,0,0);end.setHours(23,59,59,999);next30.setDate(next30.getDate()+30);const [totalEmployees,activeEmployees,inactiveEmployees,attendanceToday,scheduledVacations,expiringDocuments]=await Promise.all([prisma.hREmployee.count({where:{clinicId:c.clinicId,tenantId:c.tenantId}}),prisma.hREmployee.count({where:{clinicId:c.clinicId,tenantId:c.tenantId,status:'ACTIVE'}}),prisma.hREmployee.count({where:{clinicId:c.clinicId,tenantId:c.tenantId,status:'INACTIVE'}}),prisma.hRAttendance.count({where:{clinicId:c.clinicId,tenantId:c.tenantId,date:{gte:start,lte:end}}}),prisma.hRVacation.count({where:{clinicId:c.clinicId,tenantId:c.tenantId,status:{in:['SCHEDULED','APPROVED']}}}),prisma.hRDocument.count({where:{clinicId:c.clinicId,tenantId:c.tenantId,expiresAt:{gte:now,lte:next30}}})]);return res.json({totalEmployees,activeEmployees,inactiveEmployees,attendanceToday,scheduledVacations,expiringDocuments})}
export async function employees(req:Request,res:Response){const c=requestContext(req);return res.json(await prisma.hREmployee.findMany({where:{clinicId:c.clinicId,tenantId:c.tenantId},orderBy:{name:'asc'}}))}
export const listEmployees=employees
export async function createEmployee(req:Request,res:Response){const c=requestContext(req),b=req.body;if(!b.employeeCode)return res.status(400).json({error:'Código do colaborador é obrigatório.'});const existing=await prisma.hREmployee.findFirst({where:{clinicId:c.clinicId,employeeCode:String(b.employeeCode)}});if(existing)return res.status(409).json({error:'Já existe um colaborador com este código.'});const row=await prisma.hREmployee.create({data:{clinicId:c.clinicId,tenantId:c.tenantId,employeeCode:String(b.employeeCode),name:b.name,category:b.category,department:b.department,position:b.position,employmentModel:b.employmentModel,status:b.status||'ACTIVE',admissionDate:toDate(b.admissionDate)??new Date(),experienceEndDate:b.experienceEndDate?toDate(b.experienceEndDate):null,terminationDate:b.terminationDate?toDate(b.terminationDate):null,baseSalary:b.baseSalary??0,monthlyWorkload:b.monthlyWorkload??220,supervisor:b.supervisor,email:b.email,phone:b.phone,cpf:b.cpf,pixKey:b.pixKey,notes:b.notes}});await writeAudit({clinicId:c.clinicId,tenantId:c.tenantId,actorId:c.actorId,module:'hr',action:'create',entityType:'HREmployee',entityId:row.id,afterData:row});return res.status(201).json(row)}
export async function updateEmployee(req:Request,res:Response){const c=requestContext(req),employeeId=paramId(req),b=req.body,before=await getEmployee(c.clinicId,c.tenantId,employeeId);if(!before)return res.status(404).json({error:'Colaborador não encontrado.'});const row=await prisma.hREmployee.update({where:{id:before.id},data:{employeeCode:b.employeeCode!==undefined?String(b.employeeCode):undefined,name:b.name,category:b.category,department:b.department,position:b.position,employmentModel:b.employmentModel,status:b.status,admissionDate:b.admissionDate!==undefined?toDate(b.admissionDate):undefined,experienceEndDate:b.experienceEndDate===null?null:b.experienceEndDate!==undefined?toDate(b.experienceEndDate):undefined,terminationDate:b.terminationDate===null?null:b.terminationDate!==undefined?toDate(b.terminationDate):undefined,baseSalary:b.baseSalary,monthlyWorkload:b.monthlyWorkload,supervisor:b.supervisor,email:b.email,phone:b.phone,cpf:b.cpf,pixKey:b.pixKey,notes:b.notes}});await writeAudit({clinicId:c.clinicId,tenantId:c.tenantId,actorId:c.actorId,module:'hr',action:'edit',entityType:'HREmployee',entityId:row.id,beforeData:before,afterData:row});return res.json(row)}
export async function deleteEmployee(req:Request,res:Response){const c=requestContext(req),employeeId=paramId(req),before=await getEmployee(c.clinicId,c.tenantId,employeeId);if(!before)return res.status(404).json({error:'Colaborador não encontrado.'});const row=await prisma.hREmployee.update({where:{id:before.id},data:{status:'INACTIVE',terminationDate:before.terminationDate??new Date()}});await writeAudit({clinicId:c.clinicId,tenantId:c.tenantId,actorId:c.actorId,module:'hr',action:'deactivate',entityType:'HREmployee',entityId:row.id,beforeData:before,afterData:row});return res.json(row)}
export async function createAttendance(req:Request,res:Response){const c=requestContext(req),b=req.body,emp=await getEmployee(c.clinicId,c.tenantId,String(b.employeeId));if(!emp)return res.status(404).json({error:'Colaborador não encontrado.'});const row=await prisma.hRAttendance.create({data:{clinicId:c.clinicId,tenantId:c.tenantId,employeeId:emp.id,date:toDate(b.date)??new Date(),status:b.status,clockIn:b.clockIn,clockOut:b.clockOut,overtimeHours:b.overtimeHours??0,balanceHours:b.balanceHours??0,observation:b.observation}});return res.status(201).json(row)}
export async function createPayrollEntry(req:Request,res:Response){const c=requestContext(req),b=req.body,emp=await getEmployee(c.clinicId,c.tenantId,String(b.employeeId));if(!emp)return res.status(404).json({error:'Colaborador não encontrado.'});const row=await prisma.hRPayrollEntry.create({data:{clinicId:c.clinicId,tenantId:c.tenantId,employeeId:emp.id,reference:b.reference,type:b.type,description:b.description,value:b.value}});return res.status(201).json(row)}
export async function closePayroll(req:Request,res:Response){
  const c=requestContext(req),b=req.body
  if(!b.reference)return res.status(400).json({error:'Referência da folha é obrigatória.'})
  const reference=String(b.reference)
  const entries=await prisma.hRPayrollEntry.findMany({where:{clinicId:c.clinicId,tenantId:c.tenantId,reference}})
  let gross=0,discounts=0
  for(const e of entries){
    const v=Number(e.value),type=String(e.type).toUpperCase()
    if(['DISCOUNT','DESCONTO','DEDUCTION','DEDUCAO','DEDUÇÃO'].includes(type))discounts+=v
    else if(!['ENCARGO','CHARGE'].includes(type))gross+=v
  }
  const explicitCharges=entries.filter(e=>['ENCARGO','CHARGE'].includes(String(e.type).toUpperCase())).reduce((total,e)=>total+Number(e.value),0)
  const charges=Number(b.employerCharges??explicitCharges??0),net=gross-discounts
  const count=await prisma.hREmployee.count({where:{clinicId:c.clinicId,tenantId:c.tenantId,status:'ACTIVE'}})
  const paymentDate=b.paymentDate?toDate(b.paymentDate):new Date()
  const row=await prisma.hRPayrollClosing.upsert({where:{clinicId_reference:{clinicId:c.clinicId,reference}},update:{grossPayroll:gross,discounts,employerCharges:charges,netPayroll:net,employeeCount:count,status:b.status||'CLOSED',paymentDate},create:{clinicId:c.clinicId,tenantId:c.tenantId,reference,grossPayroll:gross,discounts,employerCharges:charges,netPayroll:net,employeeCount:count,status:b.status||'CLOSED',paymentDate}})

  const syncPayable=async(originId:string,description:string,amount:number,category:string)=>{
    if(amount<=0)return
    const existing=await prisma.financialEntry.findFirst({where:{clinicId:c.clinicId,tenantId:c.tenantId,origin:'HR',originId}})
    const data={type:'EXPENSE',description,category,personName:'Folha de pagamento',amount,netAmount:amount,dueDate:paymentDate??new Date(),competenceDate:paymentDate??new Date(),status:'PENDING',paymentMethod:'TRANSFER',origin:'HR',originId,accountingMode:'PAYROLL',accountingStatus:'REVIEWED'}
    if(existing)await prisma.financialEntry.update({where:{id:existing.id},data})
    else await prisma.financialEntry.create({data:{clinicId:c.clinicId,tenantId:c.tenantId,...data}})
  }
  await syncPayable(`payroll-net:${reference}`,`Folha líquida • ${reference}`,net,'FOLHA')
  await syncPayable(`payroll-charges:${reference}`,`Encargos da folha • ${reference}`,charges,'ENCARGOS_TRABALHISTAS')
  await writeAudit({clinicId:c.clinicId,tenantId:c.tenantId,actorId:c.actorId,module:'hr',action:'PAYROLL_CLOSE',entityType:'HRPayrollClosing',entityId:row.id,afterData:row,summary:`Folha ${reference} fechada e integrada ao contas a pagar.`})
  return res.json(row)
}
export async function createVacation(req:Request,res:Response){const c=requestContext(req),b=req.body,emp=await getEmployee(c.clinicId,c.tenantId,String(b.employeeId));if(!emp)return res.status(404).json({error:'Colaborador não encontrado.'});const a=toDate(b.acquisitionStart),z=toDate(b.acquisitionEnd),deadline=toDate(b.concessionDeadline);if(!a||!z||!deadline)return res.status(400).json({error:'Período aquisitivo e prazo de concessão são obrigatórios.'});const row=await prisma.hRVacation.create({data:{clinicId:c.clinicId,tenantId:c.tenantId,employeeId:emp.id,acquisitionStart:a,acquisitionEnd:z,concessionDeadline:deadline,scheduledStart:b.scheduledStart?toDate(b.scheduledStart):null,scheduledEnd:b.scheduledEnd?toDate(b.scheduledEnd):null,vacationDays:b.vacationDays??30,soldDays:b.soldDays??0,status:b.status||'PLANNED'}});return res.status(201).json(row)}
export async function createDocument(req:Request,res:Response){const c=requestContext(req),b=req.body,emp=await getEmployee(c.clinicId,c.tenantId,String(b.employeeId));if(!emp)return res.status(404).json({error:'Colaborador não encontrado.'});const issued=toDate(b.issuedAt);if(!issued)return res.status(400).json({error:'Data de emissão é obrigatória.'});const row=await prisma.hRDocument.create({data:{clinicId:c.clinicId,tenantId:c.tenantId,employeeId:emp.id,type:b.type,title:b.title,issuedAt:issued,expiresAt:b.expiresAt?toDate(b.expiresAt):null,status:b.status||'ACTIVE',digitallySigned:Boolean(b.digitallySigned),fileUrl:b.fileUrl,notes:b.notes}});return res.status(201).json(row)}
export async function createDiscipline(req:Request,res:Response){const c=requestContext(req),b=req.body,emp=await getEmployee(c.clinicId,c.tenantId,String(b.employeeId));if(!emp)return res.status(404).json({error:'Colaborador não encontrado.'});const row=await prisma.hRDisciplinaryAction.create({data:{clinicId:c.clinicId,tenantId:c.tenantId,employeeId:emp.id,type:b.type,date:toDate(b.date)??new Date(),reason:b.reason,daysSuspended:b.daysSuspended!==undefined?Number(b.daysSuspended):null,status:b.status||'APPLIED'}});return res.status(201).json(row)}
