import { Response } from 'express'
import { prisma } from '../lib/prisma'
import { AuthRequest } from '../middleware/auth'
import { writeAudit } from '../services/auditService'

function user(req:AuthRequest){if(!req.user)throw new Error('Não autenticado');return req.user}
export async function index(req:AuthRequest,res:Response){try{const u=user(req);return res.json(await prisma.payment.findMany({where:{clinicId:u.clinicId,tenantId:u.tenantId},include:{budget:{include:{patient:true}},appointment:true},orderBy:{dueDate:'asc'}}))}catch(error){console.error(error);return res.status(500).json({error:'Erro ao listar pagamentos.'})}}
export async function show(req:AuthRequest,res:Response){try{const u=user(req);const row=await prisma.payment.findFirst({where:{id:String(req.params.id),clinicId:u.clinicId,tenantId:u.tenantId},include:{budget:true,appointment:true}});if(!row)return res.status(404).json({error:'Pagamento não encontrado.'});return res.json(row)}catch(error){console.error(error);return res.status(500).json({error:'Erro ao buscar pagamento.'})}}
export async function store(req:AuthRequest,res:Response){try{const u=user(req);const b=req.body;const budget=await prisma.budget.findFirst({where:{id:String(b.budgetId),clinicId:u.clinicId,tenantId:u.tenantId}});if(!budget)return res.status(404).json({error:'Orçamento não encontrado.'});const row=await prisma.payment.create({data:{clinicId:u.clinicId,tenantId:u.tenantId,budgetId:budget.id,appointmentId:b.appointmentId||null,amount:Number(b.amount),grossAmount:Number(b.amount),netAmount:Number(b.amount),method:String(b.method||'PIX'),provider:b.provider?String(b.provider):null,installment:Number(b.installment||1),dueDate:new Date(b.dueDate),status:String(b.status||'PENDING'),notes:b.notes?String(b.notes):null}});return res.status(201).json(row)}catch(error){console.error(error);return res.status(500).json({error:'Erro ao criar pagamento.'})}}
export async function update(req:AuthRequest,res:Response){try{const u=user(req);const id=String(req.params.id);const existing=await prisma.payment.findFirst({where:{id,clinicId:u.clinicId,tenantId:u.tenantId}});if(!existing)return res.status(404).json({error:'Pagamento não encontrado.'});const b=req.body;const data:any={};for(const k of ['method','provider','status','notes','asaasId','externalId','transactionStatus'])if(b[k]!==undefined)data[k]=b[k];for(const k of ['amount','grossAmount','feeAmount','netAmount'])if(b[k]!==undefined)data[k]=Number(b[k]);if(b.dueDate!==undefined)data.dueDate=new Date(b.dueDate);if(b.paidDate!==undefined)data.paidDate=b.paidDate?new Date(b.paidDate):null;const row=await prisma.payment.update({where:{id},data});await writeAudit({clinicId:u.clinicId,tenantId:u.tenantId,actorId:u.id,module:'finance',action:'PAYMENT_UPDATE',entityType:'Payment',entityId:id,beforeData:existing,afterData:row,summary:'Pagamento atualizado.'});return res.json(row)}catch(error){console.error(error);return res.status(500).json({error:'Erro ao atualizar pagamento.'})}}
export async function settle(req:AuthRequest,res:Response){try{const u=user(req);const id=String(req.params.id);const existing=await prisma.payment.findFirst({where:{id,clinicId:u.clinicId,tenantId:u.tenantId},include:{budget:{include:{patient:true}}}});if(!existing)return res.status(404).json({error:'Pagamento não encontrado.'});const fee=Number(req.body.feeAmount||0);const gross=Number(req.body.grossAmount||existing.amount);const net=gross-fee;const row=await prisma.$transaction(async tx=>{const paid=await tx.payment.update({where:{id},data:{status:'PAID',paidDate:new Date(),grossAmount:gross,feeAmount:fee,netAmount:net,transactionStatus:'SETTLED'}});const related=await tx.financialEntry.findFirst({where:{clinicId:u.clinicId,tenantId:u.tenantId,origin:'BUDGET',originId:existing.budgetId,installment:existing.installment}});if(related)await tx.financialEntry.update({where:{id:related.id},data:{status:'PAID',paidAt:new Date(),externalId:existing.externalId}});return paid});await writeAudit({clinicId:u.clinicId,tenantId:u.tenantId,actorId:u.id,module:'finance',action:'PAYMENT_SETTLE',entityType:'Payment',entityId:id,beforeData:existing,afterData:row,summary:`Recebimento baixado: ${existing.budget.patient.fullName}.`});return res.json(row)}catch(error){console.error(error);return res.status(500).json({error:'Erro ao baixar pagamento.'})}}
export async function remove(req:AuthRequest,res:Response){try{const u=user(req);const id=String(req.params.id);const existing=await prisma.payment.findFirst({where:{id,clinicId:u.clinicId,tenantId:u.tenantId}});if(!existing)return res.status(404).json({error:'Pagamento não encontrado.'});const row=await prisma.payment.update({where:{id},data:{status:'CANCELLED',transactionStatus:'CANCELLED'}});return res.json(row)}catch(error){console.error(error);return res.status(500).json({error:'Erro ao cancelar pagamento.'})}}
