import type { Request, Response } from 'express'
import { prisma } from '../lib/prisma'
import { dispatchRevah, type RevahChannel } from '../services/revahProviderService'
import { writeAudit } from '../services/auditService'
import { decryptSecret } from '../services/secretVault'
function c(req:Request){const u=(req as any).user||{};return{clinicId:u.clinicId as string,tenantId:u.tenantId as string,actorId:u.id as string|undefined}}
function id(req:Request){const v=req.params.id;return Array.isArray(v)?v[0]:v}
export async function campaigns(req:Request,res:Response){const x=c(req);res.json(await prisma.revahCampaign.findMany({where:{clinicId:x.clinicId,tenantId:x.tenantId},orderBy:{createdAt:'desc'}}))}
export async function createCampaign(req:Request,res:Response){const x=c(req),b=req.body;const row=await prisma.revahCampaign.create({data:{clinicId:x.clinicId,tenantId:x.tenantId,name:b.name,channel:b.channel,audience:b.audience||'Manual',template:b.template,status:b.status||'DRAFT',scheduledAt:b.scheduledAt?new Date(b.scheduledAt):null,createdById:x.actorId,recurrence:b.recurrence||null,nextRunAt:b.nextRunAt?new Date(b.nextRunAt):null}});await writeAudit({clinicId:x.clinicId,tenantId:x.tenantId,actorId:x.actorId,module:'revah',action:'CAMPAIGN_CREATE',entityType:'RevahCampaign',entityId:row.id,afterData:row});res.status(201).json(row)}
export async function contacts(req:Request,res:Response){const x=c(req);res.json(await prisma.revahContact.findMany({where:{clinicId:x.clinicId,tenantId:x.tenantId},orderBy:{name:'asc'}}))}
export async function createContact(req:Request,res:Response){const x=c(req);const row=await prisma.revahContact.create({data:{clinicId:x.clinicId,tenantId:x.tenantId,...req.body}});res.status(201).json(row)}
export async function optOut(req:Request,res:Response){const x=c(req),contactId=id(req);const row=await prisma.revahContact.updateMany({where:{clinicId:x.clinicId,tenantId:x.tenantId,id:contactId},data:{whatsappOptIn:false,smsOptIn:false,emailOptIn:false,telegramOptIn:false,phoneOptIn:false,optedOutAt:new Date()}});await writeAudit({clinicId:x.clinicId,tenantId:x.tenantId,actorId:x.actorId,module:'revah',action:'OPTOUT',entityType:'RevahContact',entityId:contactId});res.json(row)}
export async function send(req:Request,res:Response){const x=c(req);const {channel,destination,content,contactName='Contato',campaignId,senderId}=req.body;const sender=senderId?await prisma.revahSender.findFirst({where:{clinicId:x.clinicId,tenantId:x.tenantId,id:senderId,isActive:true}}):await prisma.revahSender.findFirst({where:{clinicId:x.clinicId,tenantId:x.tenantId,channel:String(channel).toUpperCase(),isDefault:true,isActive:true}});if(!sender)return res.status(409).json({error:'Configure um remetente ativo para este canal.'});const contact=await prisma.revahContact.findFirst({where:{clinicId:x.clinicId,tenantId:x.tenantId,OR:[{phone:destination},{email:destination},{telegramChatId:destination}]}});const ch=String(channel).toUpperCase() as RevahChannel;const opt=ch==='WHATSAPP'?contact?.whatsappOptIn:ch==='SMS'?contact?.smsOptIn:ch==='EMAIL'?contact?.emailOptIn:ch==='TELEGRAM'?contact?.telegramOptIn:contact?.phoneOptIn;if(contact&&opt===false)return res.status(409).json({error:'Contato sem consentimento/opt-in para este canal.'});const creds=decryptSecret<any>(sender.encryptedCredentials)||{};const result=await dispatchRevah(ch,destination,content,creds,sender.address);const msg=await prisma.revahMessage.create({data:{clinicId:x.clinicId,tenantId:x.tenantId,campaignId:campaignId||null,senderId:sender.id,channel:ch,destination,content,contactName,provider:sender.provider||result.provider,providerMessageId:result.providerMessageId,status:result.simulated?'SIMULATED':'SENT',sentAt:new Date()}});await writeAudit({clinicId:x.clinicId,tenantId:x.tenantId,actorId:x.actorId,module:'revah',action:'SEND',entityType:'RevahMessage',entityId:msg.id,metadata:{channel:ch,provider:result.provider,simulated:result.simulated}});res.status(201).json(msg)}
export async function messages(req:Request,res:Response){const x=c(req);res.json(await prisma.revahMessage.findMany({where:{clinicId:x.clinicId,tenantId:x.tenantId},orderBy:{createdAt:'desc'},take:200}))}
export async function automations(req:Request,res:Response){const x=c(req);res.json(await prisma.revahAutomation.findMany({where:{clinicId:x.clinicId,tenantId:x.tenantId},orderBy:{name:'asc'}}))}
export async function createAutomation(req:Request,res:Response){const x=c(req),b=req.body;const row=await prisma.revahAutomation.create({data:{clinicId:x.clinicId,tenantId:x.tenantId,name:String(b.name),trigger:String(b.trigger),channel:String(b.channel),template:String(b.template),delayMinutes:Number(b.delayMinutes||0),recurrence:b.recurrence||null,filters:b.filters||undefined,isActive:b.isActive!==false}});res.status(201).json(row)}
