import type {Request,Response} from 'express'
import {prisma} from '../lib/prisma'
import {writeAudit} from '../services/auditService'
function c(req:Request){const u=(req as any).user||{};return{clinicId:u.clinicId as string,tenantId:u.tenantId as string,actorId:u.id as string|undefined}}
function id(req:Request){const v=req.params.id;return Array.isArray(v)?v[0]:v}
export async function leads(req:Request,res:Response){const x=c(req);res.json(await prisma.salesLead.findMany({where:{clinicId:x.clinicId,tenantId:x.tenantId},orderBy:{updatedAt:'desc'}}))}
export async function createLead(req:Request,res:Response){const x=c(req);const row=await prisma.salesLead.create({data:{clinicId:x.clinicId,tenantId:x.tenantId,...req.body,estimatedValue:req.body.estimatedValue||0,nextActionAt:req.body.nextActionAt?new Date(req.body.nextActionAt):null}});await prisma.salesLeadEvent.create({data:{clinicId:x.clinicId,tenantId:x.tenantId,leadId:row.id,actorId:x.actorId,type:'CREATED',toStage:row.stage,summary:`Lead ${row.name} criado`}});await writeAudit({clinicId:x.clinicId,tenantId:x.tenantId,actorId:x.actorId,module:'sales',action:'LEAD_CREATE',entityType:'SalesLead',entityId:row.id});res.status(201).json(row)}
export async function updateLead(req:Request,res:Response){const x=c(req),leadId=id(req);const before=await prisma.salesLead.findFirst({where:{clinicId:x.clinicId,tenantId:x.tenantId,id:leadId}});if(!before)return res.status(404).json({error:'Lead não encontrado.'});const stage=req.body.stage;const row=await prisma.salesLead.update({where:{id:before.id},data:{...req.body,nextActionAt:req.body.nextActionAt===null?null:req.body.nextActionAt!==undefined?new Date(req.body.nextActionAt):undefined,convertedAt:stage==='WON'||stage==='CONVERTED'?new Date():undefined,lostAt:stage==='LOST'?new Date():undefined}});if(stage&&stage!==before.stage)await prisma.salesLeadEvent.create({data:{clinicId:x.clinicId,tenantId:x.tenantId,leadId:row.id,actorId:x.actorId,type:'STAGE_CHANGED',fromStage:before.stage,toStage:stage,summary:`${before.stage} → ${stage}`}});res.json(row)}
export async function journey(req:Request,res:Response){const x=c(req),leadId=id(req);res.json(await prisma.salesLeadEvent.findMany({where:{clinicId:x.clinicId,tenantId:x.tenantId,leadId},orderBy:{createdAt:'asc'}}))}
export async function products(req:Request,res:Response){const x=c(req);res.json(await prisma.salesProduct.findMany({where:{clinicId:x.clinicId,tenantId:x.tenantId},orderBy:{name:'asc'}}))}
export async function upsertProduct(req:Request,res:Response){const x=c(req);const{sku,...data}=req.body;const row=await prisma.salesProduct.upsert({where:{clinicId_sku:{clinicId:x.clinicId,sku}},update:data,create:{clinicId:x.clinicId,tenantId:x.tenantId,sku,...data}});res.json(row)}
