import { randomUUID } from 'crypto'
import { Prisma } from '@prisma/client'
import type { Response } from 'express'
import { prisma } from '../lib/prisma'
import type { AuthRequest } from '../middleware/auth'
import { writeAudit } from '../services/auditService'
import { ValidationError, validateImplant, validateProsthesis, validateSurgery } from '../validation/specialtyClinicalValidation'

const context = (req: AuthRequest) => ({ clinicId: req.user!.clinicId, tenantId: req.user!.tenantId, actorId: req.user!.id })
const error = (res: Response, e: unknown) => {
  if (e instanceof ValidationError) return res.status(400).json({ error: e.message })
  console.error('[specialty-clinical]', e)
  return res.status(500).json({ error: 'Erro interno no núcleo clínico especializado' })
}
const json = (v: unknown) => Prisma.sql`${JSON.stringify(v ?? null)}::jsonb`
const nullableDate = (v: unknown) => v ? new Date(String(v)) : null
const routeParam = (req: AuthRequest, key: string): string => { const value = req.params[key]; return Array.isArray(value) ? (value[0] ?? '') : String(value ?? '') }

async function ensurePatient(patientId: string, req: AuthRequest) {
  const c = context(req)
  const patient = await prisma.patient.findFirst({ where: { id: patientId, clinicId: c.clinicId, tenantId: c.tenantId, isActive: true }, select: { id: true } })
  if (!patient) throw new ValidationError('Paciente não encontrado nesta clínica')
}
async function ensureLabLink(id: string | null | undefined, req: AuthRequest) {
  if (!id) return
  const c = context(req)
  const row = await prisma.laboratoryWork.findFirst({ where: { id, clinicId: c.clinicId, tenantId: c.tenantId }, select: { id: true } })
  if (!row) throw new ValidationError('Ordem de laboratório inválida para esta clínica')
}
async function ensureOwned(table: 'SurgeryCase'|'ImplantRecord'|'ProsthesisCase', id: string | null | undefined, req: AuthRequest) {
  if (!id) return
  const c = context(req)
  const rows = await prisma.$queryRaw<{id:string}[]>(Prisma.sql`SELECT "id" FROM ${Prisma.raw(`"${table}"`)} WHERE "id"=${id} AND "clinicId"=${c.clinicId} AND "tenantId"=${c.tenantId} LIMIT 1`)
  if (!rows[0]) throw new ValidationError('Vínculo clínico inválido para esta clínica')
}

export async function listSurgeries(req: AuthRequest, res: Response) {
  try { const c=context(req); await ensurePatient(routeParam(req,'patientId'),req)
    const rows=await prisma.$queryRaw(Prisma.sql`SELECT s.*, COALESCE((SELECT jsonb_agg(f ORDER BY f."followUpAt" DESC) FROM "SurgeryFollowUp" f WHERE f."surgeryCaseId"=s."id"),'[]'::jsonb) AS "followUps" FROM "SurgeryCase" s WHERE s."patientId"=${routeParam(req,'patientId')} AND s."clinicId"=${c.clinicId} AND s."tenantId"=${c.tenantId} ORDER BY COALESCE(s."surgeryDate",s."createdAt") DESC`)
    return res.json(rows)
  } catch(e){ return error(res,e) }
}

export async function createSurgery(req: AuthRequest,res:Response){
  try { const c=context(req); const patientId=routeParam(req,'patientId'); await ensurePatient(patientId,req); const x=validateSurgery(req.body)
    const id=randomUUID(); const rows=await prisma.$queryRaw<any[]>(Prisma.sql`
      INSERT INTO "SurgeryCase" ("id","clinicId","tenantId","patientId","treatmentItemId","clinicalEvolutionId","surgeryType","tooth","region","diagnosis","planning","technique","anesthesia","anesthetic","medications","biomaterials","graft","membrane","suture","materialLots","complications","instructions","surgeryDate","returnAt","professionalId","professionalName","status","notes","createdById")
      VALUES (${id},${c.clinicId},${c.tenantId},${patientId},${x.treatmentItemId??null},${x.clinicalEvolutionId??null},${x.surgeryType!},${x.tooth??null},${x.region??null},${x.diagnosis!},${x.planning!},${x.technique!},${x.anesthesia??null},${x.anesthetic??null},${json(x.medications??[])},${json(x.biomaterials??[])},${x.graft??null},${x.membrane??null},${x.suture??null},${json(x.materialLots??[])},${x.complications??null},${x.instructions??null},${nullableDate(x.surgeryDate)},${nullableDate(x.returnAt)},${x.professionalId??null},${x.professionalName??null},${x.status??'PLANNED'},${x.notes??null},${c.actorId}) RETURNING *`)
    await writeAudit({ ...c, module:'CLINICAL_SPECIALTY',action:'SURGERY_CREATE',entityType:'SurgeryCase',entityId:id,summary:`Cirurgia registrada para paciente ${patientId}`,afterData:rows[0] })
    return res.status(201).json(rows[0])
  } catch(e){ return error(res,e) }
}

export async function updateSurgery(req:AuthRequest,res:Response){
  try { const c=context(req); await ensureOwned('SurgeryCase',routeParam(req,'id'),req); const x=validateSurgery(req.body,true); const old=(await prisma.$queryRaw<any[]>(Prisma.sql`SELECT * FROM "SurgeryCase" WHERE "id"=${routeParam(req,'id')} AND "clinicId"=${c.clinicId} AND "tenantId"=${c.tenantId}`))[0]
    const n={...old,...x,updatedAt:new Date()}; const rows=await prisma.$queryRaw<any[]>(Prisma.sql`UPDATE "SurgeryCase" SET "treatmentItemId"=${n.treatmentItemId??null},"clinicalEvolutionId"=${n.clinicalEvolutionId??null},"surgeryType"=${n.surgeryType},"tooth"=${n.tooth??null},"region"=${n.region??null},"diagnosis"=${n.diagnosis},"planning"=${n.planning},"technique"=${n.technique},"anesthesia"=${n.anesthesia??null},"anesthetic"=${n.anesthetic??null},"medications"=${json(n.medications)},"biomaterials"=${json(n.biomaterials)},"graft"=${n.graft??null},"membrane"=${n.membrane??null},"suture"=${n.suture??null},"materialLots"=${json(n.materialLots)},"complications"=${n.complications??null},"instructions"=${n.instructions??null},"surgeryDate"=${nullableDate(n.surgeryDate)},"returnAt"=${nullableDate(n.returnAt)},"professionalId"=${n.professionalId??null},"professionalName"=${n.professionalName??null},"status"=${n.status},"notes"=${n.notes??null},"updatedAt"=CURRENT_TIMESTAMP WHERE "id"=${routeParam(req,'id')} AND "clinicId"=${c.clinicId} AND "tenantId"=${c.tenantId} RETURNING *`)
    await writeAudit({...c,module:'CLINICAL_SPECIALTY',action:'SURGERY_UPDATE',entityType:'SurgeryCase',entityId:routeParam(req,'id'),beforeData:old,afterData:rows[0]}); return res.json(rows[0])
  } catch(e){return error(res,e)}
}

export async function addSurgeryFollowUp(req:AuthRequest,res:Response){
  try { const c=context(req); await ensureOwned('SurgeryCase',routeParam(req,'id'),req); const surgery=(await prisma.$queryRaw<any[]>(Prisma.sql`SELECT "patientId" FROM "SurgeryCase" WHERE "id"=${routeParam(req,'id')}`))[0]; const id=randomUUID(); const b=req.body||{}; const when=nullableDate(b.followUpAt)||new Date()
    const rows=await prisma.$queryRaw<any[]>(Prisma.sql`INSERT INTO "SurgeryFollowUp" ("id","clinicId","tenantId","patientId","surgeryCaseId","followUpAt","professionalId","professionalName","symptoms","healing","complications","instructions","nextReturnAt","notes","createdById") VALUES (${id},${c.clinicId},${c.tenantId},${surgery.patientId},${routeParam(req,'id')},${when},${b.professionalId??null},${b.professionalName??null},${b.symptoms??null},${b.healing??null},${b.complications??null},${b.instructions??null},${nullableDate(b.nextReturnAt)},${b.notes??null},${c.actorId}) RETURNING *`)
    await writeAudit({...c,module:'CLINICAL_SPECIALTY',action:'SURGERY_FOLLOW_UP_CREATE',entityType:'SurgeryFollowUp',entityId:id,afterData:rows[0]}); return res.status(201).json(rows[0])
  }catch(e){return error(res,e)}
}

export async function listImplants(req:AuthRequest,res:Response){try{const c=context(req);await ensurePatient(routeParam(req,'patientId'),req);const rows=await prisma.$queryRaw(Prisma.sql`SELECT i.*, CASE WHEN l."id" IS NULL THEN NULL ELSE jsonb_build_object('id',l."id",'trackingCode',l."trackingCode",'workType',l."workType",'status',l."status") END AS "laboratoryWork" FROM "ImplantRecord" i LEFT JOIN "LaboratoryWork" l ON l."id"=i."laboratoryWorkId" AND l."clinicId"=i."clinicId" AND l."tenantId"=i."tenantId" WHERE i."patientId"=${routeParam(req,'patientId')} AND i."clinicId"=${c.clinicId} AND i."tenantId"=${c.tenantId} ORDER BY COALESCE(i."installationDate",i."createdAt") DESC`);return res.json(rows)}catch(e){return error(res,e)}}

export async function createImplant(req:AuthRequest,res:Response){try{const c=context(req);const patientId=routeParam(req,'patientId');await ensurePatient(patientId,req);const x=validateImplant(req.body);await ensureLabLink(x.laboratoryWorkId,req);await ensureOwned('SurgeryCase',x.surgeryCaseId,req);const id=randomUUID();const rows=await prisma.$queryRaw<any[]>(Prisma.sql`INSERT INTO "ImplantRecord" ("id","clinicId","tenantId","patientId","surgeryCaseId","treatmentItemId","region","tooth","brand","productLine","connection","platform","diameterMm","lengthMm","lot","serialNumber","installationDate","insertionTorqueNcm","primaryStability","isq","graft","prostheticComponent","healingAbutment","miniPillar","transmucosalHeightMm","componentTorqueNcm","prostheticDate","professionalId","professionalName","laboratoryWorkId","radiographRefs","notes","complications","traceabilityCode","barcodeValue","qrValue","traceabilityPayload","scanSource","createdById") VALUES (${id},${c.clinicId},${c.tenantId},${patientId},${x.surgeryCaseId??null},${x.treatmentItemId??null},${x.region??null},${x.tooth??null},${x.brand!},${x.productLine??null},${x.connection!},${x.platform??null},${x.diameterMm!},${x.lengthMm!},${x.lot!},${x.serialNumber??null},${nullableDate(x.installationDate)},${x.insertionTorqueNcm??null},${x.primaryStability??null},${x.isq??null},${x.graft??null},${x.prostheticComponent??null},${x.healingAbutment??null},${x.miniPillar??null},${x.transmucosalHeightMm??null},${x.componentTorqueNcm??null},${nullableDate(x.prostheticDate)},${x.professionalId??null},${x.professionalName??null},${x.laboratoryWorkId??null},${json(x.radiographRefs??[])},${x.notes??null},${x.complications??null},${x.traceabilityCode??null},${x.barcodeValue??null},${x.qrValue??null},${json(x.traceabilityPayload??{})},${x.scanSource??null},${c.actorId}) RETURNING *`);await writeAudit({...c,module:'CLINICAL_SPECIALTY',action:'IMPLANT_CREATE',entityType:'ImplantRecord',entityId:id,summary:`Implante ${x.brand} lote ${x.lot}`,afterData:rows[0]});return res.status(201).json(rows[0])}catch(e){return error(res,e)}}

export async function updateImplant(req:AuthRequest,res:Response){try{const c=context(req);await ensureOwned('ImplantRecord',routeParam(req,'id'),req);const x=validateImplant(req.body,true);await ensureLabLink(x.laboratoryWorkId,req);await ensureOwned('SurgeryCase',x.surgeryCaseId,req);const old=(await prisma.$queryRaw<any[]>(Prisma.sql`SELECT * FROM "ImplantRecord" WHERE "id"=${routeParam(req,'id')} AND "clinicId"=${c.clinicId} AND "tenantId"=${c.tenantId}`))[0];const n={...old,...x};const rows=await prisma.$queryRaw<any[]>(Prisma.sql`UPDATE "ImplantRecord" SET "surgeryCaseId"=${n.surgeryCaseId??null},"treatmentItemId"=${n.treatmentItemId??null},"region"=${n.region??null},"tooth"=${n.tooth??null},"brand"=${n.brand},"productLine"=${n.productLine??null},"connection"=${n.connection},"platform"=${n.platform??null},"diameterMm"=${n.diameterMm},"lengthMm"=${n.lengthMm},"lot"=${n.lot},"serialNumber"=${n.serialNumber??null},"installationDate"=${nullableDate(n.installationDate)},"insertionTorqueNcm"=${n.insertionTorqueNcm??null},"primaryStability"=${n.primaryStability??null},"isq"=${n.isq??null},"graft"=${n.graft??null},"prostheticComponent"=${n.prostheticComponent??null},"healingAbutment"=${n.healingAbutment??null},"miniPillar"=${n.miniPillar??null},"transmucosalHeightMm"=${n.transmucosalHeightMm??null},"componentTorqueNcm"=${n.componentTorqueNcm??null},"prostheticDate"=${nullableDate(n.prostheticDate)},"professionalId"=${n.professionalId??null},"professionalName"=${n.professionalName??null},"laboratoryWorkId"=${n.laboratoryWorkId??null},"radiographRefs"=${json(n.radiographRefs)},"notes"=${n.notes??null},"complications"=${n.complications??null},"traceabilityCode"=${n.traceabilityCode??null},"barcodeValue"=${n.barcodeValue??null},"qrValue"=${n.qrValue??null},"traceabilityPayload"=${json(n.traceabilityPayload)},"scanSource"=${n.scanSource??null},"updatedAt"=CURRENT_TIMESTAMP WHERE "id"=${routeParam(req,'id')} AND "clinicId"=${c.clinicId} AND "tenantId"=${c.tenantId} RETURNING *`);await writeAudit({...c,module:'CLINICAL_SPECIALTY',action:'IMPLANT_UPDATE',entityType:'ImplantRecord',entityId:routeParam(req,'id'),beforeData:old,afterData:rows[0]});return res.json(rows[0])}catch(e){return error(res,e)}}

export async function findImplantByTrace(req:AuthRequest,res:Response){try{const c=context(req);const code=routeParam(req,'code').trim();const rows=await prisma.$queryRaw<any[]>(Prisma.sql`SELECT * FROM "ImplantRecord" WHERE "clinicId"=${c.clinicId} AND "tenantId"=${c.tenantId} AND ("traceabilityCode"=${code} OR "barcodeValue"=${code} OR "qrValue"=${code} OR "serialNumber"=${code}) ORDER BY "createdAt" DESC LIMIT 20`);return res.json(rows)}catch(e){return error(res,e)}}

export async function listProstheses(req:AuthRequest,res:Response){try{const c=context(req);await ensurePatient(routeParam(req,'patientId'),req);const rows=await prisma.$queryRaw(Prisma.sql`SELECT p.*, CASE WHEN l."id" IS NULL THEN NULL ELSE jsonb_build_object('id',l."id",'trackingCode',l."trackingCode",'workType',l."workType",'status',l."status") END AS "laboratoryWork", COALESCE((SELECT jsonb_agg(h ORDER BY h."occurredAt" DESC) FROM "ProsthesisHistory" h WHERE h."prosthesisCaseId"=p."id"),'[]'::jsonb) AS "history" FROM "ProsthesisCase" p LEFT JOIN "LaboratoryWork" l ON l."id"=p."laboratoryWorkId" AND l."clinicId"=p."clinicId" AND l."tenantId"=p."tenantId" WHERE p."patientId"=${routeParam(req,'patientId')} AND p."clinicId"=${c.clinicId} AND p."tenantId"=${c.tenantId} ORDER BY COALESCE(p."deliveryDate",p."createdAt") DESC`);return res.json(rows)}catch(e){return error(res,e)}}

export async function createProsthesis(req:AuthRequest,res:Response){try{const c=context(req);const patientId=routeParam(req,'patientId');await ensurePatient(patientId,req);const x=validateProsthesis(req.body);await ensureLabLink(x.laboratoryWorkId,req);await ensureOwned('ImplantRecord',x.implantRecordId,req);const id=randomUUID();const rows=await prisma.$queryRaw<any[]>(Prisma.sql`INSERT INTO "ProsthesisCase" ("id","clinicId","tenantId","patientId","treatmentItemId","implantRecordId","laboratoryWorkId","prosthesisType","teeth","region","material","shade","shadeGuide","conventionalImpression","impressionNotes","intraoralScan","scanSystem","stlFileRefs","provisional","tryIn","framework","ceramic","adjustment","deliveryDate","cementation","screw","torqueNcm","warrantyUntil","warrantyTerms","maintenancePlan","status","notes","createdById") VALUES (${id},${c.clinicId},${c.tenantId},${patientId},${x.treatmentItemId??null},${x.implantRecordId??null},${x.laboratoryWorkId??null},${x.prosthesisType!},${json(x.teeth??[])},${x.region??null},${x.material!},${x.shade??null},${x.shadeGuide??null},${x.conventionalImpression??false},${x.impressionNotes??null},${x.intraoralScan??false},${x.scanSystem??null},${json(x.stlFileRefs??[])},${x.provisional??null},${x.tryIn??null},${x.framework??null},${x.ceramic??null},${x.adjustment??null},${nullableDate(x.deliveryDate)},${x.cementation??null},${x.screw??null},${x.torqueNcm??null},${nullableDate(x.warrantyUntil)},${x.warrantyTerms??null},${x.maintenancePlan??null},${x.status??'PLANNED'},${x.notes??null},${c.actorId}) RETURNING *`);await writeAudit({...c,module:'CLINICAL_SPECIALTY',action:'PROSTHESIS_CREATE',entityType:'ProsthesisCase',entityId:id,afterData:rows[0]});return res.status(201).json(rows[0])}catch(e){return error(res,e)}}

export async function updateProsthesis(req:AuthRequest,res:Response){try{const c=context(req);await ensureOwned('ProsthesisCase',routeParam(req,'id'),req);const x=validateProsthesis(req.body,true);await ensureLabLink(x.laboratoryWorkId,req);await ensureOwned('ImplantRecord',x.implantRecordId,req);const old=(await prisma.$queryRaw<any[]>(Prisma.sql`SELECT * FROM "ProsthesisCase" WHERE "id"=${routeParam(req,'id')} AND "clinicId"=${c.clinicId} AND "tenantId"=${c.tenantId}`))[0];const n={...old,...x};const rows=await prisma.$queryRaw<any[]>(Prisma.sql`UPDATE "ProsthesisCase" SET "treatmentItemId"=${n.treatmentItemId??null},"implantRecordId"=${n.implantRecordId??null},"laboratoryWorkId"=${n.laboratoryWorkId??null},"prosthesisType"=${n.prosthesisType},"teeth"=${json(n.teeth)},"region"=${n.region??null},"material"=${n.material},"shade"=${n.shade??null},"shadeGuide"=${n.shadeGuide??null},"conventionalImpression"=${Boolean(n.conventionalImpression)},"impressionNotes"=${n.impressionNotes??null},"intraoralScan"=${Boolean(n.intraoralScan)},"scanSystem"=${n.scanSystem??null},"stlFileRefs"=${json(n.stlFileRefs)},"provisional"=${n.provisional??null},"tryIn"=${n.tryIn??null},"framework"=${n.framework??null},"ceramic"=${n.ceramic??null},"adjustment"=${n.adjustment??null},"deliveryDate"=${nullableDate(n.deliveryDate)},"cementation"=${n.cementation??null},"screw"=${n.screw??null},"torqueNcm"=${n.torqueNcm??null},"warrantyUntil"=${nullableDate(n.warrantyUntil)},"warrantyTerms"=${n.warrantyTerms??null},"maintenancePlan"=${n.maintenancePlan??null},"status"=${n.status},"notes"=${n.notes??null},"updatedAt"=CURRENT_TIMESTAMP WHERE "id"=${routeParam(req,'id')} AND "clinicId"=${c.clinicId} AND "tenantId"=${c.tenantId} RETURNING *`);await writeAudit({...c,module:'CLINICAL_SPECIALTY',action:'PROSTHESIS_UPDATE',entityType:'ProsthesisCase',entityId:routeParam(req,'id'),beforeData:old,afterData:rows[0]});return res.json(rows[0])}catch(e){return error(res,e)}}

export async function addProsthesisHistory(req:AuthRequest,res:Response){try{const c=context(req);await ensureOwned('ProsthesisCase',routeParam(req,'id'),req);const p=(await prisma.$queryRaw<any[]>(Prisma.sql`SELECT "patientId" FROM "ProsthesisCase" WHERE "id"=${routeParam(req,'id')}`))[0];const b=req.body||{};if(!String(b.stage||'').trim())throw new ValidationError('Etapa é obrigatória');const id=randomUUID();const rows=await prisma.$queryRaw<any[]>(Prisma.sql`INSERT INTO "ProsthesisHistory" ("id","clinicId","tenantId","patientId","prosthesisCaseId","stage","status","occurredAt","professionalId","professionalName","notes","createdById") VALUES (${id},${c.clinicId},${c.tenantId},${p.patientId},${routeParam(req,'id')},${String(b.stage).trim()},${b.status??null},${nullableDate(b.occurredAt)||new Date()},${b.professionalId??null},${b.professionalName??null},${b.notes??null},${c.actorId}) RETURNING *`);await writeAudit({...c,module:'CLINICAL_SPECIALTY',action:'PROSTHESIS_HISTORY_CREATE',entityType:'ProsthesisHistory',entityId:id,afterData:rows[0]});return res.status(201).json(rows[0])}catch(e){return error(res,e)}}
