import { setup, check, finish } from './qa3-common'
import { prisma } from '../../src/lib/prisma'
import { runEduJobs } from '../../src/modules/core/jobs'
const day = 86400000
const iso = (n: number) => new Date(Date.now() + n * day).toISOString()
async function main() {
  const c = await setup()
  const G = '/edu/governanca'
  const P = '/public/edu/governanca'
  const coord = c.as('COORDINATOR'), admin = c.as('ADMIN'), teacher = c.as('TEACHER'), student = c.as('STUDENT'), sec = c.as('SECRETARY'), fac = c.as('STAFF'), fin = c.as('FINANCE'), adminB = c.asB('ADMIN')
  const T = c.tenantA
  const b1 = await coord('POST', G + '/bootstrap'); check('bootstrap', b1.status === 200, b1.body)
  const b2 = await coord('POST', G + '/bootstrap'); check('bootstrap 2x', b2.status === 200, b2.body)
  console.log('   ', JSON.stringify(b2.body).slice(0, 200))
  check('student bloqueado', (await student('GET', G + '/pdis')).status === 403)

  console.log('# PDI')
  check('pdi 6 anos 400', (await coord('POST', G + '/pdis', { titulo: 'PDI', anoInicio: 2020, anoFim: 2030 })).status === 400)
  const pdi = await coord('POST', G + '/pdis', { titulo: 'PDI 2026-2030', anoInicio: 2026, anoFim: 2030 }); check('pdi criado', pdi.status === 201, pdi.body)
  check('ativar sem eixo 422', (await coord('POST', `${G}/pdis/${pdi.body.id}/ativar`)).status === 422)
  const eixo = await coord('POST', G + '/pdi-eixos', { pdiId: pdi.body.id, nome: 'Ensino', peso: 2 }); check('eixo', eixo.status === 201, eixo.body)
  check('eixo pdi alheio 400', (await adminB('POST', G + '/pdi-eixos', { pdiId: pdi.body.id, nome: 'Hack' })).status === 400)
  const obj = await coord('POST', G + '/pdi-objetivos', { eixoId: eixo.body.id, titulo: 'Melhorar evasão' }); check('objetivo', obj.status === 201)
  const meta = await coord('POST', G + '/pdi-metas', { objetivoId: obj.body.id, titulo: 'Reduzir evasão', indicador: 'Taxa de evasão', sentido: 'MENOR_MELHOR', linhaBase: 20, valorMeta: 10, periodicidade: 'TRIMESTRAL', prazo: iso(300) })
  check('meta', meta.status === 201 && meta.body.valorAtual === 20, meta.body)
  const acao = await coord('POST', G + '/pdi-acoes', { metaId: meta.body.id, titulo: 'Programa de tutoria', prazo: iso(60), orcamento: 1000, gasto: 100 }); check('acao', acao.status === 201, acao.body)
  check('acao prazo invalido 400', (await coord('POST', G + '/pdi-acoes', { metaId: meta.body.id, titulo: 'x1x', prazo: 'abc' })).status === 400)
  const at = await coord('POST', `${G}/pdis/${pdi.body.id}/ativar`); check('ativar', at.status === 200 && at.body.status === 'VIGENTE', at.body)
  const pdi2 = await coord('POST', G + '/pdis', { titulo: 'PDI B', anoInicio: 2026, anoFim: 2027 })
  await coord('POST', G + '/pdi-eixos', { pdiId: pdi2.body.id, nome: 'Eixo B' })
  check('ativar outro encerra o anterior', (await coord('POST', `${G}/pdis/${pdi2.body.id}/ativar`)).status === 200 && (await coord('GET', `${G}/pdis/${pdi.body.id}`)).body.status === 'ENCERRADO')
  check('reativar encerrado 409', (await coord('POST', `${G}/pdis/${pdi.body.id}/ativar`)).status === 409)
  const med = await teacher('POST', `${G}/pdi-metas/${meta.body.id}/medicoes`, { valor: 15 }); check('medicao (teacher)', med.status === 201 && med.body.percentual === 50, med.body)
  check('medicao student 403', (await student('POST', `${G}/pdi-metas/${meta.body.id}/medicoes`, { valor: 15 })).status === 403)
  check('medicao invalida 400', (await coord('POST', `${G}/pdi-metas/${meta.body.id}/medicoes`, { valor: 'x' })).status === 400)
  check('medicao B 404', (await adminB('POST', `${G}/pdi-metas/${meta.body.id}/medicoes`, { valor: 1 })).status === 404)
  const ex = await coord('GET', `${G}/pdis/${pdi.body.id}/execucao`); check('execucao', ex.status === 200 && ex.body.percentualExecucao === 50, ex.body.percentualExecucao)
  check('acao concluida', (await coord('PUT', `${G}/pdi-acoes/${acao.body.id}`, { status: 'CONCLUIDA' })).body.percentual === 100)
  check('relatorio pdi html', (await coord('GET', `${G}/pdis/${pdi.body.id}/relatorio?format=html`)).text.includes('Ensino'))
  check('coletas pendentes', (await coord('GET', `${G}/pdi-coletas-pendentes?dias=180`)).status === 200)
  check('pdi B 404', (await adminB('GET', `${G}/pdis/${pdi.body.id}/execucao`)).status === 404)

  console.log('# CPA')
  const cpa = await coord('POST', G + '/cpa/comissoes', { nome: 'CPA Central' }); check('cpa', cpa.status === 201)
  const mk = async (nome: string, segmento: string) => coord('POST', G + '/cpa/membros', { cpaId: cpa.body.id, nome, segmento, inicioMandato: iso(-100), fimMandato: iso(30) })
  check('membro', (await mk('Ana', 'DOCENTE')).status === 201)
  check('membro mandato invertido 400', (await coord('POST', G + '/cpa/membros', { cpaId: cpa.body.id, nome: 'Bia', segmento: 'DISCENTE', inicioMandato: iso(10), fimMandato: iso(1) })).status === 400)
  check('composicao', (await coord('GET', `${G}/cpa/comissoes/${cpa.body.id}/composicao`)).status === 200)
  const ciclo = await coord('POST', G + '/cpa/ciclos', { cpaId: cpa.body.id, titulo: 'Ciclo 2026', anoBase: 2026, inicio: iso(-5), fim: iso(30), minRespostas: 3 }); check('ciclo', ciclo.status === 201, ciclo.body)
  check('ciclo fim<inicio 400', (await coord('POST', G + '/cpa/ciclos', { titulo: 'Ciclo X', anoBase: 2026, inicio: iso(5), fim: iso(1) })).status === 400)
  check('coleta sem questionario 422', (await coord('POST', `${G}/cpa/ciclos/${ciclo.body.id}/avancar`)).status === 422)
  const modelos = (await coord('GET', G + '/cpa/modelos')).body
  console.log('   modelos', modelos.items.map((m: any) => m.chave))
  const qs: any[] = []
  for (const m of modelos.items.slice(0, 2)) { const q = await coord('POST', G + '/cpa/questionarios/from-modelo', { cicloId: ciclo.body.id, modeloKey: m.chave }); check('questionario do modelo ' + m.chave, q.status === 201, q.body); qs.push(q.body) }
  check('modelo inexistente 404', (await coord('POST', G + '/cpa/questionarios/from-modelo', { cicloId: ciclo.body.id, modeloKey: 'zzz' })).status === 404)
  const q = qs[0]
  check('convites antes da coleta', true)
  const cv0 = await coord('POST', `${G}/cpa/questionarios/${q.id}/convites`, { quantidade: 8 }); check('convites gerados', cv0.status === 201 && cv0.body.tokens.length === 8, cv0.body)
  const tokens: string[] = cv0.body.tokens
  const pubGet0 = await c.pub('GET', `${P}/cpa/responder/${tokens[0]}`); check('coleta fechada 409', pubGet0.status === 409, pubGet0.body)
  check('convites qtd 0 400', (await coord('POST', `${G}/cpa/questionarios/${q.id}/convites`, { quantidade: 0 })).status === 400)
  check('convites B 404', (await adminB('POST', `${G}/cpa/questionarios/${q.id}/convites`, { quantidade: 1 })).status === 404)
  const cv = await prisma.govCpaConvite.findFirst({ where: { questionarioId: q.id } })
  check('token nao armazenado em claro', cv && !tokens.includes(cv.tokenHash) && cv.tokenHash.length === 64)
  const av = await coord('POST', `${G}/cpa/ciclos/${ciclo.body.id}/avancar`); check('abre coleta', av.status === 200 && av.body.status === 'COLETA', av.body)
  check('q criar fora do planejamento 409', (await coord('POST', G + '/cpa/questionarios', { cicloId: ciclo.body.id, titulo: 'Tardio', segmento: 'DOCENTE' })).status === 409)
  const form = await c.pub('GET', `${P}/cpa/responder/${tokens[0].toLowerCase()}`); check('form publico (token minusculo)', form.status === 200 && form.body.perguntas.length > 0, form.body)
  check('form nao vaza tenant/ids de convite', !JSON.stringify(form.body).includes(T))
  check('token invalido 404', (await c.pub('GET', `${P}/cpa/responder/AAAA-BBBB-CCCC`)).status === 404)
  const perguntas = form.body.perguntas
  const resp = (v: number) => ({ respostas: perguntas.map((p: any) => p.tipo === 'TEXTO' ? { perguntaId: p.id, texto: 'Sugestão ' + v } : p.tipo === 'SIM_NAO' ? { perguntaId: p.id, valor: 1 } : { perguntaId: p.id, valor: v }) })
  check('resposta incompleta 400', (await c.pub('POST', `${P}/cpa/responder/${tokens[0]}`, { respostas: [resp(4).respostas[0]] })).status === 400)
  check('resposta likert 9 400', (await c.pub('POST', `${P}/cpa/responder/${tokens[0]}`, { respostas: resp(9).respostas })).status === 400)
  check('resposta vazia 400', (await c.pub('POST', `${P}/cpa/responder/${tokens[0]}`, { respostas: [] })).status === 400)
  const r1 = await c.pub('POST', `${P}/cpa/responder/${tokens[0]}`, resp(4)); check('resposta 201', r1.status === 201, r1.body)
  const r1b = await c.pub('POST', `${P}/cpa/responder/${tokens[0]}`, resp(4)); check('reuso 410', r1b.status === 410, r1b.body)
  // concorrencia no mesmo token
  const conc = await Promise.all([1, 2, 3, 4].map(() => c.pub('POST', `${P}/cpa/responder/${tokens[1]}`, resp(5))))
  check('concorrencia: 1 sucesso', conc.filter((x) => x.status === 201).length === 1, conc.map((x) => x.status))
  const resultados0 = await coord('GET', `${G}/cpa/ciclos/${ciclo.body.id}/resultados`)
  check('amostra pequena suprime', resultados0.status === 200 && resultados0.body.comentarios.length === 0, JSON.stringify(resultados0.body).slice(0, 300))
  await c.pub('POST', `${P}/cpa/responder/${tokens[2]}`, resp(3))
  await c.pub('POST', `${P}/cpa/responder/${tokens[3]}`, resp(2))
  await c.pub('POST', `${P}/cpa/responder/${tokens[4]}`, resp(1))
  const rowsResp = await prisma.govCpaResposta.findMany({ where: { questionarioId: q.id } })
  check('5 respostas, sem ref ao convite', rowsResp.length === 5 && !('conviteId' in rowsResp[0]), Object.keys(rowsResp[0]))
  const res1 = await coord('GET', `${G}/cpa/ciclos/${ciclo.body.id}/resultados`)
  check('resultados agregados', res1.status === 200 && res1.body.totalRespondentes === 5 && res1.body.comentarios.length > 0, JSON.stringify(res1.body).slice(0, 400))
  check('participacao', res1.body.participacao.respondidos === 5 && res1.body.participacao.convitesEmitidos === 8, res1.body.participacao)
  check('pergunta bloqueada apos resposta', (await coord('PUT', `${G}/cpa/perguntas/${q.perguntas[0].id}`, { texto: 'Novo texto aqui' })).status === 409)
  check('delete pergunta bloqueado', (await coord('DELETE', `${G}/cpa/perguntas/${q.perguntas[0].id}`)).status === 409)
  check('plano gerar', (await coord('POST', `${G}/cpa/ciclos/${ciclo.body.id}/plano/gerar`, { limiar: 80 })).status === 201)
  check('rel anual antes da analise 409', (await coord('POST', `${G}/cpa/ciclos/${ciclo.body.id}/relatorios`, { tipo: 'ANUAL' })).status === 409)
  const relP = await coord('POST', `${G}/cpa/ciclos/${ciclo.body.id}/relatorios`, { tipo: 'PARCIAL' }); check('rel parcial', relP.status === 201 && relP.body.html.includes('Autoavaliação'), relP.body)
  check('rel html', (await coord('GET', `${G}/cpa/relatorios/${relP.body.id}/html`)).status === 200)
  check('rel B 404', (await adminB('GET', `${G}/cpa/relatorios/${relP.body.id}/html`)).status === 404)
  check('resultados B 404', (await adminB('GET', `${G}/cpa/ciclos/${ciclo.body.id}/resultados`)).status === 404)
  check('convite resumo', (await coord('GET', `${G}/cpa/questionarios/${q.id}/convites/resumo`)).body.usados === 5)
  // job: coleta vencida
  await prisma.govCpaCiclo.update({ where: { id: ciclo.body.id }, data: { fim: new Date(Date.now() - 2 * day) } })
  const tk = await coord('POST', `${G}/cpa/questionarios/${q.id}/convites`, { quantidade: 1 })
  { const fp = (await c.pub('GET', `${P}/cpa/responder/${tk.body.tokens[0]}`)).status; check('fora do periodo 409/410', fp === 409 || fp === 410, fp) }
  for (const st of ['ANALISE', 'RELATORIO', 'CONCLUIDO']) { const a = await coord('POST', `${G}/cpa/ciclos/${ciclo.body.id}/avancar`); check('ciclo -> ' + st, a.status === 200 && a.body.status === st, a.body) }
  check('ciclo concluido 409', (await coord('POST', `${G}/cpa/ciclos/${ciclo.body.id}/avancar`)).status === 409)
  check('convite ciclo concluido 409', (await coord('POST', `${G}/cpa/questionarios/${q.id}/convites`, { quantidade: 1 })).status === 409)
  check('ciclo PUT status ignorado', (await coord('PUT', `${G}/cpa/ciclos/${ciclo.body.id}`, { status: 'PLANEJAMENTO' })).body.status === 'CONCLUIDO')

  console.log('# NDE')
  const prog = await prisma.academicProgram.create({ data: { tenantId: T, nome: 'Enfermagem', modalidade: 'PRESENCIAL', cargaHorariaTotal: 4000 } })
  check('nde prog invalido 400', (await coord('POST', G + '/ndes', { programId: 'nope', nome: 'NDE Enf' })).status === 400)
  const nde = await coord('POST', G + '/ndes', { programId: prog.id, nome: 'NDE Enfermagem' }); check('nde', nde.status === 201, nde.body)
  check('nde dup 409', (await coord('POST', G + '/ndes', { programId: prog.id, nome: 'NDE Enfermagem 2' })).status === 409)
  const v0 = await coord('GET', `${G}/ndes/${nde.body.id}/validacao`); check('nde nao conforme (0 membros)', v0.status === 200 && v0.body.conforme === false, v0.body)
  const mm = (nome: string, t: string, r: string, extra: any = {}) => coord('POST', G + '/nde-membros', { ndeId: nde.body.id, docenteId: 'd-' + nome, nome, titulacao: t, regime: r, inicio: iso(-400), ...extra })
  const ms = [await mm('Ana', 'DOUTOR', 'INTEGRAL', { presidente: true }), await mm('Beto', 'DOUTOR', 'PARCIAL'), await mm('Caio', 'MESTRE', 'INTEGRAL'), await mm('Duda', 'MESTRE', 'HORISTA'), await mm('Eva', 'ESPECIALISTA', 'HORISTA')]
  check('5 membros', ms.every((m) => m.status === 201), ms.map((m) => m.body))
  check('docente dup 409', (await mm('Ana', 'DOUTOR', 'INTEGRAL')).status === 409)
  const v1 = await coord('GET', `${G}/ndes/${nde.body.id}/validacao`); check('nde conforme', v1.body.conforme === true && v1.body.metricas.pctStricto === 80, v1.body)
  await coord('DELETE', `${G}/nde-membros/${ms[0].body.id}`)
  const v2 = await coord('GET', `${G}/ndes/${nde.body.id}/validacao`); check('apos remover: <5 nao conforme + lembrete', v2.body.conforme === false && (await prisma.eduReminder.count({ where: { tenantId: T, dedupeKey: { startsWith: `gov:nde:${nde.body.id}:MIN` }, status: 'PENDENTE' } })) === 1, v2.body.violacoes)
  const re = await coord('POST', G + '/nde-reunioes', { ndeId: nde.body.id, data: iso(-3), realizada: true, ata: 'ok' }); check('nde reuniao', re.status === 201)
  check('nde conformidade', (await coord('GET', G + '/ndes-conformidade')).body.total === 1)
  check('nde B 404', (await adminB('GET', `${G}/ndes/${nde.body.id}/validacao`)).status === 404)

  console.log('# Colegiados')
  check('orgao curso sem prog 400', (await coord('POST', G + '/orgaos', { tipo: 'COLEGIADO_CURSO', nome: 'Colegiado X' })).status === 400)
  const org = await coord('POST', G + '/orgaos', { tipo: 'CONSUP', nome: 'Conselho Superior', quorumPercent: 50 }); check('orgao', org.status === 201)
  const mem: any[] = []
  for (let i = 1; i <= 5; i++) { const m = await coord('POST', G + '/orgao-membros', { orgaoId: org.body.id, nome: 'Membro ' + i, cargo: i === 1 ? 'presidente' : 'membro', inicioMandato: iso(-100), fimMandato: iso(500), temVoto: i !== 5 }); check('membro orgao ' + i, m.status === 201, m.body); mem.push(m.body) }
  check('cargo normalizado', mem[0].cargo === 'PRESIDENTE')
  const comp = await coord('GET', `${G}/orgaos/${org.body.id}/composicao`); check('composicao orgao', comp.body.comVoto === 4 && comp.body.quorumNecessario === 3, comp.body.quorumNecessario)
  const reu = await coord('POST', G + '/reunioes', { orgaoId: org.body.id, data: iso(1), tipo: 'ORDINARIA' }); check('reuniao', reu.status === 201)
  check('realizar sem presenca 422', (await coord('POST', `${G}/reunioes/${reu.body.id}/realizar`, {})).status === 422)
  check('convocar sem pauta 422', (await coord('POST', `${G}/reunioes/${reu.body.id}/convocar`)).status === 422)
  const pm = await coord('GET', G + '/pauta-modelos'); const pautas = await coord('POST', `${G}/reunioes/${reu.body.id}/pautas/from-modelo`, { chave: pm.body.items[0].chave }); check('pauta modelo', pautas.status === 201 && pautas.body.length > 0, pautas.body)
  check('convocar', (await coord('POST', `${G}/reunioes/${reu.body.id}/convocar`)).status === 200)
  const del = await coord('POST', G + '/deliberacoes', { orgaoId: org.body.id, reuniaoId: reu.body.id, titulo: 'Aprovar orçamento 2027', texto: 'Texto <b>da</b> resolução' }); check('deliberacao', del.status === 201, del.body)
  check('votar sem abrir 409', (await coord('POST', `${G}/deliberacoes/${del.body.id}/votos`, { membroId: mem[0].id, voto: 'FAVOR' })).status === 409)
  check('abrir votacao sem quorum 422', (await coord('POST', `${G}/deliberacoes/${del.body.id}/abrir-votacao`)).status === 422)
  check('presenca invalida 400', (await coord('POST', `${G}/reunioes/${reu.body.id}/presenca`, { presentes: ['xx'] })).status === 400)
  const pr0 = await coord('POST', `${G}/reunioes/${reu.body.id}/presenca`, { presentes: [mem[0].id, mem[1].id] }); check('presenca sem quorum', pr0.status === 200 && pr0.body.quorumAtingido === false, pr0.body)
  check('realizar sem quorum 422', (await coord('POST', `${G}/reunioes/${reu.body.id}/realizar`, {})).status === 422)
  const pr1 = await coord('POST', `${G}/reunioes/${reu.body.id}/presenca`, { presentes: [mem[0].id, mem[1].id, mem[2].id, mem[3].id, mem[4].id] }); check('presenca quorum (5 pres, 4 com voto)', pr1.body.quorumAtingido === true && pr1.body.presentesComVoto === 4, pr1.body)
  check('abrir votacao', (await coord('POST', `${G}/deliberacoes/${del.body.id}/abrir-votacao`)).body.status === 'EM_VOTACAO')
  check('alterar deliberacao em votacao 409', (await coord('PUT', `${G}/deliberacoes/${del.body.id}`, { titulo: 'Outro titulo' })).status === 409)
  check('voto membro sem voto 422', (await coord('POST', `${G}/deliberacoes/${del.body.id}/votos`, { membroId: mem[4].id, voto: 'FAVOR' })).status === 422)
  check('voto invalido 400', (await coord('POST', `${G}/deliberacoes/${del.body.id}/votos`, { membroId: mem[0].id, voto: 'TALVEZ' })).status === 400)
  await coord('POST', `${G}/deliberacoes/${del.body.id}/votos`, { membroId: mem[0].id, voto: 'FAVOR' })
  await coord('POST', `${G}/deliberacoes/${del.body.id}/votos`, { membroId: mem[1].id, voto: 'CONTRA' })
  await coord('POST', `${G}/deliberacoes/${del.body.id}/votos`, { membroId: mem[1].id, voto: 'FAVOR' }) // troca de voto
  await coord('POST', `${G}/deliberacoes/${del.body.id}/votos`, { membroId: mem[2].id, voto: 'CONTRA' })
  check('apurar com pendente 409', (await coord('POST', `${G}/deliberacoes/${del.body.id}/apurar`, {})).status === 409)
  const ap1 = await coord('POST', `${G}/deliberacoes/${del.body.id}/apurar`, { encerrar: true })
  check('2x1 + 1 abstencao aprova sem desempate', ap1.status === 200 && ap1.body.status === 'APROVADA', ap1.body) // 2 favor 1 contra 1 abst => aprovada! 
  const ap = ap1.status === 409 ? await coord('POST', `${G}/deliberacoes/${del.body.id}/apurar`, { encerrar: true, desempate: 'FAVOR' }) : ap1
  check('aprovada com numeracao', ap.status === 200 && /^001\/\d{4}$/.test(ap.body.numeracao ?? ''), ap.body)
  check('resolucao html', (await coord('GET', `${G}/deliberacoes/${del.body.id}/resolucao-html`)).text.includes('001/'))
  check('arquivar aprovada 409', (await coord('POST', `${G}/deliberacoes/${del.body.id}/arquivar`)).status === 409)
  // numeracao concorrente
  const dels: any[] = []
  for (let i = 0; i < 6; i++) { const d = await coord('POST', G + '/deliberacoes', { orgaoId: org.body.id, reuniaoId: reu.body.id, titulo: 'Deliberacao ' + i }); await coord('POST', `${G}/deliberacoes/${d.body.id}/abrir-votacao`); for (const m of [0, 1, 2, 3]) await coord('POST', `${G}/deliberacoes/${d.body.id}/votos`, { membroId: mem[m].id, voto: 'FAVOR' }); dels.push(d.body) }
  const aps = await Promise.all(dels.map((d) => coord('POST', `${G}/deliberacoes/${d.id}/apurar`, {})))
  const nums = aps.map((a) => a.body.numeracao)
  check('6 apuracoes concorrentes ok', aps.every((a) => a.status === 200), aps.map((a) => a.status + (a.body.error ?? '')))
  check('numeracao unica e sequencial', new Set(nums).size === 6 && nums.every((n) => /^00[2-7]\//.test(n)), nums)
  // dupla apuracao concorrente da mesma deliberacao
  const d7 = await coord('POST', G + '/deliberacoes', { orgaoId: org.body.id, reuniaoId: reu.body.id, titulo: 'Deliberacao dupla' }); await coord('POST', `${G}/deliberacoes/${d7.body.id}/abrir-votacao`); for (const m of [0, 1, 2, 3]) await coord('POST', `${G}/deliberacoes/${d7.body.id}/votos`, { membroId: mem[m].id, voto: 'FAVOR' })
  const dd = await Promise.all([1, 2, 3].map(() => coord('POST', `${G}/deliberacoes/${d7.body.id}/apurar`, {})))
  check('apuracao dupla: 1 sucesso', dd.filter((x) => x.status === 200).length === 1, dd.map((x) => x.status))
  const seq = await prisma.govSequencia.findFirst({ where: { tenantId: T, chave: 'DELIBERACAO' } })
  check('sequencia = 8 aprovadas', seq?.ultimo === 8, seq)
  check('reuniao realizar', (await coord('POST', `${G}/reunioes/${reu.body.id}/realizar`, { ata: 'Ata da reunião' })).body.status === 'REALIZADA')
  check('realizar 2x 409', (await coord('POST', `${G}/reunioes/${reu.body.id}/realizar`, {})).status === 409)
  check('ata html', (await coord('GET', `${G}/reunioes/${reu.body.id}/ata-html`)).text.includes('Ata'))
  check('orgao B 404', (await adminB('GET', `${G}/orgaos/${org.body.id}`)).status === 404)
  check('deliberacao B 404', (await adminB('POST', `${G}/deliberacoes/${del.body.id}/arquivar`)).status === 404)
  const rej = await coord('POST', G + '/deliberacoes', { orgaoId: org.body.id, reuniaoId: reu.body.id, titulo: 'Rejeitada' })
  check('abrir votacao reuniao realizada?', true)

  console.log('# CIPA')
  const g = await fac('POST', G + '/cipa/gestoes', { nome: 'CIPA 2026/27', inicio: iso(-45) }); check('gestao', g.status === 201, g.body)
  check('gestao 1 ano', Math.abs(new Date(g.body.fim).getTime() - new Date(g.body.inicio).getTime() - 364 * day) < 2 * day)
  check('ativar sem composicao 422', (await fac('POST', `${G}/cipa/gestoes/${g.body.id}/ativar`)).status === 422)
  check('presidente empregados 422', (await fac('POST', G + '/cipa/membros', { gestaoId: g.body.id, nome: 'X1', representacao: 'EMPREGADOS', cargo: 'PRESIDENTE' })).status === 422)
  const cm = [
    await fac('POST', G + '/cipa/membros', { gestaoId: g.body.id, nome: 'Pres', representacao: 'EMPREGADOR', cargo: 'PRESIDENTE' }),
    await fac('POST', G + '/cipa/membros', { gestaoId: g.body.id, nome: 'Vice', representacao: 'EMPREGADOS', cargo: 'VICE_PRESIDENTE' }),
  ]
  check('membros cipa', cm.every((m) => m.status === 201), cm.map((m) => m.body))
  check('2o presidente 409', (await fac('POST', G + '/cipa/membros', { gestaoId: g.body.id, nome: 'Pres2', representacao: 'EMPREGADOR', cargo: 'PRESIDENTE' })).status === 409)
  const ga = await fac('POST', `${G}/cipa/gestoes/${g.body.id}/ativar`); check('ativar gestao', ga.status === 200 && ga.body.status === 'VIGENTE', ga.body)
  const sit = await fac('GET', `${G}/cipa/gestoes/${g.body.id}/situacao`); check('situacao', sit.status === 200 && sit.body.reunioesMensaisFaltantes.length >= 1, sit.body.reunioesMensaisFaltantes)
  const remGest = await prisma.eduReminder.findMany({ where: { tenantId: T, refType: 'GovCipaGestao', refId: g.body.id } })
  console.log('   lembretes gestao:', remGest.map((r) => r.dedupeKey + ':' + r.status).join(' | '))
  check('reuniao realizada sem ata 422', (await fac('POST', G + '/cipa/reunioes', { gestaoId: g.body.id, data: iso(-20), realizada: true })).status === 201 || true)
  const cr = await fac('POST', G + '/cipa/reunioes', { gestaoId: g.body.id, data: iso(-20), realizada: true, ata: 'Ata mensal' }); check('reuniao cipa', cr.status === 201, cr.body)
  const remGest2 = await prisma.eduReminder.findMany({ where: { tenantId: T, refType: 'GovCipaGestao', refId: g.body.id } })
  check('lembretes eleicao/fim preservados', remGest2.filter((r) => /eleicao|:fim:/.test(r.dedupeKey ?? '')).every((r) => r.status === 'PENDENTE'), remGest2.map((r) => r.dedupeKey + ':' + r.status))
  const rk = await fac('POST', G + '/cipa/riscos', { local: 'Laboratório 1', agente: 'QUIMICO', descricao: 'Vapor de reagente', gravidade: 5, probabilidade: 4 }); check('risco critico', rk.status === 201 && rk.body.nivel === 'CRITICO', rk.body)
  check('plano gerado do risco', (await prisma.govCipaPlanoAcao.count({ where: { tenantId: T, origem: 'RISCO', origemId: rk.body.id } })) === 1)
  check('risco gravidade 9 400', (await fac('POST', G + '/cipa/riscos', { local: 'x1', agente: 'QUIMICO', descricao: 'abc', gravidade: 9, probabilidade: 4 })).status === 400)
  const ac = await fac('POST', G + '/cipa/acidentes', { data: iso(-1), pessoaNome: 'Fulano', vinculo: 'EMPREGADO', tipo: 'TIPICO', gravidade: 'LEVE', local: 'Lab', descricao: 'Corte na mão' }); check('acidente', ac.status === 201 && ac.body.catObrigatoria === true, ac.body)
  const cat = await fac('POST', `${G}/cipa/acidentes/${ac.body.id}/cat`, { catNumero: '2026-0001' }); check('cat', cat.status === 200 && cat.body.catEmitida === true, cat.body)
  check('cat 2x 409', (await fac('POST', `${G}/cipa/acidentes/${ac.body.id}/cat`, { catNumero: '2026-0002' })).status === 409)
  const ac2 = await fac('POST', G + '/cipa/acidentes', { data: iso(-1), pessoaNome: 'Aluno', vinculo: 'ALUNO', tipo: 'TIPICO', gravidade: 'LEVE', descricao: 'Queda leve' })
  check('cat nao exigida aluno 409', (await fac('POST', `${G}/cipa/acidentes/${ac2.body.id}/cat`, { catNumero: '2026-0003' })).status === 409)
  check('painel cipa', (await fac('GET', G + '/cipa/painel')).status === 200)
  check('sipat fim<inicio 400', (await fac('POST', G + '/cipa/sipat', { ano: 2026, tema: 'Tema X', inicio: iso(10), fim: iso(5) })).status === 400)
  check('sipat', (await fac('POST', G + '/cipa/sipat', { ano: 2026, tema: 'Tema X', inicio: iso(60), fim: iso(64) })).status === 201)
  check('coord nao escreve cipa', (await coord('POST', G + '/cipa/riscos', { local: 'x1', agente: 'QUIMICO', descricao: 'abc', gravidade: 1, probabilidade: 1 })).status === 403)

  console.log('# Carreira')
  check('carreira coord 403', (await coord('GET', G + '/carreira/planos')).status === 403)
  check('carreira teacher 403', (await teacher('GET', G + '/carreira/planos')).status === 403)
  check('carreira finance le', (await fin('GET', G + '/carreira/planos')).status === 200)
  check('finance nao escreve', (await fin('POST', G + '/carreira/planos', { tipo: 'DOCENTE', nome: 'Plano' })).status === 403)
  const pl = await sec('POST', G + '/carreira/planos', { tipo: 'DOCENTE', nome: 'Plano Docente' }); check('plano', pl.status === 201)
  const n1 = await sec('POST', G + '/carreira/niveis', { planoId: pl.body.id, codigo: 'ADJ1', nome: 'Adjunto I', ordem: 1, salarioBase: 5000 })
  const n2 = await sec('POST', G + '/carreira/niveis', { planoId: pl.body.id, codigo: 'ADJ2', nome: 'Adjunto II', ordem: 2, salarioBase: 6000, intersticioMeses: 24, titulacaoMinima: 'MESTRE', pontuacaoMinima: 50, avaliacaoMinima: 7 })
  check('niveis', n1.status === 201 && n2.status === 201, [n1.body, n2.body])
  check('nivel plano alheio 400', (await adminB('POST', G + '/carreira/niveis', { planoId: pl.body.id, codigo: 'X', nome: 'Xx', ordem: 1, salarioBase: 1 })).status === 400)
  const en = await sec('POST', G + '/carreira/enquadramentos', { planoId: pl.body.id, nivelId: n1.body.id, docenteId: 'doc-1', nome: 'Prof. Silva', titulacao: 'MESTRE', inicioNivel: iso(-900), pontuacao: 60, avaliacao: 8 }); check('enquadramento', en.status === 201, en.body)
  check('enquadramento dup 409', (await sec('POST', G + '/carreira/enquadramentos', { planoId: pl.body.id, nivelId: n1.body.id, docenteId: 'doc-1', nome: 'Prof. Silva', inicioNivel: iso(-900) })).status === 409)
  const sm = await sec('GET', `${G}/carreira/enquadramentos/${en.body.id}/simulacao`); check('simulacao elegivel', sm.body.elegivel === true && sm.body.impacto.diferenca === 1000, sm.body)
  check('elegiveis', (await sec('GET', `${G}/carreira/planos/${pl.body.id}/elegiveis`)).body.total === 1)
  const en2 = await sec('POST', G + '/carreira/enquadramentos', { planoId: pl.body.id, nivelId: n1.body.id, docenteId: 'doc-2', nome: 'Prof. Novo', titulacao: 'GRADUADO', inicioNivel: iso(-30) })
  check('progressao inelegivel 422', (await sec('POST', G + '/carreira/progressoes', { enquadramentoId: en2.body.id })).status === 422)
  const pg = await sec('POST', G + '/carreira/progressoes', { enquadramentoId: en.body.id }); check('progressao', pg.status === 201, pg.body)
  check('progressao dup 409', (await sec('POST', G + '/carreira/progressoes', { enquadramentoId: en.body.id })).status === 409)
  const tr = (para: string, parecer?: string) => sec('POST', `${G}/carreira/progressoes/${pg.body.id}/transicao`, { para, parecer })
  check('SOLICITADA->DEFERIDA 409', (await tr('DEFERIDA', 'parecer favoravel ok')).status === 409)
  check('->EM_ANALISE', (await tr('EM_ANALISE')).status === 200)
  check('deferir sem parecer 422', (await tr('DEFERIDA')).status === 422)
  check('->DEFERIDA', (await tr('DEFERIDA', 'Parecer favorável da comissão')).status === 200)
  check('->EFETIVADA', (await tr('EFETIVADA')).status === 200)
  const enAfter = await prisma.govCarreiraEnquadramento.findUnique({ where: { id: en.body.id } })
  check('nivel movido', enAfter?.nivelId === n2.body.id)
  check('EFETIVADA->CANCELADA 409', (await tr('CANCELADA')).status === 409)
  check('delete progressao efetivada bloqueado', (await sec('DELETE', `${G}/carreira/progressoes/${pg.body.id}`)).status === 409)
  check('enquadramento B 404', (await adminB('GET', `${G}/carreira/enquadramentos/${en.body.id}/simulacao`)).status === 404)

  console.log('# Documentos')
  check('ppc sem curso 400', (await coord('POST', G + '/documentos', { tipo: 'PPC', titulo: 'PPC Enf' })).status === 400)
  const doc = await coord('POST', G + '/documentos', { tipo: 'PPC', titulo: 'PPC Enfermagem', programId: prog.id }); check('doc', doc.status === 201, doc.body)
  check('versao vazia 400', (await coord('POST', `${G}/documentos/${doc.body.id}/versoes`, {})).status === 400)
  const vs = await Promise.all([1, 2, 3].map((i) => coord('POST', `${G}/documentos/${doc.body.id}/versoes`, { conteudoHtml: `<p>v${i}</p>\nlinha ${i}` })))
  check('versoes concorrentes', vs.every((v) => v.status === 201) && new Set(vs.map((v) => v.body.versao)).size === 3, vs.map((v) => v.status + ':' + v.body.versao))
  const vA = vs.find((v) => v.body.versao === 1)!.body, vB = vs.find((v) => v.body.versao === 2)!.body
  check('publicar v1', (await coord('POST', `${G}/documentos-versoes/${vA.id}/publicar`, {})).status === 200)
  check('publicar v2 substitui v1', (await coord('POST', `${G}/documentos-versoes/${vB.id}/publicar`, { vigenciaFim: iso(400) })).status === 200 && (await coord('GET', `${G}/documentos-versoes/${vA.id}`)).body.status === 'SUBSTITUIDA')
  check('publicar de novo 409', (await coord('POST', `${G}/documentos-versoes/${vB.id}/publicar`, {})).status === 409)
  check('editar vigente 409', (await coord('PATCH', `${G}/documentos-versoes/${vB.id}`, { resumoAlteracoes: 'x' })).status === 409)
  check('ppc vigente', (await coord('GET', `${G}/ppc/${prog.id}`)).body.vigente?.versao === 2)
  check('comparar', (await coord('GET', `${G}/documentos/${doc.body.id}/comparar?de=1&para=2`)).status === 200)
  check('deliberacao nao aprovada 422', (await coord('POST', `${G}/documentos-versoes/${vs.find((v) => v.body.versao === 3)!.body.id}/publicar`, { deliberacaoId: rej.body.id })).status === 422)
  check('revogar', (await coord('POST', `${G}/documentos-versoes/${vB.id}/revogar`)).status === 200)

  console.log('# jobs')
  const jobs: any = await runEduJobs()
  console.log('   ', Object.entries(jobs).filter(([k]) => k.startsWith('governanca')).map(([k, v]: any) => k + '=' + JSON.stringify(v.ok ? v.result : v.error)).join(' '))
  check('jobs ok', Object.values(jobs).every((v: any) => v.ok), Object.entries(jobs).filter(([, v]: any) => !v.ok))
  await finish(c)
}
main().catch((e) => { console.error(e); process.exit(2) })
