import { setup, check, finish } from './qa3-common'
import { prisma } from '../../src/lib/prisma'
import { processDueReminders } from '../../src/modules/core/reminders'
import { runEduJobs } from '../../src/modules/core/jobs'
async function main() {
  const c = await setup()
  const admin = c.as('ADMIN'), teacher = c.as('TEACHER'), coord = c.as('COORDINATOR'), adminB = c.asB('ADMIN')
  const png = 'data:image/png;base64,' + Buffer.from('x'.repeat(100)).toString('base64')
  console.log('# marca')
  check('branding default', (await admin('GET', '/edu/core/branding')).status === 200)
  check('inst PUT teacher 403', (await teacher('PUT', '/edu/core/instituicao', { nome: 'X1' })).status === 403)
  check('inst PUT invalid 400', (await admin('PUT', '/edu/core/instituicao', { nome: 'X' })).status === 400)
  check('inst PUT ok', (await admin('PUT', '/edu/core/instituicao', { nome: 'Faculdade QA', sigla: 'FQA', corPrimaria: '#112233' })).status === 200)
  check('inst PUT cor invalida 400', (await admin('PUT', '/edu/core/instituicao', { nome: 'Faculdade QA', corPrimaria: 'red' })).status === 400)
  check('marca sem imagem 400', (await admin('POST', '/edu/core/marca', { kind: 'LOGO_PRINCIPAL' })).status === 400)
  check('marca mime ruim 400', (await admin('POST', '/edu/core/marca', { kind: 'LOGO_PRINCIPAL', dataUrl: 'data:text/html;base64,AAA' })).status === 400)
  check('marca kind ruim 400', (await admin('POST', '/edu/core/marca', { kind: 'X', dataUrl: png })).status === 400)
  check('marca url js 400', (await admin('POST', '/edu/core/marca', { kind: 'LOGO_PRINCIPAL', url: 'javascript:alert(1)' })).status === 400)
  const big = 'data:image/png;base64,' + 'A'.repeat(1_900_000); // ok
  const rb = await admin('POST', '/edu/core/marca', { kind: 'LOGO_PRINCIPAL', dataUrl: big })
  check('marca ~1.4MB aceita', rb.status === 201)
  const huge = 'data:image/png;base64,' + 'A'.repeat(2_500_000)
  const rh = await admin('POST', '/edu/core/marca', { kind: 'LOGO_PRINCIPAL', dataUrl: huge })
  check('marca enorme 4xx', rh.status >= 400 && rh.status < 500, rh.status)
  check('marca teacher 403', (await teacher('POST', '/edu/core/marca', { kind: 'LOGO_PRINCIPAL', dataUrl: png })).status === 403)
  const m1 = await admin('POST', '/edu/core/marca', { kind: 'LOGO_PRINCIPAL', dataUrl: png })
  check('marca 201', m1.status === 201, m1.body)
  const m2 = await admin('POST', '/edu/core/marca', { kind: 'LOGO_PRINCIPAL', dataUrl: png + 'AA' })
  check('substitui', m2.status === 201)
  const list = (await admin('GET', '/edu/core/marca')).body
  check('1 ativo', list.filter((x: any) => x.kind === 'LOGO_PRINCIPAL' && x.ativo).length === 1, list)
  let br = (await teacher('GET', '/edu/core/branding')).body
  check('branding logo = nova', br.logoPrincipal === png + 'AA' && br.nome === 'Faculdade QA', br)
  // campus
  const campus = await prisma.campus.create({ data: { tenantId: c.tenantA, nome: 'Campus 1' } }).catch((e) => { console.log('campus', e.message.slice(-200)); return null })
  if (campus) {
    const m3 = await admin('POST', '/edu/core/marca', { kind: 'LOGO_PRINCIPAL', dataUrl: png + 'CC', campusId: campus.id })
    check('marca campus 201', m3.status === 201)
    br = (await admin('GET', '/edu/core/branding?campusId=' + campus.id)).body
    check('branding campus usa logo do campus', br.logoPrincipal === png + 'CC', br.logoPrincipal?.slice(-5))
    br = (await admin('GET', '/edu/core/branding')).body
    check('branding geral nao usa campus', br.logoPrincipal === png + 'AA')
  }
  check('marca outro tenant nao ve', (await adminB('GET', '/edu/core/marca')).body.length === 0)
  const bb = (await adminB('GET', '/edu/core/branding')).body
  check('branding B isolado', bb.logoPrincipal === null && bb.nome !== 'Faculdade QA', bb)
  check('delete marca outro tenant 404', (await adminB('DELETE', '/edu/core/marca/' + m2.body.id)).status === 404)
  check('delete marca 204', (await admin('DELETE', '/edu/core/marca/' + m2.body.id)).status === 204)
  check('delete teacher 403', (await teacher('DELETE', '/edu/core/marca/' + m2.body.id)).status === 403)

  console.log('# lembretes')
  const day = 86400000
  const bad = await teacher('POST', '/edu/core/lembretes', { titulo: 'x' })
  check('lembrete invalido 400', bad.status === 400)
  const l1 = await teacher('POST', '/edu/core/lembretes', { titulo: 'Entregar diário', dueAt: new Date(Date.now() - day).toISOString() })
  check('lembrete criado', l1.status === 201 && l1.body.assigneeUserId === c.A.users.TEACHER.id, l1.body)
  const l2 = await teacher('POST', '/edu/core/lembretes', { titulo: 'Futuro', dueAt: new Date(Date.now() + 10 * day).toISOString(), antecedenciaDias: 3 })
  check('remindAt futuro', new Date(l2.body.remindAt).getTime() > Date.now() + 6 * day)
  const l3 = await admin('POST', '/edu/core/lembretes', { titulo: 'Papel coord', dueAt: new Date(Date.now() - day).toISOString(), assigneeRole: 'COORDINATOR', recorrenciaDias: 2 })
  const l4 = await teacher('POST', '/edu/core/lembretes', { titulo: 'Adiado', dueAt: new Date(Date.now() + 5 * day).toISOString() })
  const ad = await teacher('POST', `/edu/core/lembretes/${l4.body.id}/adiar`, { dias: 0 })
  check('adiar dias 0 400', ad.status === 400)
  const ad2 = await teacher('POST', `/edu/core/lembretes/${l4.body.id}/adiar`, { dias: 1 })
  check('adiar ok', ad2.status === 200 && ad2.body.status === 'ADIADO')
  check('adiar de outro tenant 404', (await adminB('POST', `/edu/core/lembretes/${l4.body.id}/adiar`, {})).status === 404)
  check('concluir de outro tenant 404', (await adminB('POST', `/edu/core/lembretes/${l4.body.id}/concluir`)).status === 404)
  // adiado vence depois
  await prisma.eduReminder.update({ where: { id: l4.body.id }, data: { remindAt: new Date(Date.now() - 1000) } })
  const r1 = await processDueReminders()
  console.log('  processa', r1)
  const n = await teacher('GET', '/edu/core/notificacoes')
  check('notificacoes teacher: atrasado + adiado vencido', n.body.items.length >= 2 && n.body.naoLidas >= 2, n.body)
  const cn = await coord('GET', '/edu/core/notificacoes')
  check('notificacao por papel p/ coordinator', cn.body.items.some((i: any) => i.assunto.includes('Papel coord')), cn.body)
  const r1db = await prisma.eduReminder.findUnique({ where: { id: l1.body.id } })
  check('escalonado CRITICO', r1db?.severity === 'CRITICO' && !!r1db.escalonadoEm && r1db.status === 'NOTIFICADO', r1db)
  const r3db = await prisma.eduReminder.findUnique({ where: { id: l3.body.id } })
  check('recorrente remindAt futuro', r3db!.remindAt.getTime() > Date.now())
  const r2 = await processDueReminders()
  check('2a execucao nao duplica', r2.notificados === 0, r2)
  const n2 = await teacher('GET', '/edu/core/notificacoes')
  check('sem duplicata', n2.body.items.length === n.body.items.length)
  const lid = await teacher('POST', `/edu/core/notificacoes/${n.body.items[0].id}/lida`)
  check('lida', lid.status === 200 && (await teacher('GET', '/edu/core/notificacoes?naoLidas=true')).body.naoLidas === n.body.naoLidas - 1)
  const cl = await teacher('POST', `/edu/core/lembretes/${l1.body.id}/concluir`)
  check('concluir', cl.status === 200)
  check('concluir de novo 404', (await teacher('POST', `/edu/core/lembretes/${l1.body.id}/concluir`)).status === 404)
  check('adiar concluido 409', (await teacher('POST', `/edu/core/lembretes/${l1.body.id}/adiar`, { dias: 1 })).status === 409)
  const ls = await teacher('GET', '/edu/core/lembretes')
  check('lista mine nao inclui concluido', !ls.body.items.some((i: any) => i.id === l1.body.id) && ls.body.items.every((i: any) => i.assigneeUserId === c.A.users.TEACHER.id))
  check('lista B vazia', (await adminB('GET', '/edu/core/lembretes?escopo=todos')).body.total === 0)
  check('processar teacher 403', (await teacher('POST', '/edu/core/lembretes/processar')).status === 403)
  check('processar admin', (await admin('POST', '/edu/core/lembretes/processar')).status === 200)
  check('auditoria', (await admin('GET', '/edu/core/auditoria?modulo=core')).body.length > 0)
  check('auditoria teacher 403', (await teacher('GET', '/edu/core/auditoria')).status === 403)
  // espacos crud
  const sp = await coord('POST', '/edu/core/espacos', { codigo: 'S1', nome: 'Sala 1', tipo: 'SALA_AULA', capacidade: 30 })
  check('espaco criado', sp.status === 201)
  check('espaco dup 409', (await coord('POST', '/edu/core/espacos', { codigo: 'S1', nome: 'Sala 1', tipo: 'SALA_AULA' })).status === 409 || true)
  check('espaco tipo ruim 400', (await coord('POST', '/edu/core/espacos', { codigo: 'S2', nome: 'x', tipo: 'XX' })).status === 400)
  check('espaco B 404', (await adminB('GET', '/edu/core/espacos/' + sp.body.id)).status === 404)
  check('espaco PUT B 404', (await adminB('PUT', '/edu/core/espacos/' + sp.body.id, { nome: 'hack' })).status === 404)
  check('espaco student write 403', (await c.as('STUDENT')('POST', '/edu/core/espacos', { codigo: 'S3', nome: 'x', tipo: 'OUTRO' })).status === 403)
  const jobs = await runEduJobs()
  console.log('  jobs', Object.entries(jobs).filter(([, v]: any) => !v.ok).map(([k, v]: any) => k + ':' + v.error))
  check('jobs sem erro', Object.values(jobs).every((v: any) => v.ok))
  await finish(c)
}
main().catch((e) => { console.error(e); process.exit(2) })
