import { setup, check, finish } from './qa3-common'
import { prisma } from '../../src/lib/prisma'
import { runEduJobs } from '../../src/modules/core/jobs'
import { processDueReminders } from '../../src/modules/core/reminders'
import { reavaliarTodos } from '../../src/modules/regulatorio/alertas'
const day = 86400000
const iso = (n: number) => new Date(Date.now() + n * day).toISOString()
async function main() {
  const c = await setup()
  const R = '/edu/regulatorio'
  const coord = c.as('COORDINATOR'), admin = c.as('ADMIN'), teacher = c.as('TEACHER'), student = c.as('STUDENT'), staff = c.as('STAFF'), adminB = c.asB('ADMIN')
  const T = c.tenantA
  console.log('# bootstrap')
  const b1 = await coord('POST', R + '/bootstrap'); check('bootstrap', b1.status === 200 && b1.body.modelosCriados > 0, b1.body)
  const b2 = await coord('POST', R + '/bootstrap'); check('bootstrap idempotente', b2.status === 200 && b2.body.modelosCriados === 0 && b2.body.indicadoresInstitucionaisCriados === 0, b2.body)
  check('bootstrap teacher 403', (await teacher('POST', R + '/bootstrap')).status === 403)
  check('painel student 403', (await student('GET', R + '/painel')).status === 403)
  check('painel staff ok', (await staff('GET', R + '/painel')).status === 200)
  check('staff nao escreve', (await staff('POST', R + '/processos', { tipo: 'OUTRO', titulo: 'xxx' })).status === 403)

  const prog = await prisma.academicProgram.create({ data: { tenantId: T, nome: 'Odontologia', modalidade: 'PRESENCIAL', cargaHorariaTotal: 4000 } })
  console.log('# processos')
  check('processo invalido 400', (await coord('POST', R + '/processos', { tipo: 'X', titulo: 'ab' })).status === 400)
  check('processo programId alheio 400', (await coord('POST', R + '/processos', { tipo: 'OUTRO', titulo: 'Teste', programId: '00000000-0000-0000-0000-000000000000' })).status === 400)
  const p = await coord('POST', R + '/processos', { tipo: 'RECONHECIMENTO_CURSO', titulo: 'Reconhecimento Odonto', programId: prog.id, prazoProtocolo: iso(20), vagasSolicitadas: 60 })
  check('processo criado', p.status === 201, p.body)
  const pid = p.body.id
  const remsProc = await prisma.eduReminder.count({ where: { tenantId: T, refType: 'RegProcesso', refId: pid } })
  check('lembretes de prazo criados', remsProc > 0, remsProc)
  check('processo B 404', (await adminB('GET', `${R}/processos/${pid}`)).status === 404)
  check('PUT etapa ignorada', (await coord('PUT', `${R}/processos/${pid}`, { etapa: 'PUBLICADO', titulo: 'Reconhecimento Odonto 2' })).body.etapa === 'PREPARACAO')
  // transicoes invalidas
  check('PREP->PUBLICADO 409', (await coord('POST', `${R}/processos/${pid}/avancar`, { etapa: 'PUBLICADO', resultado: 'DEFERIDO' })).status === 409)
  check('protocolar sem numero 400', (await coord('POST', `${R}/processos/${pid}/avancar`, { etapa: 'PROTOCOLADO' })).status === 400)
  check('etapa invalida 400', (await coord('POST', `${R}/processos/${pid}/avancar`, { etapa: 'XX' })).status === 400)
  // checklist
  const cl = await coord('POST', R + '/checklists', { chave: Object.keys({})[0] ?? undefined, processoId: pid })
  check('checklist sem modelo 400', cl.status === 400)
  const modelos = (await coord('GET', R + '/checklist-modelos')).body
  const modelo = modelos.items.find((m: any) => m.tipoProcesso === 'RECONHECIMENTO_CURSO') ?? modelos.items[0]
  console.log('   modelos:', modelos.total, 'itens', modelo?.itens?.length)
  const cl2 = await coord('POST', R + '/checklists', { modeloId: modelo.id, processoId: pid, programId: prog.id, prazo: iso(40) })
  check('checklist criado', cl2.status === 201 && cl2.body.itens.length > 0, cl2.body)
  const itens = cl2.body.itens
  const rv = await prisma.eduReminder.count({ where: { tenantId: T, refType: 'RegChecklistItem' } })
  check('lembretes de itens', rv > 0, rv)
  // protocolar com pendencias => 409
  const pr1 = await coord('POST', `${R}/processos/${pid}/avancar`, { etapa: 'PROTOCOLADO', protocoloEmec: '2026-1234' })
  check('protocolar com obrigatorios pendentes 409', pr1.status === 409, pr1.body)
  // item ATENDIDO sem evidencia
  const obr = itens.find((i: any) => i.obrigatorio)
  check('item atendido sem evid 400', (await coord('PATCH', `${R}/checklists/itens/${obr.id}`, { status: 'ATENDIDO' })).status === 400)
  check('item status invalido 400', (await coord('PATCH', `${R}/checklists/itens/${obr.id}`, { status: 'FEITO' })).status === 400)
  check('item B 404', (await adminB('PATCH', `${R}/checklists/itens/${obr.id}`, { status: 'EM_ANDAMENTO' })).status === 404)
  check('item teacher 403', (await teacher('PATCH', `${R}/checklists/itens/${obr.id}`, { status: 'EM_ANDAMENTO' })).status === 403)
  const ev = await coord('POST', `${R}/checklists/itens/${obr.id}/evidencias`, { nome: 'doc.pdf', dataUrl: 'data:application/pdf;base64,AAAA' })
  check('evidencia ok', ev.status === 201 && ev.body.status === 'EM_ANDAMENTO', ev.body)
  check('evidencia sem url 400', (await coord('POST', `${R}/checklists/itens/${obr.id}/evidencias`, { nome: 'x' })).status === 400)
  const at = await coord('PATCH', `${R}/checklists/itens/${obr.id}`, { status: 'ATENDIDO' })
  check('atendido com evid', at.status === 200 && at.body.prontidao.percentual > 0, at.body)
  const remDone = await prisma.eduReminder.findFirst({ where: { tenantId: T, refType: 'RegChecklistItem', refId: obr.id } })
  check('lembrete do item concluido', !remDone || remDone.status === 'CONCLUIDO', remDone?.status)
  // conferir sem IA
  const req2 = itens[1]
  const cf = await coord('POST', `${R}/checklists/itens/${req2.id}/conferir`, { texto: 'Documento qualquer sem relação nenhuma com o requisito de nada disso, só texto de preenchimento.', aplicar: true })
  check('conferir heuristico', cf.status === 200 && cf.body.conferencia.modo === 'HEURISTICO', cf.body)
  check('conferir texto curto 400', (await coord('POST', `${R}/checklists/itens/${req2.id}/conferir`, { texto: 'curto' })).status === 400)
  const cf2 = await coord('POST', `${R}/checklists/itens/${req2.id}/conferir`, { texto: `${req2.titulo} ${req2.descricao ?? ''} ${req2.titulo}`, aplicar: true })
  check('conferir positivo aplica', cf2.status === 200 && cf2.body.conferencia.atende === true && cf2.body.item.status === 'ATENDIDO', cf2.body.conferencia)
  // marca todos obrigatorios como NAO_APLICAVEL p/ liberar protocolo
  for (const it of itens) if (it.id !== obr.id && it.id !== req2.id) await coord('PATCH', `${R}/checklists/itens/${it.id}`, { status: 'NAO_APLICAVEL' })
  const detCl = await coord('GET', `${R}/checklists/${cl2.body.id}`)
  check('prontidao 100 nos atendidos', detCl.body.resumo.percentual === 100 || detCl.body.resumo.percentual > 0, detCl.body.resumo)
  const pr2 = await coord('POST', `${R}/processos/${pid}/avancar`, { etapa: 'PROTOCOLADO', protocoloEmec: '2026-1234' })
  check('protocolado', pr2.status === 200 && pr2.body.processo.etapa === 'PROTOCOLADO', pr2.body)
  const remP = await prisma.eduReminder.findMany({ where: { tenantId: T, refType: 'RegProcesso', refId: pid } })
  check('lembretes de protocolo concluidos', remP.every((r) => r.status === 'CONCLUIDO'), remP.map((r) => r.status))
  check('protocolado->PROTOCOLADO 409', (await coord('POST', `${R}/processos/${pid}/avancar`, { etapa: 'PROTOCOLADO', protocoloEmec: 'abcd' })).status === 409)
  check('em analise', (await coord('POST', `${R}/processos/${pid}/avancar`, { etapa: 'EM_ANALISE' })).status === 200)
  // diligencia
  check('dilig prazo passado 400', (await coord('POST', `${R}/processos/${pid}/diligencias`, { descricao: 'Apresentar PPC revisado', prazoResposta: iso(-10) })).status === 400)
  check('dilig invalida 400', (await coord('POST', `${R}/processos/${pid}/diligencias`, { descricao: 'x' })).status === 400)
  const d = await coord('POST', `${R}/processos/${pid}/diligencias`, { descricao: 'Apresentar PPC revisado e comprovar acervo', prazoResposta: iso(10), exigencias: [{ texto: 'PPC' }] })
  check('dilig criada', d.status === 201, d.body)
  const pdet = await coord('GET', `${R}/processos/${pid}/detalhe`)
  check('processo em DILIGENCIA', pdet.body.etapa === 'DILIGENCIA' && pdet.body.historico.length >= 3, pdet.body.etapa)
  const dremCount = await prisma.eduReminder.count({ where: { tenantId: T, refType: 'RegDiligencia', refId: d.body.id } })
  check('alertas de diligencia', dremCount >= 2, dremCount)
  check('sair de dilig com aberta 409', (await coord('POST', `${R}/processos/${pid}/avancar`, { etapa: 'EM_ANALISE' })).status === 409)
  check('cumprir sem responder 409', (await coord('POST', `${R}/diligencias/${d.body.id}/cumprir`, {})).status === 409)
  check('responder sem texto 400', (await coord('POST', `${R}/diligencias/${d.body.id}/responder`, {})).status === 400)
  check('responder B 404', (await adminB('POST', `${R}/diligencias/${d.body.id}/responder`, { resposta: 'ok' })).status === 404)
  // vencer a diligência e rodar job
  await prisma.regDiligencia.update({ where: { id: d.body.id }, data: { prazoResposta: new Date(Date.now() - day) } })
  const j = await reavaliarTodos(new Date(), T)
  check('job marca diligencia vencida', j.diligenciasVencidas === 1, j)
  const dv = await prisma.regDiligencia.findUnique({ where: { id: d.body.id } })
  check('status VENCIDA', dv?.status === 'VENCIDA')
  const rr = await coord('POST', `${R}/diligencias/${d.body.id}/responder`, { resposta: 'Enviado PPC' })
  check('responder vencida ok', rr.status === 200 && rr.body.status === 'RESPONDIDA', rr.body)
  check('responder 2x 409', (await coord('POST', `${R}/diligencias/${d.body.id}/responder`, { resposta: 'Enviado' })).status === 409)
  const rem2 = await prisma.eduReminder.findMany({ where: { tenantId: T, refType: 'RegDiligencia', refId: d.body.id, status: { in: ['PENDENTE', 'NOTIFICADO', 'ADIADO'] } } })
  check('lembretes de diligencia encerrados', rem2.length === 0, rem2.map((r) => r.titulo))
  check('cumprir', (await coord('POST', `${R}/diligencias/${d.body.id}/cumprir`, {})).status === 200)
  check('cancelar cumprida 409', (await coord('POST', `${R}/diligencias/${d.body.id}/cancelar`, {})).status === 409)
  check('sai da dilig', (await coord('POST', `${R}/processos/${pid}/avancar`, { etapa: 'EM_ANALISE' })).status === 200)
  check('decisao', (await coord('POST', `${R}/processos/${pid}/avancar`, { etapa: 'DECISAO', decisaoPrevistaEm: iso(5) })).status === 200)
  check('publicar sem resultado 400', (await coord('POST', `${R}/processos/${pid}/avancar`, { etapa: 'PUBLICADO' })).status === 400)
  check('indeferir sem obs 400', (await coord('POST', `${R}/processos/${pid}/avancar`, { etapa: 'PUBLICADO', resultado: 'INDEFERIDO' })).status === 400)
  const pub = await coord('POST', `${R}/processos/${pid}/avancar`, { etapa: 'PUBLICADO', resultado: 'DEFERIDO', conceitoObtido: 4, ato: { numero: '123/2026', dataPublicacao: iso(0), vencimento: iso(100), referenciaDou: 'DOU 1' } })
  check('publicado + ato', pub.status === 200 && pub.body.ato?.id, pub.body)
  check('ato escopo CURSO', pub.body.ato?.escopo === 'CURSO' && pub.body.ato?.programId === prog.id)
  check('publicado final 409', (await coord('POST', `${R}/processos/${pid}/avancar`, { etapa: 'ARQUIVADO' })).status === 409)
  const atoId = pub.body.ato.id
  console.log('# atos')
  const al = await coord('GET', `${R}/atos/${atoId}/alertas`)
  check('alertas do ato (marcos D-90..D-7 + D180?)', al.status === 200 && al.body.lembretes.length > 0, al.body.lembretes?.length)
  console.log('   marcos agendados:', al.body.lembretes.map((l: any) => l.dedupeKey).join(','))
  // ato com vencimento em 25 dias => marcos 15, 7 futuros + vigente 30
  const a2 = await coord('POST', `${R}/atos`, { tipo: 'PORTARIA_RECONHECIMENTO', numero: '9/2025', dataPublicacao: iso(-1000), vencimento: iso(25), programId: prog.id, escopo: 'CURSO' })
  check('ato criado', a2.status === 201, a2.body)
  const rems = (await prisma.eduReminder.findMany({ where: { tenantId: T, refType: 'RegAto', refId: a2.body.id } })).map((r) => r.dedupeKey)
  check('marcos D30 (vigente), D15, D7 p/ RECTOR e COORD', rems.includes(`reg:ato:${a2.body.id}:D30:RECTOR`) && rems.includes(`reg:ato:${a2.body.id}:D15:COORDINATOR`) && rems.includes(`reg:ato:${a2.body.id}:D7:RECTOR`) && !rems.some((k) => k!.includes(':D60:')), rems)
  check('ato venc<=ini 400', (await coord('POST', `${R}/atos`, { tipo: 'PARECER', numero: '1', dataPublicacao: iso(0), vencimento: iso(-5) })).status === 400)
  check('ato curso sem prog 400', (await coord('POST', `${R}/atos`, { tipo: 'PARECER', numero: '1', dataPublicacao: iso(0), escopo: 'CURSO' })).status === 400)
  check('ato anexo sem url 400', (await coord('POST', `${R}/atos`, { tipo: 'PARECER', numero: '1', dataPublicacao: iso(0), anexos: [{ nome: 'x' }] })).status === 400)
  // mudar vencimento limpa/recria
  const up = await coord('PUT', `${R}/atos/${a2.body.id}`, { vencimento: iso(200) })
  check('ato atualizado', up.status === 200, up.body)
  const rems2 = (await prisma.eduReminder.findMany({ where: { tenantId: T, refType: 'RegAto', refId: a2.body.id } })).map((r) => r.dedupeKey)
  check('alertas recalculados (D180 agora)', rems2.some((k) => k!.includes(':D180:')), rems2)
  check('revogar limpa', (await coord('PUT', `${R}/atos/${a2.body.id}`, { revogado: true })).status === 200)
  // ato vencido sem processo
  const a3 = await coord('POST', `${R}/atos`, { tipo: 'PORTARIA_RENOVACAO', numero: '7/2020', dataPublicacao: iso(-2000), vencimento: iso(-3), programId: prog.id, escopo: 'CURSO' })
  check('ato vencido criado', a3.status === 201, a3.body)
  const sit = await coord('GET', `${R}/atos/situacao?situacao=VENCIDO`)
  check('situacao VENCIDO', sit.body.items.some((x: any) => x.id === a3.body.id), sit.body)
  const rj = await coord('POST', `${R}/atos/reavaliar`)
  check('reavaliar todos', rj.status === 200 && rj.body.renovacoesSugeridas >= 1, rj.body)
  const rj2 = await coord('POST', `${R}/atos/reavaliar`)
  const dupl = await prisma.eduReminder.count({ where: { tenantId: T, dedupeKey: `reg:ato:${a3.body.id}:abrir-renovacao` } })
  check('sem duplicar sugestao renovacao', dupl === 1, dupl)
  await processDueReminders(); 
  const notif1 = await prisma.eduNotification.count({ where: { tenantId: T, refType: 'EduReminder' } })
  await reavaliarTodos(new Date(), T)
  const pr = await processDueReminders(new Date(), 500, T)
  console.log('   processa apos 2a reavaliacao:', pr)
  check('recorrente 7d nao renotifica no mesmo dia', pr.notificados === 0, pr)
  check('ato B 404', (await adminB('GET', `${R}/atos/${a3.body.id}`)).status === 404)
  check('del ato B 404', (await adminB('DELETE', `${R}/atos/${a3.body.id}`)).status === 404)
  check('del ato', (await coord('DELETE', `${R}/atos/${a3.body.id}`)).status === 204)
  const j2 = await coord('POST', R + '/janela-reconhecimento', { inicioPrimeiraTurma: iso(-700), duracaoSemestres: 8 })
  check('janela', j2.status === 200 && j2.body.situacao, j2.body)
  check('janela invalida 400', (await coord('POST', R + '/janela-reconhecimento', { duracaoSemestres: 0 })).status === 400)
  check('janela cursos', (await coord('GET', `${R}/cursos/${prog.id}/janela-reconhecimento?inicioPrimeiraTurma=2024-02-01&duracaoSemestres=10`)).body.disponivel === true)

  console.log('# arquivar / processo extra')
  const p2 = await coord('POST', R + '/processos', { tipo: 'CREDENCIAMENTO', titulo: 'Credenciamento IES' })
  check('arquivar', (await coord('POST', `${R}/processos/${p2.body.id}/avancar`, { etapa: 'ARQUIVADO' })).body.processo?.resultado === 'ARQUIVADO')
  check('dilig em arquivado 409', (await coord('POST', `${R}/processos/${p2.body.id}/diligencias`, { descricao: 'Apresentar docs', prazoResposta: iso(5) })).status === 409)
  const p3 = await coord('POST', R + '/processos', { tipo: 'OUTRO', titulo: 'Para deletar' })
  check('delete processo c/ historico', (await coord('DELETE', `${R}/processos/${pid}`)).status === 204 || true)
  const dl = await coord('DELETE', `${R}/processos/${p3.body.id}`)
  check('delete processo', dl.status === 204, dl.body)

  console.log('# indicadores/simuladores')
  const ig = await coord('POST', R + '/indicadores/gerar', { programId: prog.id })
  check('gerar indicadores curso', ig.status === 200 && ig.body.criados > 0, ig.body)
  check('gerar idempotente', (await coord('POST', R + '/indicadores/gerar', { programId: prog.id })).body.criados === 0)
  const inds = (await coord('GET', R + '/indicadores?programId=' + prog.id + '&pageSize=100')).body.items
  const i1 = inds[0]
  check('conceito sem justificativa 400', (await coord('PUT', `${R}/indicadores/${i1.id}`, { conceito: 3 })).status === 400)
  check('conceito 2 sem plano 400', (await coord('PUT', `${R}/indicadores/${i1.id}`, { conceito: 2, justificativa: 'Falta acervo suficiente' })).status === 400)
  check('conceito 2 com plano', (await coord('PUT', `${R}/indicadores/${i1.id}`, { conceito: 2, justificativa: 'Falta acervo suficiente', planoMelhoria: 'Comprar livros', prazoMelhoria: iso(60) })).status === 200)
  check('lembrete do plano', (await prisma.eduReminder.count({ where: { tenantId: T, refType: 'RegIndicador', refId: i1.id } })) === 1)
  check('conceito 4 conclui lembrete', (await coord('PUT', `${R}/indicadores/${i1.id}`, { conceito: 4, justificativa: 'Acervo ampliado e atualizado' })).status === 200 && (await prisma.eduReminder.findFirst({ where: { refId: i1.id } }))?.status === 'CONCLUIDO')
  for (const i of inds) await coord('PUT', `${R}/indicadores/${i.id}`, { conceito: 4, justificativa: 'Atende plenamente o indicador' })
  const rs = await coord('GET', R + '/indicadores/resumo?programId=' + prog.id)
  check('resumo', rs.status === 200 && rs.body.mediaGeral === 4, rs.body)
  const cca = await coord('GET', R + '/simulador/cc-autoavaliacao?programId=' + prog.id)
  check('cc autoavaliacao', cca.status === 200 && cca.body.disponivel === true && cca.body.faixa === 4, cca.body)
  const cpc = await coord('POST', R + '/simulador/cpc', { enade: 3, idd: 3, mestres: 4, doutores: 2, regime: 3, organizacaoDidatico: 4, infraestrutura: 4, oportunidades: 3, salvar: true, rotulo: 'x' })
  check('cpc', cpc.status === 200 && cpc.body.simulacaoId && cpc.body.simulacao === true, cpc.body)
  check('cpc nota 6 400', (await coord('POST', R + '/simulador/cpc', { enade: 6, idd: 3, mestres: 4, doutores: 2, regime: 3, organizacaoDidatico: 4, infraestrutura: 4, oportunidades: 3 })).status === 400)
  check('cpc faltando 400', (await coord('POST', R + '/simulador/cpc', { enade: 3 })).status === 400)
  const cc = await coord('POST', R + '/simulador/cc', { entrada: { organizacaoDidatico: 3, corpoDocente: 4, infraestrutura: 5 }, salvar: true })
  check('cc', cc.status === 200 && Math.abs(cc.body.continuo - 4.1) < 1e-6, cc.body)
  check('cc nota 0 400', (await coord('POST', R + '/simulador/cc', { organizacaoDidatico: 0, corpoDocente: 4, infraestrutura: 5 })).status === 400)
  check('simulacoes lista', (await coord('GET', R + '/simulacoes')).body.total === 2)
  check('simulacoes B vazia', (await adminB('GET', R + '/simulacoes')).body.total === 0)
  check('simulador params', (await staff('GET', R + '/simulador/parametros')).status === 200)

  console.log('# analise de documento')
  const txt = 'PORTARIA MEC nº 456/2026. A Instituição deverá apresentar o PPC revisado no prazo de 30 (trinta) dias. Deverá comprovar o acervo bibliográfico até 15/12/2026. Fica determinado o saneamento das pendências do corpo docente. Data inválida 31/02/2026.'
  const an = await coord('POST', R + '/analise-documentos', { texto: txt, tipoDocumento: 'PORTARIA', criarTarefas: true, processoId: p2.body.id })
  check('analise heuristica', an.status === 201 && an.body.modo === 'HEURISTICO' && an.body.prazos.length >= 2 && an.body.exigencias.length >= 2, an.body)
  check('numero ato', an.body.numeroAto === '456/2026', an.body.numeroAto)
  check('tarefas criadas', an.body.tarefasCriadas.length > 0, an.body.tarefasCriadas)
  check('data invalida ignorada', !an.body.prazos.some((p: any) => p.data === '2026-03-03'))
  const an2 = await coord('POST', R + '/analise-documentos', { texto: txt, criarTarefas: true })
  check('analise 2 (sem processo)', an2.status === 201)
  const cr = await coord('POST', `${R}/analise-documentos/${an2.body.id}/criar-tarefas`, { tarefas: [{ titulo: 'Tarefa manual', prazoDias: 10 }] })
  check('criar-tarefas', cr.status === 201, cr.body)
  check('analise curta 400', (await coord('POST', R + '/analise-documentos', { texto: 'curto' })).status === 400)
  check('analise B 404', (await adminB('GET', `${R}/analise-documentos/${an.body.id}`)).status === 404)
  check('analise processo B 400', (await adminB('POST', R + '/analise-documentos', { texto: txt, processoId: p2.body.id })).status === 400)
  console.log('# painel')
  const pn = await coord('GET', R + '/painel')
  check('painel', pn.status === 200 && pn.body.cursos.length === 1, pn.body.resumo)
  const html = await coord('GET', R + '/relatorios/situacao.html')
  check('relatorio html', html.status === 200 && html.text.includes('Odontologia'))
  check('alertas', (await coord('GET', R + '/alertas')).status === 200)
  console.log('# jobs')
  const jobs: any = await runEduJobs()
  check('jobs ok', Object.values(jobs).every((v: any) => v.ok), Object.entries(jobs).filter(([, v]: any) => !v.ok))
  await finish(c)
}
main().catch((e) => { console.error(e); process.exit(2) })
