import { setup, check, finish } from './qa3-common'
import { prisma } from '../../src/lib/prisma'
import { runEduJobs } from '../../src/modules/core/jobs'
import { processDueReminders, scheduleReminder } from '../../src/modules/core/reminders'
import { okrManutencao } from '../../src/modules/reitoria/okr'
const day = 86400000
const iso = (n: number) => new Date(Date.now() + n * day).toISOString()
async function main() {
  const c = await setup()
  const R = '/edu/reitoria'
  const T = c.tenantA
  const as = c.as, adminB = c.asB('ADMIN')
  const admin = as('ADMIN'), rector = as('RECTOR'), board = as('BOARD'), coord = as('COORDINATOR'), teacher = as('TEACHER'), student = as('STUDENT'), fin = as('FINANCE'), sec = as('SECRETARY'), staff = as('STAFF')
  // dados reais
  const prog = await prisma.academicProgram.create({ data: { tenantId: T, nome: 'Direito', modalidade: 'PRESENCIAL', cargaHorariaTotal: 3700 } })
  const term = await prisma.academicTerm.create({ data: { tenantId: T, codigo: '2026/2', dataInicio: new Date(Date.now() - 60 * day), dataFim: new Date(Date.now() + 100 * day) } })
  const sts: any[] = []
  for (let i = 0; i < 6; i++) {
    const u = i === 0 ? c.A.users.STUDENT.id : (await prisma.user.create({ data: { clinicId: c.A.clinic.id, tenantId: T, email: `al${i}@${T}.com`, password: 'x', firstName: 'Al' + i, lastName: 'Q', role: 'STUDENT' } })).id
    const st = await prisma.student.create({ data: { tenantId: T, userId: u, ra: `${T}-${i}`, nomeCompleto: 'Aluno ' + i, status: i === 5 ? 'TRANCADO' : 'ATIVO' } })
    await prisma.enrollment.create({ data: { studentId: st.id, programId: prog.id, termId: term.id, status: i === 5 ? 'TRANCADA' : 'ATIVA' } })
    await prisma.accountReceivable.create({ data: { tenantId: T, studentId: st.id, descricao: 'Mensalidade', valor: 1000, dataVencimento: new Date(Date.now() - (i + 1) * 10 * day), status: i % 2 ? 'PAGO' : 'ATRASADO', dataPagamento: i % 2 ? new Date() : null } })
    sts.push(st)
  }
  console.log('# painel')
  for (const [nome, f, perf] of [['admin', admin, 'reitoria'], ['rector', rector, 'reitoria'], ['board', board, 'reitoria'], ['coord', coord, 'coordenacao'], ['teacher', teacher, 'professor'], ['fin', fin, 'administracao'], ['sec', sec, 'secretaria']] as any) {
    const r = await f('GET', R + '/painel')
    check(`painel ${nome} => ${perf}`, r.status === 200 && r.body.perfil === perf && Array.isArray(r.body.indicadores) && r.body.indicadores.length > 0, r.body?.error ?? r.status)
    if (r.status === 200) check(`painel ${nome} sem indicador com erro`, r.body.indicadoresComErro.length === 0, r.body.indicadoresComErro)
  }
  check('painel student 403', (await student('GET', R + '/painel')).status === 403)
  check('painel staff 403', (await staff('GET', R + '/painel')).status === 403)
  check('coord ve perfil reitoria? 403', (await coord('GET', R + '/painel/reitoria')).status === 403)
  check('coord ve perfil infra 403', (await coord('GET', R + '/painel?perfil=infraestrutura')).status === 403)
  check('perfil invalido 400', (await admin('GET', R + '/painel/xx')).status === 400)
  for (const p of ['administracao', 'coordenacao', 'secretaria', 'professor', 'biblioteca', 'infraestrutura', 'admissoes']) {
    const r = await admin('GET', `${R}/painel/${p}`); check('admin perfil ' + p, r.status === 200 && r.body.indicadoresComErro.length === 0, r.body.indicadoresComErro ?? r.body)
  }
  const pr = await admin('GET', R + '/painel'); const ind = (k: string) => pr.body.indicadores.find((i: any) => i.chave === k)
  console.log('   alguns indicadores:', pr.body.indicadores.slice(0, 8).map((i: any) => `${i.chave}=${i.valor}`).join(' '))
  check('painel curso filtrado', (await admin('GET', R + '/painel?programId=' + prog.id)).status === 200)
  check('painel curso alheio 404', (await adminB('GET', R + '/painel?programId=' + prog.id)).status === 404)
  check('perfis', (await coord('GET', R + '/painel/perfis')).body.disponiveis.length === 1)
  check('catalogo', (await coord('GET', R + '/indicadores/catalogo')).status === 200)
  check('atualizar coord 403', (await coord('POST', R + '/painel/atualizar')).status === 403)
  check('atualizar admin', (await admin('POST', R + '/painel/atualizar')).status === 200)
  const sn = await admin('POST', R + '/painel/snapshot'); check('snapshot', sn.status === 200 && sn.body.snapshots > 0, sn.body)
  const sn2 = await admin('POST', R + '/painel/snapshot'); check('snapshot idempotente (mesmo dia)', sn2.status === 200)
  const nSnap = await prisma.reiSnapshot.count({ where: { tenantId: T, chave: pr.body.indicadores[0].chave } })
  check('1 snapshot/dia/indicador', nSnap === 1, nSnap)
  check('historico', (await admin('GET', `${R}/indicadores/${pr.body.indicadores[0].chave}/historico`)).body.length === 1)
  check('historico inexistente 404', (await admin('GET', `${R}/indicadores/zzz/historico`)).status === 404)
  check('painel B isolado', (await adminB('GET', R + '/painel')).body.indicadores.every((i: any) => i.valor == null || i.valor === 0 || i.chave.length > 0))

  console.log('# mesa')
  await scheduleReminder({ tenantId: T, modulo: 'teste', titulo: 'Lembrete teacher', dueAt: new Date(Date.now() - day), assigneeUserId: c.A.users.TEACHER.id, remindAt: new Date() })
  await scheduleReminder({ tenantId: T, modulo: 'teste', titulo: 'Lembrete papel coord', dueAt: new Date(Date.now() + 2 * day), assigneeRole: 'COORDINATOR' })
  await scheduleReminder({ tenantId: T, modulo: 'teste', titulo: 'Lembrete longe', dueAt: new Date(Date.now() + 90 * day), assigneeUserId: c.A.users.TEACHER.id })
  const m1 = await teacher('GET', R + '/mesa'); check('mesa teacher', m1.status === 200 && m1.body.items.some((i: any) => i.titulo === 'Lembrete teacher') && !m1.body.items.some((i: any) => i.titulo === 'Lembrete longe'), m1.body)
  check('mesa ordenada (atrasado primeiro)', m1.body.items[0].titulo === 'Lembrete teacher')
  check('mesa coord (papel)', (await coord('GET', R + '/mesa')).body.items.some((i: any) => i.titulo === 'Lembrete papel coord'))
  check('mesa student ok', (await student('GET', R + '/mesa')).status === 200)
  check('mesa filtro atrasados', (await teacher('GET', R + '/mesa?atrasados=true')).body.items.every((i: any) => i.atrasadoDias > 0))
  check('mesa sem fontes com erro', m1.body.fontesComErro.length === 0, m1.body.fontesComErro)
  const sino = await teacher('GET', R + '/mesa/resumo'); check('sino', sino.status === 200 && sino.body.badge >= 1, sino.body)
  const lemb = m1.body.items.find((i: any) => i.titulo === 'Lembrete teacher'); const lid = lemb.ref.id
  check('concluir alheio 403', (await coord('POST', `${R}/mesa/lembretes/${lid}/concluir`)).status === 403)
  check('concluir B 404', (await adminB('POST', `${R}/mesa/lembretes/${lid}/concluir`)).status === 404)
  check('adiar 0 400', (await teacher('POST', `${R}/mesa/lembretes/${lid}/adiar`, { dias: 0 })).status === 400)
  const ad = await teacher('POST', `${R}/mesa/lembretes/${lid}/adiar`, { dias: 3, motivo: 'feriado' }); check('adiar', ad.status === 200 && ad.body.status === 'PENDENTE')
  check('concluir', (await teacher('POST', `${R}/mesa/lembretes/${lid}/concluir`)).status === 200)
  check('concluir 2x 409', (await teacher('POST', `${R}/mesa/lembretes/${lid}/concluir`)).status === 409)
  check('adiar concluido 409', (await teacher('POST', `${R}/mesa/lembretes/${lid}/adiar`, { dias: 1 })).status === 409)
  check('sino atualiza apos concluir', !(await teacher('GET', R + '/mesa')).body.items.some((i: any) => i.titulo === 'Lembrete teacher'))
  check('panorama coord', (await coord('GET', R + '/mesa/panorama')).status === 200)
  check('panorama teacher 403', (await teacher('GET', R + '/mesa/panorama')).status === 403)
  await scheduleReminder({ tenantId: T, modulo: 'teste', titulo: 'Notif p/ teacher', dueAt: new Date(Date.now() - day), assigneeUserId: c.A.users.TEACHER.id, remindAt: new Date(Date.now() - day) })
  await processDueReminders(new Date(), 500, T)
  const nt = await teacher('GET', '/edu/core/notificacoes'); check('notificacao in-app gerada', nt.body.items.length >= 1, nt.body)
  const nid = nt.body.items[0].id
  check('notif lida (mesa)', (await teacher('POST', `${R}/mesa/notificacoes/${nid}/lida`)).status === 200)
  check('notif lida alheia 404', (await coord('POST', `${R}/mesa/notificacoes/${nid}/lida`)).status === 404)
  check('notif lidas todas', (await teacher('POST', `${R}/mesa/notificacoes/lidas`)).status === 200)

  console.log('# OKR')
  const bt = await admin('POST', R + '/bootstrap'); check('bootstrap okr', bt.status === 200 && bt.body.criados.length === 5, bt.body)
  const bt2 = await admin('POST', R + '/bootstrap'); check('bootstrap idempotente', bt2.body.criados.length === 0 && bt2.body.existentes.length === 5, bt2.body)
  check('bootstrap coord 403', (await coord('POST', R + '/bootstrap')).status === 403)
  check('objetivo criar coord 403', (await coord('POST', R + '/objetivos', { titulo: 'Abc', ciclo: '2026', inicio: iso(0), fim: iso(100) })).status === 403)
  check('objetivo invalido 400', (await admin('POST', R + '/objetivos', { titulo: 'a' })).status === 400)
  check('objetivo fim<inicio 422', (await admin('POST', R + '/objetivos', { titulo: 'Abc', ciclo: '2026', inicio: iso(10), fim: iso(1) })).status === 422)
  check('objetivo curso sem prog 422', (await admin('POST', R + '/objetivos', { titulo: 'Abc', ciclo: '2026', nivel: 'CURSO', inicio: iso(0), fim: iso(10) })).status === 422)
  const ob = await admin('POST', R + '/objetivos', { titulo: 'Expandir pesquisa', ciclo: '2026', inicio: iso(-30), fim: iso(150), responsavelUserId: c.A.users.TEACHER.id }); check('objetivo', ob.status === 201, ob.body)
  check('ativar sem KR 422', (await admin('POST', `${R}/objetivos/${ob.body.id}/ativar`)).status === 422)
  check('KR meta==inicial 422', (await admin('POST', `${R}/objetivos/${ob.body.id}/resultados-chave`, { titulo: 'KR 1', valorInicial: 10, valorMeta: 10 })).status === 422)
  check('KR sentido errado 422', (await admin('POST', `${R}/objetivos/${ob.body.id}/resultados-chave`, { titulo: 'KR 1', valorInicial: 10, valorMeta: 5 })).status === 422)
  check('KR indicador inexistente 422', (await admin('POST', `${R}/objetivos/${ob.body.id}/resultados-chave`, { titulo: 'KR 1', valorInicial: 10, valorMeta: 20, fonte: 'INDICADOR', indicadorChave: 'zzz' })).status === 422)
  const kr1 = await admin('POST', `${R}/objetivos/${ob.body.id}/resultados-chave`, { titulo: 'Publicações', valorInicial: 0, valorMeta: 10, checkinFrequenciaDias: 7 }); check('KR1', kr1.status === 201 && kr1.body.progresso === 0, kr1.body)
  const kr2 = await admin('POST', `${R}/objetivos/${ob.body.id}/resultados-chave`, { titulo: 'Redução de evasão', valorInicial: 20, valorMeta: 10, sentido: 'MENOR_MELHOR', peso: 3 }); check('KR2', kr2.status === 201)
  check('ativar', (await admin('POST', `${R}/objetivos/${ob.body.id}/ativar`)).body.status === 'ATIVO')
  check('ativar 2x 409', (await admin('POST', `${R}/objetivos/${ob.body.id}/ativar`)).status === 409)
  check('lembrete de check-in criado', (await prisma.eduReminder.count({ where: { tenantId: T, refType: 'ReiResultadoChave', refId: kr1.body.id } })) === 1)
  check('delete objetivo ativo 409', (await admin('DELETE', `${R}/objetivos/${ob.body.id}`)).status === 409)
  check('checkin student 403', (await student('POST', `${R}/resultados-chave/${kr1.body.id}/checkins`, { valor: 1 })).status === 403)
  check('checkin staff (nao resp.) 403', (await staff('POST', `${R}/resultados-chave/${kr1.body.id}/checkins`, { valor: 1 })).status === 403)
  check('checkin B 404', (await adminB('POST', `${R}/resultados-chave/${kr1.body.id}/checkins`, { valor: 1 })).status === 404)
  const ck = await teacher('POST', `${R}/resultados-chave/${kr1.body.id}/checkins`, { valor: 5, comentario: 'Metade' }); check('checkin (responsavel do objetivo)', ck.status === 201 && ck.body.resultado.progresso === 50, ck.body)
  check('lembrete do proximo check-in pendente', (await prisma.eduReminder.count({ where: { tenantId: T, refType: 'ReiResultadoChave', refId: kr1.body.id, status: 'PENDENTE' } })) === 1)
  const ck2 = await admin('POST', `${R}/resultados-chave/${kr2.body.id}/checkins`, { valor: 20, confianca: 'VERMELHO' }); check('checkin vermelho', ck2.status === 201, ck2.body)
  check('checkin vermelho gera lembrete critico', (await prisma.eduReminder.count({ where: { tenantId: T, refType: 'ReiResultadoChave', refId: kr2.body.id, severity: 'CRITICO' } })) >= 1)
  const od = await admin('GET', `${R}/objetivos/${ob.body.id}`); check('objetivo progresso ponderado 12.5', od.body.progresso === 12.5, od.body.progresso)
  check('kr valor em %: 150% satura 100', (await admin('POST', `${R}/resultados-chave/${kr1.body.id}/checkins`, { valor: 15 })).body.resultado.progresso === 100)
  check('kr patch', (await admin('PATCH', `${R}/resultados-chave/${kr1.body.id}`, { valorMeta: 20 })).status === 200)
  check('delete KR com checkins 409', (await admin('DELETE', `${R}/resultados-chave/${kr1.body.id}`)).status === 409)
  check('checkins hist', (await coord('GET', `${R}/resultados-chave/${kr1.body.id}/checkins`)).body.length === 2)
  // KR por indicador
  const krI = await admin('POST', `${R}/objetivos/${ob.body.id}/resultados-chave`, { titulo: 'Inadimplência', valorInicial: 90, valorMeta: 5, sentido: 'MENOR_MELHOR', fonte: 'INDICADOR', indicadorChave: 'inadimplencia' }); check('KR indicador', krI.status === 201, krI.body)
  check('checkin manual em KR indicador 409', (await admin('POST', `${R}/resultados-chave/${krI.body.id}/checkins`, { valor: 1 })).status === 409)
  const sy = await admin('POST', R + '/okr/sincronizar'); check('sincronizar', sy.status === 200, sy.body)
  console.log('   sync', sy.body)
  const krIdb = await prisma.reiResultadoChave.findUnique({ where: { id: krI.body.id } }); console.log('   KR indicador valorAtual', krIdb?.valorAtual, 'indicador', ind('inadimplencia')?.valor)
  // KR manual desatualizado => escala
  await prisma.reiResultadoChave.update({ where: { id: kr2.body.id }, data: { ultimoCheckinEm: new Date(Date.now() - 40 * day) } })
  const sy2 = await admin('POST', R + '/okr/sincronizar'); check('escalonamento check-in atrasado', sy2.body.escalonados >= 1, sy2.body)
  const sy3 = await admin('POST', R + '/okr/sincronizar'); const escal = await prisma.eduReminder.count({ where: { tenantId: T, dedupeKey: { startsWith: `rei-kr-atraso:${kr2.body.id}` } } })
  check('escalonamento sem duplicar', escal === 1, escal)
  check('okr painel', (await coord('GET', R + '/okr/painel')).status === 200)
  check('okr painel student 403', (await student('GET', R + '/okr/painel')).status === 403)
  check('okr ciclos', (await coord('GET', R + '/okr/ciclos')).body.length >= 1)
  check('objetivos lista', (await coord('GET', R + '/objetivos?ciclo=2026')).body.total >= 6)
  check('objetivo B 404', (await adminB('GET', `${R}/objetivos/${ob.body.id}`)).status === 404)
  check('concluir', (await admin('POST', `${R}/objetivos/${ob.body.id}/concluir`)).body.status === 'CONCLUIDO')
  check('KR em objetivo concluido 409', (await admin('POST', `${R}/objetivos/${ob.body.id}/resultados-chave`, { titulo: 'KR novo', valorInicial: 0, valorMeta: 3 })).status === 409)
  check('lembretes cancelados', (await prisma.eduReminder.count({ where: { tenantId: T, refType: 'ReiObjetivo', refId: ob.body.id, status: { in: ['PENDENTE', 'NOTIFICADO'] } } })) === 0)
  check('reabrir', (await admin('POST', `${R}/objetivos/${ob.body.id}/reabrir`)).body.status === 'ATIVO')
  check('cancelar', (await admin('POST', `${R}/objetivos/${ob.body.id}/cancelar`)).body.status === 'CANCELADO')
  check('cancelar 2x 409', (await admin('POST', `${R}/objetivos/${ob.body.id}/cancelar`)).status === 409)
  const rasc = (await admin('GET', R + '/objetivos?status=RASCUNHO')).body.items[0]
  check('delete rascunho', (await admin('DELETE', `${R}/objetivos/${rasc.id}`)).status === 204)
  const okrAct = (await admin('GET', R + '/objetivos?status=RASCUNHO')).body.items[0]
  check('ativar modelo do bootstrap', (await admin('POST', `${R}/objetivos/${okrAct.id}/ativar`)).status === 200)
  console.log('   okrManutencao direto:', await okrManutencao())

  console.log('# relatorio')
  await admin('PUT', '/edu/core/instituicao', { nome: 'Instituto <b>QA</b> & Cia', reitorNome: 'Dra. Reitora' })
  const rh = await admin('GET', R + '/relatorio/executivo'); check('relatorio html', rh.status === 200 && rh.text.includes('<!doctype html>') && rh.text.includes('Instituto &lt;b&gt;QA&lt;/b&gt; &amp; Cia') && !rh.text.includes('<b>QA</b>'), rh.text.slice(0, 200))
  const rc = await admin('GET', R + '/relatorio/executivo?formato=csv'); check('relatorio csv', rc.status === 200 && rc.text.startsWith('categoria;chave') && rc.text.split('\n').length > 5, rc.text.slice(0, 200))
  check('relatorio json', (await admin('GET', R + '/relatorio/executivo?formato=json')).body.perfil === 'reitoria')
  check('relatorio coord', (await coord('GET', R + '/relatorio/executivo')).status === 200)
  check('relatorio student 403', (await student('GET', R + '/relatorio/executivo')).status === 403)
  check('relatorio perfil alheio 403', (await coord('GET', R + '/relatorio/executivo?perfil=reitoria')).status === 403)
  const rs = await admin('POST', R + '/relatorios', { perfil: 'reitoria', titulo: 'Rel maio' }); check('relatorio salvo', rs.status === 201, rs.body)
  check('relatorio salvo html', (await admin('GET', `${R}/relatorios/${rs.body.id}/html`)).text.includes('doctype'))
  check('relatorio salvo B 404', (await adminB('GET', `${R}/relatorios/${rs.body.id}`)).status === 404)
  check('relatorio salvo coord 403', (await coord('GET', `${R}/relatorios/${rs.body.id}`)).status === 403)
  check('relatorios lista', (await admin('GET', R + '/relatorios')).body.total === 1)
  check('relatorio perfil invalido 400', (await admin('POST', R + '/relatorios', { perfil: 'xx' })).status === 400)

  console.log('# assistente')
  const as1 = await admin('POST', R + '/assistente/perguntar', { pergunta: 'Como está a inadimplência?' }); check('assistente sem IA', as1.status === 200 && as1.body.modo === 'HEURISTICO' && as1.body.resposta.length > 20, as1.body)
  check('assistente cita indicadores', as1.body.indicadoresCitados.length > 0, as1.body.indicadoresCitados)
  check('assistente pergunta curta 400', (await admin('POST', R + '/assistente/perguntar', { pergunta: 'a' })).status === 400)
  check('assistente student 403', (await student('POST', R + '/assistente/perguntar', { pergunta: 'Como estamos?' })).status === 403)
  check('assistente coord perfil reitoria 403', (await coord('POST', R + '/assistente/perguntar', { pergunta: 'Como estamos?', perfil: 'reitoria' })).status === 403)
  check('assistente teacher', (await teacher('POST', R + '/assistente/perguntar', { pergunta: 'Quais minhas turmas em risco?' })).status === 200)
  check('briefing', (await admin('GET', R + '/assistente/briefing')).status === 200)
  check('briefing cache', (await admin('GET', R + '/assistente/briefing')).status === 200)
  check('historico', (await admin('GET', R + '/assistente/historico?meu=true')).body.total >= 2)
  check('historico coord 403', (await coord('GET', R + '/assistente/historico')).status === 403)
  let lim = 0; for (let i = 0; i < 14; i++) { const r = await rector('POST', R + '/assistente/perguntar', { pergunta: 'Pergunta ' + i }); if (r.status === 429) lim++ }
  check('rate limit 429', lim >= 1, lim)

  console.log('# jobs')
  const jobs: any = await runEduJobs()
  console.log('   ', Object.entries(jobs).filter(([k]) => k.startsWith('reitoria')).map(([k, v]: any) => k + '=' + JSON.stringify(v.ok ? v.result : v.error)).join(' '))
  check('jobs ok', Object.values(jobs).every((v: any) => v.ok), Object.entries(jobs).filter(([, v]: any) => !v.ok))
  await finish(c)
}
main().catch((e) => { console.error(e); process.exit(2) })
