import { prisma } from '../../src/lib/prisma'
import { setup, check, summary } from './qa4-lib'

async function main() {
  const c = await setup()
  const { call, tenantId } = c
  const iso = (d: number) => new Date(Date.now() + d * 86400000).toISOString()

  console.log('# bootstrap / RBAC')
  let r = await call('SUPPLIES', 'POST', '/edu/suprimentos/bootstrap', {})
  check(r.status === 200, 'bootstrap 200', r)
  const r2 = await call('SUPPLIES', 'POST', '/edu/suprimentos/bootstrap', {})
  check(r2.status === 200 && r2.json.criados.itens === 0, 'bootstrap idempotente', r2)
  check((await call('TEACHER', 'POST', '/edu/suprimentos/bootstrap', {})).status === 403, 'teacher bootstrap 403')
  check((await call('STUDENT', 'GET', '/edu/suprimentos/itens')).status === 403 || true, 'student itens (readAll)')
  check((await call('TEACHER', 'POST', '/edu/suprimentos/almoxarifados', { codigo: 'X', nome: 'xx' })).status === 403, 'teacher create almox 403')

  const itens = (await call('SUPPLIES', 'GET', '/edu/suprimentos/itens?pageSize=100')).json.items
  const itemOf = (cod: string) => itens.find((i: any) => i.codigo === cod)
  const almCentral = (await call('SUPPLIES', 'GET', '/edu/suprimentos/almoxarifados')).json.items.find((a: any) => a.codigo === 'CENTRAL')
  const almLab = (await call('SUPPLIES', 'GET', '/edu/suprimentos/almoxarifados')).json.items.find((a: any) => a.codigo === 'LAB')
  check(!!almCentral && itens.length >= 9, 'catálogo bootstrap', { n: itens.length })

  console.log('# tenant 2 isolation of catalog')
  await call('SUPPLIES', 'POST', '/edu/suprimentos/bootstrap', {}, true)
  const t2itens = (await call('SUPPLIES', 'GET', '/edu/suprimentos/itens?pageSize=100', undefined, true)).json.items
  check(!t2itens.some((i: any) => itens.some((x: any) => x.id === i.id)), 'itens isolados por tenant')
  check((await call('SUPPLIES', 'GET', `/edu/suprimentos/itens/${itens[0].id}`, undefined, true)).status === 404, 'item de outro tenant 404')

  console.log('# fornecedores')
  check((await call('SUPPLIES', 'POST', '/edu/suprimentos/fornecedores', { razaoSocial: 'Bad', cnpj: '123' })).status === 400, 'cnpj inválido 400')
  const forn: any[] = []
  for (let i = 1; i <= 3; i++) {
    const f = await call('SUPPLIES', 'POST', '/edu/suprimentos/fornecedores', { razaoSocial: `Fornecedor ${i}`, cnpj: `1234567800019${i}`, prazoPagamentoDias: 30 })
    check(f.status === 201, 'criar fornecedor ' + i, f)
    forn.push(f.json)
  }
  const dupf = await call('SUPPLIES', 'POST', '/edu/suprimentos/fornecedores', { razaoSocial: 'Fornecedor 1 dup', cnpj: '12.345.678/0001-91' })
  console.log('  dup cnpj ->', dupf.status)
  const doc = await call('SUPPLIES', 'POST', '/edu/suprimentos/fornecedor-documentos', { fornecedorId: forn[0].id, tipo: 'CND Federal', validade: iso(-5) })
  check(doc.status === 201 && doc.json.status === 'VENCIDO', 'doc vencido', doc)
  check((await call('SUPPLIES', 'POST', '/edu/suprimentos/fornecedor-documentos', { fornecedorId: 'nope', tipo: 'CND' })).status === 404, 'doc forn inexistente 404')
  const av = await call('FINANCE', 'POST', '/edu/suprimentos/fornecedores/avaliacoes', { fornecedorId: forn[1].id, notaPrazo: 5, notaQualidade: 4, notaPreco: 3 })
  check(av.status === 201, 'avaliação', av)
  check((await call('FINANCE', 'POST', '/edu/suprimentos/fornecedores/avaliacoes', { fornecedorId: forn[1].id, notaPrazo: 9, notaQualidade: 4, notaPreco: 3 })).status === 400, 'nota 9 -> 400')

  console.log('# requisição -> aprovação por alçada')
  const cc = await prisma.eduCostCenter.create({ data: { tenantId, nome: 'CC QA' } })
  const toner = itemOf('TI-TONER'), a4 = itemOf('ESC-A4')
  const reqBody = { cursoId: undefined, centroCustoId: cc.id, justificativa: 'teste', itens: [{ itemId: toner.id, quantidade: 10 }, { itemId: a4.id, quantidade: 100 }] }
  check((await call('TEACHER', 'POST', '/edu/suprimentos/requisicoes', { itens: reqBody.itens })).status === 400, 'req sem origem 400')
  check((await call('TEACHER', 'POST', '/edu/suprimentos/requisicoes', { ...reqBody, itens: [] })).status === 400, 'req sem itens 400')
  check((await call('TEACHER', 'POST', '/edu/suprimentos/requisicoes', { ...reqBody, centroCustoId: 'zz' })).status === 404, 'req cc inexistente 404')
  check((await call('STUDENT', 'POST', '/edu/suprimentos/requisicoes', reqBody)).status === 403, 'aluno não cria req')
  const rq = await call('TEACHER', 'POST', '/edu/suprimentos/requisicoes', reqBody)
  check(rq.status === 201 && rq.json.valorEstimado > 5000, 'criar req valor ~5590', rq)
  const rid = rq.json.id
  // concorrência de numeração
  const nums = await Promise.all(Array.from({ length: 8 }, () => call('TEACHER', 'POST', '/edu/suprimentos/requisicoes', { ...reqBody, itens: [{ itemId: a4.id, quantidade: 1 }] })))
  check(nums.every((x) => x.status === 201) && new Set(nums.map((x) => x.json?.numero)).size === 8, 'numeração concorrente REQ única', nums.map((x) => x.status + ':' + x.json?.numero))
  check((await call('TEACHER', 'POST', `/edu/suprimentos/requisicoes/${rid}/decidir`, { decisao: 'APROVADO' })).status === 403, 'teacher não decide')
  check((await call('COORDINATOR', 'POST', `/edu/suprimentos/requisicoes/${rid}/decidir`, { decisao: 'APROVADO' })).status === 409, 'decidir rascunho 409')
  check((await call('TEACHER2' as any, 'GET', `/edu/suprimentos/requisicoes/${rid}`)).status === 401, 'sem token 401')
  check((await call('SUPPLIES', 'POST', `/edu/suprimentos/requisicoes/${rid}/enviar`, {})).status === 200, 'enviar (SUPPLIES)')
  check((await call('TEACHER', 'POST', `/edu/suprimentos/requisicoes/${rid}/enviar`, {})).status === 409, 'reenviar 409')
  let g = (await call('TEACHER', 'GET', `/edu/suprimentos/requisicoes/${rid}`)).json
  check(g.aprovacoes.length === 2 && g.status === 'AGUARDANDO_APROVACAO', 'cadeia 2 níveis (valor 5590)', g.aprovacoes)
  check((await call('FINANCE', 'POST', `/edu/suprimentos/requisicoes/${rid}/decidir`, { decisao: 'APROVADO' })).status === 403, 'financeiro não pode decidir nível 1')
  check((await call('COORDINATOR', 'POST', `/edu/suprimentos/requisicoes/${rid}/decidir`, { decisao: 'REPROVADO' })).status === 400, 'reprovar sem parecer 400')
  r = await call('COORDINATOR', 'POST', `/edu/suprimentos/requisicoes/${rid}/decidir`, { decisao: 'APROVADO' })
  check(r.status === 200 && r.json.status === 'AGUARDANDO_APROVACAO', 'nível 1 aprovado, segue', r)
  r = await call('FINANCE', 'POST', `/edu/suprimentos/requisicoes/${rid}/decidir`, { decisao: 'APROVADO' })
  check(r.status === 200 && r.json.status === 'APROVADA', 'nível 2 aprovado => APROVADA', r)
  check((await call('FINANCE', 'POST', `/edu/suprimentos/requisicoes/${rid}/decidir`, { decisao: 'APROVADO' })).status === 409, 'decidir de novo 409')
  const notif = await prisma.eduNotification.count({ where: { tenantId, refType: 'SupRequisicao', refId: rid } })
  check(notif >= 1, 'notificação ao solicitante', notif)
  check((await call('SUPPLIES', 'GET', `/edu/suprimentos/requisicoes/${rid}`, undefined, true)).status === 404, 'req outro tenant 404')

  // reprovação -> reabrir -> rascunho
  const rq2 = (await call('TEACHER', 'POST', '/edu/suprimentos/requisicoes', { ...reqBody, itens: [{ itemId: a4.id, quantidade: 5 }] })).json
  await call('TEACHER', 'POST', `/edu/suprimentos/requisicoes/${rq2.id}/enviar`, {})
  r = await call('COORDINATOR', 'POST', `/edu/suprimentos/requisicoes/${rq2.id}/decidir`, { decisao: 'REPROVADO', parecer: 'sem verba' })
  check(r.status === 200 && r.json.status === 'REPROVADA', 'reprovada', r)
  check((await call('TEACHER', 'POST', `/edu/suprimentos/requisicoes/${rq2.id}/reabrir`, {})).status === 200, 'reabrir')
  check((await call('TEACHER', 'PUT', `/edu/suprimentos/requisicoes/${rq2.id}`, { justificativa: 'ajustada', itens: [{ itemId: a4.id, quantidade: 7 }] })).status === 200, 'editar rascunho')
  check((await call('TEACHER', 'POST', `/edu/suprimentos/requisicoes/${rq2.id}/cancelar`, {})).status === 200, 'cancelar')
  check((await call('TEACHER', 'POST', `/edu/suprimentos/requisicoes/${rq2.id}/cancelar`, {})).status === 409, 'cancelar de novo 409')

  console.log('# cotação')
  const cot0 = await call('SUPPLIES', 'POST', `/edu/suprimentos/requisicoes/${rq2.id}/cotacoes`, { fornecedorIds: [forn[0].id] })
  check(cot0.status === 409, 'cotar req cancelada 409', cot0)
  check((await call('SUPPLIES', 'POST', `/edu/suprimentos/requisicoes/${rid}/cotacoes`, { fornecedorIds: [forn[0].id, 'nope'] })).status === 400, 'cotação c/ fornecedor inexistente 400')
  const cot = await call('SUPPLIES', 'POST', `/edu/suprimentos/requisicoes/${rid}/cotacoes`, { fornecedorIds: forn.map((f) => f.id), prazoResposta: iso(3) })
  check(cot.status === 201, 'abrir cotação', cot)
  const cid = cot.json.id
  const reqFull = (await call('SUPPLIES', 'GET', `/edu/suprimentos/requisicoes/${rid}`)).json
  const [i1, i2] = reqFull.itens
  check((await call('SUPPLIES', 'POST', `/edu/suprimentos/cotacoes/${cid}/encerrar`, {})).status === 409, 'encerrar sem propostas 409')
  const price = (f: number) => [{ requisicaoItemId: i1.id, precoUnitario: 10 * f }, { requisicaoItemId: i2.id, precoUnitario: 1 * f }]
  check((await call('SUPPLIES', 'PUT', `/edu/suprimentos/cotacoes/${cid}/propostas/${forn[0].id}`, { frete: 10, prazoEntregaDias: 5, precos: price(30) })).status === 200, 'proposta 1')
  check((await call('SUPPLIES', 'PUT', `/edu/suprimentos/cotacoes/${cid}/propostas/${forn[1].id}`, { frete: 0, prazoEntregaDias: 10, precos: price(25) })).status === 200, 'proposta 2')
  check((await call('SUPPLIES', 'PUT', `/edu/suprimentos/cotacoes/${cid}/propostas/${forn[2].id}`, { frete: 0, precos: [{ requisicaoItemId: i1.id, precoUnitario: 5 }] })).status === 200, 'proposta 3 parcial')
  check((await call('SUPPLIES', 'PUT', `/edu/suprimentos/cotacoes/${cid}/propostas/${forn[2].id}`, { precos: [{ requisicaoItemId: 'xx', precoUnitario: 5 }] })).status === 400, 'preço item inválido 400')
  const mapa = await call('SUPPLIES', 'GET', `/edu/suprimentos/cotacoes/${cid}/mapa`)
  check(mapa.status === 200 && mapa.json.vencedor === forn[1].id, 'mapa vencedor = f2', mapa.json)
  check((await call('SUPPLIES', 'POST', `/edu/suprimentos/cotacoes/${cid}/encerrar`, { fornecedorId: forn[0].id })).status === 400, 'outro fornecedor sem justificativa 400')
  check((await call('SUPPLIES', 'POST', `/edu/suprimentos/cotacoes/${cid}/encerrar`, { fornecedorId: forn[2].id, justificativa: 'x' })).status === 400, 'parcial não pode ganhar')
  check((await call('SUPPLIES', 'POST', `/edu/suprimentos/cotacoes/${cid}/gerar-pedido`, {})).status === 409, 'pedido antes de encerrar 409')
  r = await call('SUPPLIES', 'POST', `/edu/suprimentos/cotacoes/${cid}/encerrar`, {})
  check(r.status === 200 && r.json.fornecedorVencedorId === forn[1].id, 'encerrar', r)
  check((await call('SUPPLIES', 'PUT', `/edu/suprimentos/cotacoes/${cid}/propostas/${forn[0].id}`, { precos: price(1) })).status === 409, 'editar proposta após encerrar 409')
  check((await call('SUPPLIES', 'POST', `/edu/suprimentos/cotacoes/${cid}/gerar-pedido`, {})).status === 400, 'pedido sem almox 400')
  r = await call('SUPPLIES', 'POST', `/edu/suprimentos/cotacoes/${cid}/gerar-pedido`, { almoxarifadoId: almCentral.id, parcelas: 3 })
  check(r.status === 201, 'gerar pedido', r)
  const ped = r.json
  check((await call('SUPPLIES', 'POST', `/edu/suprimentos/cotacoes/${cid}/gerar-pedido`, { almoxarifadoId: almCentral.id })).status === 409, 'gerar pedido duplicado 409')

  console.log('# pedido -> recebimento -> estoque -> contas a pagar')
  check((await call('SUPPLIES', 'POST', `/edu/suprimentos/pedidos/${ped.id}/receber`, { itens: [{ pedidoItemId: ped.itens[0].id, quantidadeRecebida: 1 }] })).status === 409, 'receber antes de emitir 409')
  r = await call('SUPPLIES', 'POST', `/edu/suprimentos/pedidos/${ped.id}/emitir`, {})
  check(r.status === 200, 'emitir', r)
  check((await call('SUPPLIES', 'POST', `/edu/suprimentos/pedidos/${ped.id}/emitir`, {})).status === 409, 'emitir de novo 409')
  const pi = ped.itens
  check((await call('SUPPLIES', 'POST', `/edu/suprimentos/pedidos/${ped.id}/receber`, { itens: [{ pedidoItemId: pi[0].id, quantidadeRecebida: 999 }] })).status === 409, 'receber a mais 409')
  check((await call('SUPPLIES', 'POST', `/edu/suprimentos/pedidos/${ped.id}/receber`, { itens: [{ pedidoItemId: pi[0].id, quantidadeRecebida: 0 }] })).status === 400, 'receber zero 400')
  check((await call('SUPPLIES', 'POST', `/edu/suprimentos/pedidos/${ped.id}/receber`, { itens: [{ pedidoItemId: pi[0].id, quantidadeRecebida: 1, quantidadeRejeitada: 1 }] })).status === 400, 'rejeição sem motivo 400')
  const saldoToner0 = await prisma.supSaldo.findFirst({ where: { itemId: toner.id, almoxarifadoId: almCentral.id } })
  r = await call('SUPPLIES', 'POST', `/edu/suprimentos/pedidos/${ped.id}/receber`, { notaFiscal: 'NF1', itens: [{ pedidoItemId: pi[0].id, quantidadeRecebida: 4 }] })
  check(r.status === 201 && r.json.statusPedido === 'PARCIALMENTE_RECEBIDO', 'recebimento parcial', r)
  check(r.json.contasPagarIds?.length === 3, '3 parcelas AP', r.json)
  const sT = await prisma.supSaldo.findFirst({ where: { itemId: toner.id, almoxarifadoId: almCentral.id } })
  check(sT?.quantidade === 4, 'saldo toner 4', sT)
  // concorrência no mesmo pedido (over-receive)
  const rest = 10 - 4
  const conc = await Promise.all([1, 2, 3].map(() => call('SUPPLIES', 'POST', `/edu/suprimentos/pedidos/${ped.id}/receber`, { itens: [{ pedidoItemId: pi[0].id, quantidadeRecebida: rest }], gerarContasPagar: false })))
  const okN = conc.filter((x) => x.status === 201).length
  const sT2 = await prisma.supSaldo.findFirst({ where: { itemId: toner.id, almoxarifadoId: almCentral.id } })
  check(okN === 1 && sT2?.quantidade === 10, 'receber concorrente: só 1 vence, saldo 10', { sts: conc.map((x) => x.status), saldo: sT2?.quantidade })
  r = await call('SUPPLIES', 'POST', `/edu/suprimentos/pedidos/${ped.id}/receber`, { itens: [{ pedidoItemId: pi[1].id, quantidadeRecebida: 100 }] })
  check(r.status === 201 && r.json.statusPedido === 'RECEBIDO', 'recebimento final', r)
  const rqAfter = (await call('SUPPLIES', 'GET', `/edu/suprimentos/requisicoes/${rid}`)).json
  check(rqAfter.status === 'ATENDIDA', 'req ATENDIDA', rqAfter.status)
  const aps = await prisma.accountPayable.findMany({ where: { tenantId, descricao: { contains: ped.numero } } })
  const somaAp = aps.reduce((s, a) => s + a.valor, 0)
  console.log('  AP total', somaAp, 'n', aps.length)
  check(aps.length >= 3 && aps.every((a) => a.costCenterId === cc.id), 'AP com centro de custo')
  check((await call('SUPPLIES', 'POST', `/edu/suprimentos/pedidos/${ped.id}/cancelar`, {})).status === 409, 'cancelar recebido 409')
  const movs = await prisma.supMovimentacao.findMany({ where: { tenantId, itemId: toner.id } })
  check(movs.reduce((s, m) => s + m.sentido * m.quantidade, 0) === 10, 'soma movimentações = saldo')

  console.log('# lote/validade')
  const luva = itemOf('EPI-LUVA-M')
  const mv = (b: any) => call('SUPPLIES', 'POST', '/edu/suprimentos/estoque/movimentacoes', b)
  check((await mv({ tipo: 'ENTRADA', itemId: luva.id, almoxarifadoId: almCentral.id, quantidade: 10, custoUnitario: 40 })).status === 400, 'lote obrigatório 400')
  check((await mv({ tipo: 'ENTRADA', itemId: luva.id, almoxarifadoId: almCentral.id, quantidade: 10, custoUnitario: 40, loteNumero: 'L1' })).status === 400, 'validade obrigatória 400')
  r = await mv({ tipo: 'ENTRADA', itemId: luva.id, almoxarifadoId: almCentral.id, quantidade: 30, custoUnitario: 40, loteNumero: 'L1', validade: iso(90) })
  check(r.status === 201, 'entrada L1', r)
  r = await mv({ tipo: 'ENTRADA', itemId: luva.id, almoxarifadoId: almCentral.id, quantidade: 20, custoUnitario: 50, loteNumero: 'L2', validade: iso(30) })
  check(r.status === 201, 'entrada L2', r)
  r = await mv({ tipo: 'SAIDA', itemId: luva.id, almoxarifadoId: almCentral.id, quantidade: 25 })
  check(r.status === 201 && r.json[0].loteNumero === 'L2', 'FEFO consome L2 primeiro', r.json)
  const lotes = await prisma.supLote.findMany({ where: { itemId: luva.id, almoxarifadoId: almCentral.id } })
  check(lotes.find((l) => l.numero === 'L2')?.quantidade === 0 && lotes.find((l) => l.numero === 'L1')?.quantidade === 25, 'lotes após FEFO', lotes.map((l) => [l.numero, l.quantidade]))
  check((await mv({ tipo: 'SAIDA', itemId: luva.id, almoxarifadoId: almCentral.id, quantidade: 999 })).status === 409, 'saída maior que saldo 409')
  check((await mv({ tipo: 'AJUSTE', itemId: luva.id, almoxarifadoId: almCentral.id, quantidade: 1, sentido: 1, motivo: 'contagem' })).status === 201, 'ajuste + em item com lote (sem lote informado)')
  check((await mv({ tipo: 'AJUSTE', itemId: luva.id, almoxarifadoId: almCentral.id, quantidade: 1 })).status === 400, 'ajuste sem motivo 400')
  check((await mv({ tipo: 'SAIDA', itemId: luva.id, almoxarifadoId: almCentral.id, quantidade: 0 })).status === 400, 'qtd zero 400')
  check((await mv({ tipo: 'TRANSFERENCIA', itemId: luva.id, almoxarifadoId: almCentral.id, quantidade: 5 })).status === 400, 'transferência sem destino 400')
  r = await mv({ tipo: 'TRANSFERENCIA', itemId: luva.id, almoxarifadoId: almCentral.id, almoxarifadoDestinoId: almLab.id, quantidade: 5, motivo: 'lab' })
  check(r.status === 201, 'transferência', r)
  const sA = await prisma.supSaldo.findFirst({ where: { itemId: luva.id, almoxarifadoId: almCentral.id } })
  const sB = await prisma.supSaldo.findFirst({ where: { itemId: luva.id, almoxarifadoId: almLab.id } })
  check(sA?.quantidade === 21 && sB?.quantidade === 5, 'saldos pós-transferência', [sA?.quantidade, sB?.quantidade])
  check((await mv({ tipo: 'ENTRADA', itemId: 'nope', almoxarifadoId: almCentral.id, quantidade: 1, custoUnitario: 1 })).status === 404, 'item inexistente 404')

  console.log('# concorrência de saldo')
  const caneta = itemOf('ESC-CANETA')
  await mv({ tipo: 'ENTRADA', itemId: caneta.id, almoxarifadoId: almCentral.id, quantidade: 100, custoUnitario: 1 })
  const N = 20
  const res = await Promise.all(Array.from({ length: N }, () => mv({ tipo: 'SAIDA', itemId: caneta.id, almoxarifadoId: almCentral.id, quantidade: 5 })))
  const ok = res.filter((x) => x.status === 201).length
  const bad = res.filter((x) => x.status !== 201 && x.status !== 409).length
  const sC = await prisma.supSaldo.findFirst({ where: { itemId: caneta.id, almoxarifadoId: almCentral.id } })
  const sumMov = (await prisma.supMovimentacao.findMany({ where: { itemId: caneta.id } })).reduce((s, m) => s + m.sentido * m.quantidade, 0)
  console.log('  saídas ok', ok, 'status', res.map((x) => x.status).join(','), 'saldo', sC?.quantidade)
  check(bad === 0 && sC?.quantidade === 100 - 5 * ok && sumMov === sC?.quantidade && sC.quantidade >= 0, 'saldo consistente sob concorrência', { ok, saldo: sC?.quantidade, sumMov })
  check(ok === N, 'concorrência: todas as 20 saídas (20x5=100) deveriam passar com retry', { ok })
  // concorrência no primeiro registro de saldo (item sem saldo)
  const lamina = itemOf('LAB-LAMINA')
  const res2 = await Promise.all(Array.from({ length: 6 }, () => mv({ tipo: 'ENTRADA', itemId: lamina.id, almoxarifadoId: almCentral.id, quantidade: 2, custoUnitario: 3 })))
  const sL = await prisma.supSaldo.findMany({ where: { itemId: lamina.id, almoxarifadoId: almCentral.id } })
  check(sL.length === 1 && sL[0].quantidade === 2 * res2.filter((x) => x.status === 201).length && res2.every((x) => x.status === 201), 'entradas concorrentes em saldo novo', { sts: res2.map((x) => x.status), saldo: sL.map((x) => x.quantidade) })

  console.log('# estoque mínimo / lembrete / reposição')
  const sJ = itemOf('EPI-JALECO')
  await mv({ tipo: 'ENTRADA', itemId: sJ.id, almoxarifadoId: almCentral.id, quantidade: 5, custoUnitario: 70 })
  const rem = await prisma.eduReminder.findFirst({ where: { tenantId, dedupeKey: `sup-minimo-${sJ.id}` } })
  check(!!rem && rem.status === 'PENDENTE', 'lembrete estoque mínimo', rem)
  await mv({ tipo: 'ENTRADA', itemId: sJ.id, almoxarifadoId: almCentral.id, quantidade: 100, custoUnitario: 70 })
  check((await prisma.eduReminder.findFirst({ where: { tenantId, dedupeKey: `sup-minimo-${sJ.id}` } })) == null, 'lembrete some ao repor')
  await mv({ tipo: 'SAIDA', itemId: sJ.id, almoxarifadoId: almCentral.id, quantidade: 100 })
  const rem2 = await prisma.eduReminder.findFirst({ where: { tenantId, dedupeKey: `sup-minimo-${sJ.id}` } })
  check(rem2?.status === 'PENDENTE', 'lembrete reabre ao cair de novo abaixo do mínimo', rem2)
  const repo = await call('SUPPLIES', 'GET', '/edu/suprimentos/estoque/reposicao')
  check(repo.status === 200 && Array.isArray(repo.json) && repo.json.length > 0, 'reposição sugere', repo)
  r = await call('SUPPLIES', 'POST', '/edu/suprimentos/estoque/reposicao/gerar-requisicao', { centroCustoId: cc.id, almoxarifadoId: almCentral.id })
  check(r.status === 201, 'gerar requisição de reposição', r)
  check((await call('SUPPLIES', 'GET', '/edu/suprimentos/estoque/curva-abc')).status === 200, 'curva abc')
  check((await call('SUPPLIES', 'GET', '/edu/suprimentos/estoque/consumo?por=centroCustoId')).status === 200, 'consumo')

  console.log('# atendimento de insumo por estoque')
  const rI = await call('TEACHER', 'POST', '/edu/suprimentos/requisicoes', { tipo: 'INSUMO', almoxarifadoId: almCentral.id, centroCustoId: cc.id, itens: [{ itemId: caneta.id, quantidade: 5 }, { itemId: sJ.id, quantidade: 3 }] })
  check(rI.status === 201, 'req insumo', rI)
  await call('TEACHER', 'POST', `/edu/suprimentos/requisicoes/${rI.json.id}/enviar`, {})
  await call('COORDINATOR', 'POST', `/edu/suprimentos/requisicoes/${rI.json.id}/decidir`, { decisao: 'APROVADO' })
  let g2 = (await call('TEACHER', 'GET', `/edu/suprimentos/requisicoes/${rI.json.id}`)).json
  check(g2.status === 'APROVADA', 'insumo aprovada', g2.status)
  r = await call('SUPPLIES', 'POST', `/edu/suprimentos/requisicoes/${rI.json.id}/atender-estoque`, {})
  check(r.status === 409, 'atender sem saldo de caneta (0) 409', r)
  await mv({ tipo: 'ENTRADA', itemId: caneta.id, almoxarifadoId: almCentral.id, quantidade: 10, custoUnitario: 1 })
  r = await call('SUPPLIES', 'POST', `/edu/suprimentos/requisicoes/${rI.json.id}/atender-estoque`, {})
  check(r.status === 200 && r.json.atendida === true, 'atender estoque', r)
  check((await call('SUPPLIES', 'POST', `/edu/suprimentos/requisicoes/${rI.json.id}/atender-estoque`, {})).status === 409, 'atender de novo 409')

  console.log('# inventário')
  r = await call('SUPPLIES', 'POST', '/edu/suprimentos/inventarios', { almoxarifadoId: almCentral.id, tipo: 'GERAL' })
  check(r.status === 201, 'abrir inventário', r)
  const inv = r.json
  check((await call('SUPPLIES', 'POST', '/edu/suprimentos/inventarios', { almoxarifadoId: almCentral.id, tipo: 'GERAL' })).status === 409, 'segundo inventário 409')
  check((await call('SUPPLIES', 'POST', `/edu/suprimentos/inventarios/${inv.id}/finalizar`, {})).status === 409, 'finalizar sem contagem 409')
  await call('SUPPLIES', 'PUT', `/edu/suprimentos/inventarios/${inv.id}/contagem`, { itens: inv.itens.map((i: any) => ({ itemId: i.itemId, quantidadeContada: i.quantidadeSistema + 1 })) })
  check((await call('SUPPLIES', 'POST', `/edu/suprimentos/inventarios/${inv.id}/ajustar`, {})).status === 409, 'ajustar antes de finalizar 409')
  check((await call('SUPPLIES', 'POST', `/edu/suprimentos/inventarios/${inv.id}/finalizar`, {})).status === 200, 'finalizar')
  r = await call('SUPPLIES', 'POST', `/edu/suprimentos/inventarios/${inv.id}/ajustar`, {})
  check(r.status === 200, 'ajustar inventário (inclui itens com lote)', r)

  console.log('# contratos')
  r = await call('SUPPLIES', 'POST', '/edu/suprimentos/contratos', { numero: 'C-1', fornecedorId: forn[0].id, objeto: 'Limpeza', vigenciaInicio: iso(-300), vigenciaFim: iso(30), valorMensal: 1000, valorTotal: 12000 })
  check(r.status === 201 && r.json.status === 'A_VENCER', 'contrato A_VENCER', r)
  const ct = r.json
  check((await call('SUPPLIES', 'POST', '/edu/suprimentos/contratos', { numero: 'C-2', fornecedorId: forn[0].id, objeto: 'Limpeza', vigenciaInicio: iso(10), vigenciaFim: iso(5) })).status === 400, 'vigência invertida 400')
  r = await call('SUPPLIES', 'POST', `/edu/suprimentos/contratos/${ct.id}/reajustar`, { percentual: 10 })
  check(r.status === 200 && r.json.valorMensal === 1100, 'reajuste', r)
  r = await call('SUPPLIES', 'POST', `/edu/suprimentos/contratos/${ct.id}/renovar`, { meses: 12 })
  check(r.status === 201, 'renovar', r)
  check((await call('SUPPLIES', 'POST', `/edu/suprimentos/contratos/${ct.id}/renovar`, {})).status === 409, 'renovar renovado 409')

  console.log('# vendas / PDV')
  await mv({ tipo: 'ENTRADA', itemId: caneta.id, almoxarifadoId: almCentral.id, quantidade: 100, custoUnitario: 1 })
  const prodBody = (it: any, nome: string, preco: number, extra: any = {}) => ({ itemId: it.id, almoxarifadoId: almCentral.id, nome, preco, ...extra })
  check((await call('SUPPLIES', 'POST', '/edu/suprimentos/produtos', prodBody({ id: 'zz' }, 'Bad', 1))).status === 404, 'produto item inexistente 404')
  const pCaneta = (await call('SUPPLIES', 'POST', '/edu/suprimentos/produtos', prodBody(caneta, 'Caneta Azul', 3, { permiteLancarAluno: true }))).json
  const pLuva = (await call('SUPPLIES', 'POST', '/edu/suprimentos/produtos', prodBody(luva, 'Luva', 60, { permiteLancarAluno: false }))).json
  check(!!pCaneta?.id && !!pLuva?.id, 'produtos criados', [pCaneta, pLuva])
  check((await call('STAFF', 'POST', '/edu/suprimentos/vendas', { formaPagamento: 'PIX', itens: [{ produtoId: pCaneta.id, quantidade: 1 }] })).status === 409, 'vender sem caixa 409')
  r = await call('STAFF', 'POST', '/edu/suprimentos/caixa/abrir', { valorAbertura: 100 })
  check(r.status === 201, 'abrir caixa', r)
  const caixa = r.json
  check((await call('STAFF', 'POST', '/edu/suprimentos/caixa/abrir', {})).status === 409, 'caixa duplicado 409')
  check((await call('STAFF', 'POST', '/edu/suprimentos/vendas', { itens: [{ produtoId: pCaneta.id, quantidade: 1 }] })).status === 400, 'sem forma de pagamento 400')
  const sC0 = (await prisma.supSaldo.findFirst({ where: { itemId: caneta.id, almoxarifadoId: almCentral.id } }))!.quantidade
  r = await call('STAFF', 'POST', '/edu/suprimentos/vendas', { formaPagamento: 'DINHEIRO', desconto: 1, itens: [{ produtoId: pCaneta.id, quantidade: 4 }, { produtoId: pLuva.id, quantidade: 2 }] })
  check(r.status === 201 && r.json.total === 131, 'venda à vista total 131', r)
  const venda = r.json
  const sC1 = (await prisma.supSaldo.findFirst({ where: { itemId: caneta.id, almoxarifadoId: almCentral.id } }))!.quantidade
  check(sC0 - sC1 === 4, 'baixa de estoque da venda', [sC0, sC1])
  check((await call('STAFF', 'POST', '/edu/suprimentos/vendas', { formaPagamento: 'PIX', itens: [{ produtoId: pCaneta.id, quantidade: 99999 }] })).status === 409, 'venda sem estoque 409')
  const sC2 = (await prisma.supSaldo.findFirst({ where: { itemId: caneta.id, almoxarifadoId: almCentral.id } }))!.quantidade
  check(sC2 === sC1, 'venda falha não altera saldo')
  check((await call('STAFF', 'POST', '/edu/suprimentos/vendas', { formaPagamento: 'PIX', desconto: 5000, itens: [{ produtoId: pCaneta.id, quantidade: 1 }] })).status === 400, 'desconto > subtotal 400')
  // aluno
  const stUser = c.users.STUDENT
  let st = await prisma.student.findFirst({ where: { userId: stUser.id } })
  if (!st) st = await prisma.student.create({ data: { tenantId, userId: stUser.id, ra: 'RA-' + tenantId, nomeCompleto: 'Aluno QA' } })
  check((await call('STAFF', 'POST', '/edu/suprimentos/vendas', { tipo: 'LANCADA_ALUNO', itens: [{ produtoId: pCaneta.id, quantidade: 1 }] })).status === 400, 'lançada sem aluno 400')
  check((await call('STAFF', 'POST', '/edu/suprimentos/vendas', { tipo: 'LANCADA_ALUNO', studentId: st.id, itens: [{ produtoId: pLuva.id, quantidade: 1 }] })).status === 409, 'luva não lançável 409')
  check((await call('STAFF', 'POST', '/edu/suprimentos/vendas', { tipo: 'LANCADA_ALUNO', studentId: 'nope', itens: [{ produtoId: pCaneta.id, quantidade: 1 }] })).status === 404, 'aluno inexistente 404')
  r = await call('STAFF', 'POST', '/edu/suprimentos/vendas', { tipo: 'LANCADA_ALUNO', studentId: st.id, parcelas: 3, itens: [{ produtoId: pCaneta.id, quantidade: 10 }] })
  check(r.status === 201 && r.json.receivableIds.length === 3, 'venda lançada 3 parcelas AR', r)
  const vAluno = r.json
  const ars = await prisma.accountReceivable.findMany({ where: { id: { in: vAluno.receivableIds } } })
  check(Math.abs(ars.reduce((s, a) => s + a.valor, 0) - 30) < 0.001 && ars.every((a) => a.studentId === st!.id), 'AR soma 30', ars.map((a) => a.valor))
  // devolução
  check((await call('STAFF', 'POST', `/edu/suprimentos/vendas/${vAluno.id}/devolucao`, { motivo: 'abc', itens: [{ vendaItemId: vAluno.itens[0].id, quantidade: 1 }] })).status === 403, 'operador não devolve')
  check((await call('SUPPLIES', 'POST', `/edu/suprimentos/vendas/${vAluno.id}/devolucao`, { motivo: 'abc', itens: [{ vendaItemId: vAluno.itens[0].id, quantidade: 11 }] })).status === 409, 'devolver a mais 409')
  r = await call('SUPPLIES', 'POST', `/edu/suprimentos/vendas/${vAluno.id}/devolucao`, { motivo: 'defeito', itens: [{ vendaItemId: vAluno.itens[0].id, quantidade: 4 }] })
  check(r.status === 201 && r.json.valorDevolvido === 12, 'devolução parcial 12', r)
  const ars2 = await prisma.accountReceivable.findMany({ where: { id: { in: vAluno.receivableIds } } })
  check(Math.abs(ars2.filter((a) => a.status !== 'CANCELADO').reduce((s, a) => s + a.valor, 0) - 18) < 0.001, 'AR abatido para 18', ars2.map((a) => [a.valor, a.status]))
  // devolução concorrente
  const dv = await Promise.all([1, 2, 3].map(() => call('SUPPLIES', 'POST', `/edu/suprimentos/vendas/${vAluno.id}/devolucao`, { motivo: 'concorrente', itens: [{ vendaItemId: vAluno.itens[0].id, quantidade: 6 }] })))
  const vi = await prisma.supVendaItem.findUnique({ where: { id: vAluno.itens[0].id } })
  check(dv.filter((x) => x.status === 201).length === 1 && vi?.quantidadeDevolvida === 10, 'devolução concorrente: só 1', { sts: dv.map((x) => x.status), q: vi?.quantidadeDevolvida })
  const vv = await prisma.supVenda.findUnique({ where: { id: vAluno.id } })
  check(vv?.status === 'DEVOLVIDA', 'venda DEVOLVIDA', vv?.status)
  const ars3 = await prisma.accountReceivable.findMany({ where: { id: { in: vAluno.receivableIds } } })
  check(ars3.every((a) => a.status === 'CANCELADO' || a.valor <= 0.001), 'todos AR cancelados após devolução total', ars3.map((a) => [a.valor, a.status]))
  // devolução de item com lote (luva)
  r = await call('SUPPLIES', 'POST', `/edu/suprimentos/vendas/${venda.id}/devolucao`, { motivo: 'cliente desistiu', itens: [{ vendaItemId: venda.itens.find((i: any) => i.itemId === luva.id).id, quantidade: 1 }] })
  check(r.status === 201, 'devolução de item que controla lote', r)
  // caixa
  r = await call('STAFF', 'GET', '/edu/suprimentos/caixa/atual')
  check(r.status === 200, 'caixa atual', r)
  console.log('  esperado em dinheiro:', r.json.dinheiroEsperado)
  check((await call('STAFF', 'POST', `/edu/suprimentos/caixa/${caixa.id}/movimento`, { tipo: 'SANGRIA', valor: 99999 })).status === 409, 'sangria excessiva 409')
  check((await call('STAFF', 'POST', `/edu/suprimentos/caixa/${caixa.id}/movimento`, { tipo: 'SUPRIMENTO', valor: 50 })).status === 201, 'suprimento')
  check((await call('SECRETARY', 'POST', `/edu/suprimentos/caixa/${caixa.id}/fechar`, { valorContado: 0 })).status === 404 || true, 'outro operador')
  check((await call('STAFF', 'POST', `/edu/suprimentos/caixa/${caixa.id}/fechar`, { valorContado: 1 })).status === 400, 'diferença sem observação 400')
  r = await call('STAFF', 'POST', `/edu/suprimentos/caixa/${caixa.id}/fechar`, { valorContado: 1, observacao: 'quebra' })
  check(r.status === 200, 'fechar caixa', r)
  check((await call('STAFF', 'POST', '/edu/suprimentos/vendas', { formaPagamento: 'PIX', itens: [{ produtoId: pCaneta.id, quantidade: 1 }] })).status === 409, 'vender com caixa fechado 409')
  check((await call('STAFF', 'GET', `/edu/suprimentos/vendas/${venda.id}/recibo`)).status === 200, 'recibo')
  check((await call('SUPPLIES', 'GET', `/edu/suprimentos/vendas/${venda.id}`, undefined, true)).status === 404, 'venda outro tenant 404')
  check((await call('SUPPLIES', 'GET', '/edu/suprimentos/vendas-relatorio')).status === 200, 'relatório vendas')

  console.log('# kits')
  r = await call('SUPPLIES', 'POST', '/edu/suprimentos/kits', { nome: 'Kit Aula', itens: [{ itemId: caneta.id, quantidadeFixa: 1, quantidadePorAluno: 2 }] })
  check(r.status === 201, 'kit', r)
  const kit = r.json
  check((await call('TEACHER', 'POST', `/edu/suprimentos/kits/${kit.id}/consumir`, { almoxarifadoId: almCentral.id })).status === 400, 'consumir sem alunos 400')
  r = await call('TEACHER', 'POST', `/edu/suprimentos/kits/${kit.id}/consumir`, { almoxarifadoId: almCentral.id, numeroAlunos: 5 })
  check(r.status === 201, 'consumir kit', r)
  r = await call('TEACHER', 'POST', `/edu/suprimentos/kits/${kit.id}/solicitar`, { almoxarifadoId: almCentral.id, numeroAlunos: 5, centroCustoId: cc.id })
  check(r.status === 201, 'solicitar kit', r)
  check((await call('TEACHER', 'GET', `/edu/suprimentos/kits/${kit.id}/disponibilidade?numeroAlunos=3`)).status === 200, 'disponibilidade')

  console.log('# jobs')
  const { runEduJobs } = await import('../../src/modules/core/jobs')
  const jr: any = await runEduJobs()
  for (const k of Object.keys(jr)) if (jr[k].ok === false) { console.log('  JOB FALHOU', k, jr[k].error); check(false, 'job ' + k, jr[k]) }
  console.log('  jobs sup:', Object.keys(jr).filter((k) => k.startsWith('suprimentos')).map((k) => k + '=' + JSON.stringify(jr[k].result)).join(' | '))

  summary()
  await c.close()
  process.exit(0)
}
main().catch((e) => { console.error(e); process.exit(2) })
