import { prisma } from '../../src/lib/prisma'
import { setup, check, summary, acadFixture, tokenCall } from './qa4-lib'

async function main() {
  const c = await setup()
  const { call, tenantId } = c
  const I = '/edu/infraestrutura'
  const iso = (d: number) => new Date(Date.now() + d * 86400000).toISOString()
  const fx = await acadFixture(c)

  console.log('# bootstrap/RBAC')
  let r = await call('FACILITIES', 'POST', `${I}/bootstrap`, {})
  check(r.status === 200 && r.json.criados.categorias >= 15, 'bootstrap', r)
  r = await call('FACILITIES', 'POST', `${I}/bootstrap`, {})
  check(r.status === 200 && r.json.criados.categorias === 0 && r.json.criados.regrasUso === 0, 'bootstrap idempotente', r.json)
  check((await call('TEACHER', 'POST', `${I}/bootstrap`, {})).status === 403, 'professor bootstrap 403')
  check((await call('STUDENT', 'GET', `${I}/bens`)).status === 403, 'aluno não lista bens')
  check((await call('TEACHER', 'POST', `${I}/bens`, {})).status === 403, 'professor não cadastra bem')

  const mkSpace = (codigo: string, tipo: string, extra: any = {}) => prisma.eduSpace.create({ data: { tenantId, codigo, nome: codigo, tipo: tipo as any, ...extra } })
  const salaA = await mkSpace('SALA-A', 'SALA_AULA', { areaM2: 50, capacidade: 40 })
  const salaB = await mkSpace('SALA-B', 'SALA_AULA', { areaM2: 60, capacidade: 40 })
  const lab = await mkSpace('LAB-1', 'LABORATORIO', { areaM2: 80, capacidade: 30 })
  const patio = await mkSpace('PATIO-1', 'PATIO', { capacidade: 200 })
  const salaOutro = await prisma.eduSpace.create({ data: { tenantId: c.tenant2, codigo: 'X', nome: 'X', tipo: 'SALA_AULA' } })

  console.log('# patrimônio')
  const cats = (await call('FACILITIES', 'GET', `${I}/categorias-bem?pageSize=100`)).json.items
  const catPC = cats.find((x: any) => x.codigo === 'COMPUTADOR'), catAr = cats.find((x: any) => x.codigo === 'AR-COND')
  check(!!catPC, 'categoria computador')
  const bemBody = { descricao: 'Notebook Dell', categoriaId: catPC.id, valorAquisicao: 6000, dataAquisicao: iso(-400), spaceId: salaA.id, garantiaAte: iso(100) }
  check((await call('FACILITIES', 'POST', `${I}/bens`, { ...bemBody, valorAquisicao: -1 })).status === 400, 'valor negativo 400')
  check((await call('FACILITIES', 'POST', `${I}/bens`, { ...bemBody, categoriaId: 'zz' })).status === 400, 'categoria inexistente 400')
  check((await call('FACILITIES', 'POST', `${I}/bens`, { ...bemBody, spaceId: salaOutro.id })).status === 400, 'espaço de outro tenant 400')
  check((await call('FACILITIES', 'POST', `${I}/bens`, { ...bemBody, dataAquisicao: iso(30) })).status === 400, 'aquisição futura 400')
  r = await call('FACILITIES', 'POST', `${I}/bens`, bemBody)
  check(r.status === 201 && /^PAT-\d{6}$/.test(r.json.tombamento) && r.json.depreciacao.mesesUsados >= 13, 'cadastrar bem + tombamento + depreciação', r.json)
  const bem = r.json
  console.log('  depreciação:', JSON.stringify(bem.depreciacao))
  check(bem.depreciacao.valorContabil < 6000 && bem.depreciacao.valorContabil > 5400 * 0 + 4000, 'valor contábil plausível', bem.depreciacao)
  // tombamentos concorrentes
  const cc = await Promise.all(Array.from({ length: 8 }, (_, i) => call('FACILITIES', 'POST', `${I}/bens`, { ...bemBody, descricao: 'Lote ' + i })))
  check(cc.every((x) => x.status === 201) && new Set(cc.map((x) => x.json.tombamento)).size === 8, 'tombamento concorrente único', cc.map((x) => x.status + ':' + (x.json?.tombamento ?? x.json?.error)))
  check((await call('FACILITIES', 'POST', `${I}/bens`, { ...bemBody, tombamento: bem.tombamento })).status === 409, 'tombamento duplicado 409')
  check((await call('FACILITIES', 'GET', `${I}/bens/${bem.id}`, undefined, true)).status === 404, 'bem outro tenant 404')
  check((await call('FACILITIES', 'POST', `${I}/bens/${bem.id}/transferir`, { motivo: 'abc' })).status === 400, 'transferir sem destino 400')
  check((await call('FACILITIES', 'POST', `${I}/bens/${bem.id}/transferir`, { spaceId: salaA.id, motivo: 'mesmo local' })).status === 400, 'transferir p/ mesmo local 400')
  r = await call('FACILITIES', 'POST', `${I}/bens/${bem.id}/transferir`, { spaceId: lab.id, motivo: 'mudança de sala' })
  check(r.status === 200 && r.json.spaceId === lab.id, 'transferir', r)
  check((await call('FACILITIES', 'POST', `${I}/bens/${bem.id}/estado`, { estado: 'RUIM', motivo: 'tela quebrada' })).status === 200, 'mudar estado')
  check((await call('FACILITIES', 'POST', `${I}/bens/${bem.id}/estado`, { estado: 'XXX' })).status === 400, 'estado inválido 400')
  r = await call('FACILITIES', 'GET', `${I}/bens/${bem.id}/depreciacao`)
  check(r.status === 200 && r.json.tabela.length > 10, 'tabela de depreciação', r.status)
  check((await call('FACILITIES', 'GET', `${I}/bens/${bem.id}/etiqueta`)).status === 200, 'etiqueta')
  check((await call('FACILITIES', 'POST', `${I}/etiquetas`, { spaceId: lab.id })).status === 200, 'etiquetas por local')
  check((await call('FACILITIES', 'GET', `${I}/relatorios/patrimonio`)).status === 200, 'relatório patrimônio')
  check((await call('FACILITIES', 'GET', `${I}/relatorios/patrimonio?format=html`)).status === 200, 'relatório patrimônio html')
  check((await call('FACILITIES', 'GET', `${I}/bens?categoriaId=${catPC.id}&estado=RUIM`)).json?.total === 1, 'filtro bens')
  check((await call('FACILITIES', 'GET', `${I}/bens/${bem.id}/depreciacao?data=lixo`)).status === 200, 'depreciação data inválida ignorada')

  console.log('# manutenção: OS e preventivo')
  check((await call('FACILITIES', 'POST', `${I}/ordens-servico`, { titulo: 'ab' })).status === 400, 'OS título curto 400')
  check((await call('FACILITIES', 'POST', `${I}/ordens-servico`, { titulo: 'Troca de tela', bemId: 'zz' })).status === 400, 'OS bem inexistente 400')
  r = await call('FACILITIES', 'POST', `${I}/ordens-servico`, { titulo: 'Troca de tela', bemId: bem.id, prioridade: 'ALTA', checklist: [{ item: 'Testar', obrigatorio: true }] })
  check(r.status === 201 && /^OS-\d{4}-\d{5}$/.test(r.json.numero) && r.json.bemParado === true, 'abrir OS corretiva', r.json)
  const os = r.json
  check((await prisma.infBem.findUnique({ where: { id: bem.id } }))?.status === 'EM_MANUTENCAO', 'bem EM_MANUTENCAO')
  const nums = await Promise.all(Array.from({ length: 6 }, () => call('FACILITIES', 'POST', `${I}/ordens-servico`, { titulo: 'OS concorrente', spaceId: salaA.id })))
  check(nums.every((x) => x.status === 201) && new Set(nums.map((x) => x.json.numero)).size === 6, 'numeração OS concorrente', nums.map((x) => x.status))
  check((await call('FACILITIES', 'POST', `${I}/ordens-servico/${os.id}/status`, { status: 'CONCLUIDA' })).status === 409, 'ABERTA->CONCLUIDA 409')
  check((await call('FACILITIES', 'POST', `${I}/ordens-servico/${os.id}/status`, { status: 'AGENDADA' })).status === 400, 'agendar sem data 400')
  check((await call('FACILITIES', 'POST', `${I}/ordens-servico/${os.id}/status`, { status: 'EM_EXECUCAO' })).status === 200, 'iniciar')
  r = await call('FACILITIES', 'POST', `${I}/ordens-servico/${os.id}/pecas`, { descricao: 'Tela 15"', quantidade: 1, valorUnitario: 800 })
  check(r.status === 201 && r.json.custoPecas === 800, 'adicionar peça', r.json)
  check((await call('FACILITIES', 'POST', `${I}/ordens-servico/${os.id}/status`, { status: 'CONCLUIDA', solucao: 'tela trocada' })).status === 409, 'concluir com checklist pendente 409')
  check((await call('FACILITIES', 'PATCH', `${I}/ordens-servico/${os.id}/checklist`, { itens: [{ item: 'Testar', feito: true }] })).status === 200, 'checklist')
  check((await call('FACILITIES', 'POST', `${I}/ordens-servico/${os.id}/status`, { status: 'CONCLUIDA' })).status === 400, 'concluir sem solução 400')
  r = await call('FACILITIES', 'POST', `${I}/ordens-servico/${os.id}/status`, { status: 'CONCLUIDA', solucao: 'tela trocada', custoMaoObra: 150 })
  check(r.status === 200 && r.json.custoTotal === 950 && r.json.sla === 'CUMPRIDO', 'concluir OS', r.json)
  check((await prisma.infBem.findUnique({ where: { id: bem.id } }))?.status === 'ATIVO', 'bem volta ATIVO')
  check((await call('FACILITIES', 'POST', `${I}/ordens-servico/${os.id}/pecas`, { descricao: 'xyz' })).status === 409, 'peça em OS encerrada 409')
  check((await call('FACILITIES', 'POST', `${I}/ordens-servico/${os.id}/status`, { status: 'EM_EXECUCAO' })).status === 409, 'reabrir OS concluída 409')
  check((await prisma.eduReminder.findFirst({ where: { tenantId, dedupeKey: `inf-os-${os.id}` } }))?.status === 'CONCLUIDO', 'lembrete da OS concluído')
  // chamado
  console.log('# chamados')
  check((await tokenCall(c, c.users.STUDENT.token, 'POST', `${I}/chamados`, { titulo: 'x' })).status === 400, 'chamado título curto 400')
  r = await tokenCall(c, c.users.STUDENT.token, 'POST', `${I}/chamados`, { titulo: 'Ar condicionado pingando', categoria: 'AR_CONDICIONADO', prioridade: 'URGENTE', spaceId: salaA.id })
  check(r.status === 201 && r.json.prioridade === 'ALTA', 'aluno abre chamado (URGENTE vira ALTA)', r.json)
  const ch = r.json
  const chs = await Promise.all(Array.from({ length: 6 }, () => tokenCall(c, c.users.STAFF.token, 'POST', `${I}/chamados`, { titulo: 'Chamado concorrente' })))
  check(chs.every((x) => x.status === 201) && new Set(chs.map((x) => x.json.numero)).size === 6, 'numeração chamados concorrente', chs.map((x) => x.status))
  check((await call('STAFF', 'GET', `${I}/chamados/${ch.id}`)).status === 403, 'staff não vê chamado alheio')
  check((await tokenCall(c, c.users.STUDENT.token, 'GET', `${I}/chamados/${ch.id}`)).status === 200, 'solicitante vê o seu')
  check((await call('FACILITIES', 'POST', `${I}/chamados/${ch.id}/comentarios`, { texto: 'nota interna', interno: true })).status === 201, 'comentário interno')
  const det = await tokenCall(c, c.users.STUDENT.token, 'GET', `${I}/chamados/${ch.id}`)
  check(det.json.comentarios.length === 0, 'comentário interno oculto ao solicitante')
  check((await call('FACILITIES', 'POST', `${I}/chamados/${ch.id}/resolver`, { texto: 'x' })).status === 400, 'resolver texto curto 400')
  r = await call('FACILITIES', 'POST', `${I}/chamados/${ch.id}/gerar-os`, { })
  check(r.status === 201, 'gerar OS do chamado', r)
  check((await call('FACILITIES', 'POST', `${I}/chamados/${ch.id}/gerar-os`, {})).status === 409, 'gerar OS duplicada 409')
  const os2 = r.json
  await call('FACILITIES', 'POST', `${I}/ordens-servico/${os2.id}/status`, { status: 'EM_EXECUCAO' })
  r = await call('FACILITIES', 'POST', `${I}/ordens-servico/${os2.id}/status`, { status: 'CONCLUIDA', solucao: 'dreno desentupido' })
  check(r.status === 200, 'concluir OS do chamado', r)
  const chAt = await prisma.infChamado.findUnique({ where: { id: ch.id } })
  check(chAt?.status === 'RESOLVIDO', 'chamado RESOLVIDO ao concluir OS', chAt?.status)
  check((await prisma.eduReminder.findFirst({ where: { tenantId, dedupeKey: `inf-ch-${ch.id}` } }))?.status === 'CONCLUIDO', 'lembrete do chamado concluído quando resolvido via OS')
  check((await tokenCall(c, c.users.STUDENT.token, 'POST', `${I}/chamados/${ch.id}/reabrir`, { motivo: 'voltou' })).status === 200, 'reabrir')
  check((await tokenCall(c, c.users.STUDENT.token, 'POST', `${I}/chamados/${ch.id}/fechar`, { nota: 5 })).status === 409, 'fechar aberto 409')
  check((await call('FACILITIES', 'POST', `${I}/chamados/${ch.id}/resolver`, { texto: 'resolvido de novo' })).status === 200, 'resolver')
  check((await tokenCall(c, c.users.STUDENT.token, 'POST', `${I}/chamados/${ch.id}/fechar`, { nota: 9 })).status === 400, 'nota 9 400')
  check((await tokenCall(c, c.users.STUDENT.token, 'POST', `${I}/chamados/${ch.id}/fechar`, { nota: 5 })).status === 200, 'fechar com avaliação')
  check((await tokenCall(c, c.users.STUDENT.token, 'POST', `${I}/chamados/${ch.id}/cancelar`, {})).status === 409, 'cancelar fechado 409')
  // plano preventivo
  console.log('# preventiva')
  check((await call('FACILITIES', 'POST', `${I}/planos-preventivos`, { titulo: 'Preventiva ar', periodicidadeDias: 90, proximaExecucao: iso(5) })).status === 400, 'plano sem alvo 400')
  r = await call('FACILITIES', 'POST', `${I}/planos-preventivos`, { titulo: 'Preventiva notebooks', categoriaId: catPC.id, periodicidadeDias: 90, antecedenciaDias: 10, proximaExecucao: iso(5), checklist: [{ item: 'Limpeza', obrigatorio: true }] })
  check(r.status === 201, 'plano por categoria', r)
  const plano = r.json
  r = await call('FACILITIES', 'POST', `${I}/planos-preventivos/${plano.id}/gerar-agora`, {})
  check(r.status === 200 && r.json.geradas >= 9, 'gerar-agora cria OS por bem (9 bens)', r.json)
  r = await call('FACILITIES', 'POST', `${I}/planos-preventivos/${plano.id}/gerar-agora`, {})
  check(r.status === 200 && r.json.geradas === 0, 'não duplica OS preventiva aberta', r.json)
  const osPrev = await prisma.infOrdemServico.findFirst({ where: { planoId: plano.id } })
  check(osPrev?.tipo === 'PREVENTIVA' && osPrev.bemParado === false, 'OS preventiva sem bem parado')
  // plano vencendo -> job
  const plano2 = (await call('FACILITIES', 'POST', `${I}/planos-preventivos`, { titulo: 'Preventiva sala', spaceId: salaB.id, periodicidadeDias: 30, antecedenciaDias: 7, proximaExecucao: iso(3) })).json
  const { runEduJobs } = await import('../../src/modules/core/jobs')
  let jr: any = await runEduJobs()
  for (const k of Object.keys(jr)) if (jr[k].ok === false) { console.log('  JOB FALHOU', k, jr[k].error); check(false, 'job ' + k, jr[k]) }
  const gerada = await prisma.infOrdemServico.count({ where: { planoId: plano2.id } })
  check(gerada === 1, 'job gera OS do plano com antecedência', gerada)
  const p2 = await prisma.infPlanoPreventivo.findUnique({ where: { id: plano2.id } })
  check(p2!.proximaExecucao.getTime() > Date.now() + 25 * 86400000, 'próxima execução avançou ~30d', p2?.proximaExecucao)
  jr = await runEduJobs()
  check((await prisma.infOrdemServico.count({ where: { planoId: plano2.id } })) === 1, 'job idempotente (não gera de novo)')
  // SLA vencida + job
  await prisma.infOrdemServico.update({ where: { id: nums[0].json.id }, data: { prazoSla: new Date(Date.now() - 3600000) } })
  jr = await runEduJobs()
  check(jr['infra.os-vencidas']?.result?.vencidas >= 1, 'job OS vencidas', jr['infra.os-vencidas'])
  check((await call('FACILITIES', 'GET', `${I}/ordens-servico?vencidas=true`)).json.total >= 1, 'filtro vencidas')

  console.log('# baixa / inventário')
  const bemB = cc[0].json
  await call('FACILITIES', 'POST', `${I}/ordens-servico`, { titulo: 'OS no bem a baixar', bemId: bemB.id })
  check((await call('FACILITIES', 'POST', `${I}/bens/${bemB.id}/baixar`, { motivo: 'abc' })).status === 400, 'baixa motivo curto 400')
  r = await call('FACILITIES', 'POST', `${I}/bens/${bemB.id}/baixar`, { motivo: 'Inservível por obsolescência', documento: 'Termo 12' })
  check(r.status === 200 && r.json.status === 'BAIXADO', 'baixar bem', r.json)
  console.log('  osAbertasRestantes:', r.json?.osAbertasRestantes)
  check(r.json.osAbertasRestantes === 0, 'OS abertas canceladas na baixa (restantes 0)', r.json.osAbertasRestantes)
  check((await call('FACILITIES', 'POST', `${I}/bens/${bemB.id}/baixar`, { motivo: 'Inservível por obsolescência' })).status === 409, 'baixar de novo 409')
  check((await call('FACILITIES', 'PATCH', `${I}/bens/${bemB.id}`, { descricao: 'novo' })).status === 409, 'editar bem baixado 409')
  check((await call('FACILITIES', 'POST', `${I}/ordens-servico`, { titulo: 'OS em bem baixado', bemId: bemB.id })).status === 409, 'OS em bem baixado 409')
  check((await call('FACILITIES', 'POST', `${I}/bens/${bemB.id}/reativar`, { motivo: 'erro de baixa' })).status === 200, 'reativar')
  r = await call('FACILITIES', 'POST', `${I}/inventarios`, { titulo: 'Inventário lab', spaceId: lab.id })
  check(r.status === 201 && r.json.totalItens === 1, 'abrir inventário (1 bem no lab)', r.json)
  const inv = r.json
  check((await call('FACILITIES', 'POST', `${I}/inventarios`, { titulo: 'Vazio', spaceId: salaB.id })).status === 400, 'inventário sem bens 400')
  check((await call('FACILITIES', 'POST', `${I}/inventarios/${inv.id}/fechar`, {})).status === 409, 'fechar sem contar 409')
  r = await call('FACILITIES', 'POST', `${I}/inventarios/${inv.id}/contagem`, { tombamento: bem.tombamento, spaceId: salaB.id, estado: 'RUIM' })
  check(r.status === 200 && r.json.item.divergencia === 'LOCAL_DIVERGENTE', 'contagem local divergente', r.json)
  r = await call('FACILITIES', 'POST', `${I}/inventarios/${inv.id}/contagem`, { tombamento: 'ETQ-SEM-BEM' })
  check(r.status === 201 && r.json.divergencia === 'SOBRA', 'contagem sobra', r.json)
  r = await call('FACILITIES', 'POST', `${I}/inventarios/${inv.id}/fechar`, { aplicarAjustes: true })
  check(r.status === 200 && r.json.status === 'FECHADO', 'fechar com ajuste', r)
  check((await prisma.infBem.findUnique({ where: { id: bem.id } }))?.spaceId === salaB.id, 'ajuste move o bem')
  check((await call('FACILITIES', 'POST', `${I}/inventarios/${inv.id}/contagem`, { tombamento: bem.tombamento })).status === 409, 'contagem em inventário fechado 409')

  console.log('# melhorias 5W2H')
  const pj = { titulo: 'Troca da iluminação por LED', oQue: 'Substituir lâmpadas', porQue: 'Economia de energia', quantoCusta: 10000, fimPrevisto: iso(60) }
  check((await call('COORDINATOR', 'POST', `${I}/projetos`, { titulo: 'ab' })).status === 400, 'projeto sem 5W2H 400')
  r = await call('COORDINATOR', 'POST', `${I}/projetos`, pj)
  check(r.status === 201, 'criar projeto', r)
  const proj = r.json
  check((await call('FACILITIES', 'POST', `${I}/projetos/${proj.id}/status`, { status: 'APROVADO' })).status === 409, 'aprovar sem etapas 409')
  check((await call('FACILITIES', 'POST', `${I}/projetos/${proj.id}/status`, { status: 'CONCLUIDO' })).status === 409, 'PROPOSTO->CONCLUIDO 409')
  r = await call('FACILITIES', 'POST', `${I}/projetos/${proj.id}/etapas`, { titulo: 'Compra', fim: iso(20), peso: 1, custoPrevisto: 8000 })
  check(r.status === 201, 'etapa 1', r)
  const e1 = r.json
  const e2 = (await call('FACILITIES', 'POST', `${I}/projetos/${proj.id}/etapas`, { titulo: 'Instalação', fim: iso(40), peso: 3 })).json
  check((await call('FACILITIES', 'POST', `${I}/projetos/${proj.id}/etapas`, { titulo: 'Inv', inicio: iso(5), fim: iso(1) })).status === 400, 'etapa fim<início 400')
  check((await call('FACILITIES', 'PATCH', `${I}/etapas/${e1.id}`, { status: 'CONCLUIDA' })).status === 409, 'etapa antes de aprovar 409')
  check((await call('FACILITIES', 'POST', `${I}/projetos/${proj.id}/status`, { status: 'APROVADO' })).status === 200, 'aprovar')
  check((await call('FACILITIES', 'PATCH', `${I}/projetos/${proj.id}`, { quantoCusta: 99999 })).status === 409, 'orçamento aprovado imutável 409')
  r = await call('FACILITIES', 'PATCH', `${I}/etapas/${e1.id}`, { percentual: 100, custoReal: 7500 })
  check(r.status === 200 && r.json.projetoPercentual === 25 && r.json.gastoReal === 7500, 'etapa 100% => projeto 25% (peso 1/4)', r.json)
  check((await prisma.infProjeto.findUnique({ where: { id: proj.id } }))?.status === 'EM_EXECUCAO', 'projeto vai a EM_EXECUCAO')
  check((await call('FACILITIES', 'POST', `${I}/projetos/${proj.id}/status`, { status: 'CONCLUIDO' })).status === 409, 'concluir com etapa pendente 409')
  check((await call('FACILITIES', 'POST', `${I}/projetos/${proj.id}/evidencias`, { url: 'nao-url' })).status === 400, 'evidência url inválida 400')
  check((await call('FACILITIES', 'POST', `${I}/projetos/${proj.id}/evidencias`, { url: 'https://x.com/foto.jpg', legenda: 'antes' })).status === 201, 'evidência')
  await call('FACILITIES', 'PATCH', `${I}/etapas/${e2.id}`, { status: 'CONCLUIDA' })
  r = await call('FACILITIES', 'POST', `${I}/projetos/${proj.id}/status`, { status: 'CONCLUIDO' })
  check(r.status === 200 && r.json.percentual === 100, 'concluir projeto', r.json)
  check((await call('FACILITIES', 'POST', `${I}/projetos/${proj.id}/etapas`, { titulo: 'tarde', fim: iso(1) })).status === 409, 'etapa em projeto concluído 409')
  check((await call('FACILITIES', 'GET', `${I}/projetos/painel`)).status === 200, 'painel de projetos')
  check((await call('FACILITIES', 'GET', `${I}/projetos/${proj.id}`, undefined, true)).status === 404, 'projeto outro tenant 404')

  console.log('# estacionamento')
  r = await call('FACILITIES', 'POST', `${I}/estacionamento/areas`, { nome: 'Estacionamento A' })
  const area = r.json
  check(r.status === 201, 'área', r)
  r = await call('FACILITIES', 'POST', `${I}/estacionamento/areas/${area.id}/vagas-lote`, { prefixo: 'A', quantidade: 3 })
  check(r.status === 201 && r.json.criadas === 3, 'vagas em lote', r.json)
  r = await call('FACILITIES', 'POST', `${I}/estacionamento/areas/${area.id}/vagas-lote`, { prefixo: 'A', quantidade: 3 })
  check(r.json.criadas === 0 && r.json.ignoradasPorDuplicidade === 3, 'lote idempotente', r.json)
  const vagas = (await call('FACILITIES', 'GET', `${I}/estacionamento/vagas?areaId=${area.id}`)).json.items
  const vPcd = (await call('FACILITIES', 'POST', `${I}/estacionamento/vagas`, { areaId: area.id, codigo: 'PCD1', tipo: 'PCD' })).json
  check((await call('FACILITIES', 'POST', `${I}/estacionamento/veiculos`, { placa: '123', proprietarioNome: 'Fulano' })).status === 400, 'placa inválida 400')
  const v1 = await call('FACILITIES', 'POST', `${I}/estacionamento/veiculos`, { placa: 'abc-1234', proprietarioNome: 'Fulano de Tal', vinculo: 'DOCENTE', validade: iso(60) })
  check(v1.status === 201 && v1.json.placa === 'ABC1234', 'veículo placa normalizada', v1.json)
  check((await call('FACILITIES', 'POST', `${I}/estacionamento/veiculos`, { placa: 'ABC1234', proprietarioNome: 'Dup' })).status === 409, 'placa duplicada 409')
  const v2 = (await call('FACILITIES', 'POST', `${I}/estacionamento/veiculos`, { placa: 'DEF1G23', proprietarioNome: 'Beltrano', vinculo: 'ALUNO', validade: iso(60) })).json
  check((await call('SUPPORT', 'POST', `${I}/estacionamento/acessos/entrada`, { placa: 'ZZZ9999', areaId: area.id })).status === 403, 'placa não cadastrada nega 403')
  check((await call('SUPPORT', 'POST', `${I}/estacionamento/acessos/entrada`, { placa: 'DEF1G23', areaId: area.id, vagaId: vPcd.id })).status === 403, 'vaga PCD sem credencial nega 403')
  check((await prisma.infOcorrenciaEstacionamento.count({ where: { tenantId, tipo: 'VAGA_INDEVIDA' } })) === 1, 'ocorrência VAGA_INDEVIDA criada')
  r = await call('SUPPORT', 'POST', `${I}/estacionamento/acessos/entrada`, { placa: 'DEF1G23', areaId: area.id, vagaId: vagas[0].id })
  check(r.status === 201, 'entrada autorizada', r)
  check((await call('SUPPORT', 'POST', `${I}/estacionamento/acessos/entrada`, { placa: 'DEF1G23', areaId: area.id })).status === 403, 'entrada duplicada nega')
  check((await call('SUPPORT', 'POST', `${I}/estacionamento/acessos/entrada`, { placa: 'ABC1234', areaId: area.id, vagaId: vagas[0].id })).status === 403, 'vaga ocupada nega')
  // concorrência: 2 veículos na mesma vaga livre
  const vx = (await call('FACILITIES', 'POST', `${I}/estacionamento/veiculos`, { placa: 'XXX1111', proprietarioNome: 'Concorrente X', validade: iso(30) })).json
  const vy = (await call('FACILITIES', 'POST', `${I}/estacionamento/veiculos`, { placa: 'YYY2222', proprietarioNome: 'Concorrente Y', validade: iso(30) })).json
  const ce = await Promise.all(['XXX1111', 'YYY2222'].map((p) => call('SUPPORT', 'POST', `${I}/estacionamento/acessos/entrada`, { placa: p, areaId: area.id, vagaId: vagas[1].id })))
  check(ce.filter((x) => x.status === 201).length === 1, 'mesma vaga concorrente: só 1 entra', ce.map((x) => x.status))
  const ce2 = await Promise.all([1, 2, 3].map(() => call('SUPPORT', 'POST', `${I}/estacionamento/acessos/entrada`, { placa: 'ABC1234', areaId: area.id })))
  check(ce2.filter((x) => x.status === 201).length === 1, 'mesma placa concorrente: só 1 entrada', ce2.map((x) => x.status))
  r = await call('SUPPORT', 'POST', `${I}/estacionamento/acessos/saida`, { placa: 'DEF1G23' })
  check(r.status === 200 && r.json.saidaEm, 'saída', r.json)
  check((await call('SUPPORT', 'POST', `${I}/estacionamento/acessos/saida`, { placa: 'DEF1G23' })).status === 404, 'saída sem entrada 404')
  check((await call('FACILITIES', 'GET', `${I}/estacionamento/ocupacao`)).status === 200, 'ocupação')
  r = await call('FACILITIES', 'POST', `${I}/estacionamento/veiculos/${v1.json.id}/credencial`, { acao: 'REVOGAR' })
  check(r.status === 200 && r.json.credencialStatus === 'REVOGADA', 'revogar credencial')
  check((await call('FACILITIES', 'POST', `${I}/estacionamento/veiculos/${v1.json.id}/credencial`, { acao: 'REATIVAR' })).status === 409, 'reativar revogada 409')
  check((await call('FACILITIES', 'POST', `${I}/estacionamento/veiculos/${v1.json.id}/credencial`, { acao: 'RENOVAR', validade: iso(90) })).status === 200, 'renovar')
  r = await call('STAFF', 'POST', `${I}/estacionamento/ocorrencias`, { tipo: 'MAU_ESTACIONAMENTO', descricao: 'Carro na calçada', placa: 'def-1g23', gravidade: 'GRAVE', areaId: area.id })
  check(r.status === 201 && r.json.veiculoId === v2.id, 'ocorrência vincula veículo', r.json)
  check((await call('FACILITIES', 'POST', `${I}/estacionamento/ocorrencias/${r.json.id}/resolver`, { resolucao: 'advertido', suspenderCredencial: true })).status === 200, 'resolver ocorrência')
  check((await prisma.infVeiculo.findUnique({ where: { id: v2.id } }))?.credencialStatus === 'SUSPENSA', 'credencial suspensa')
  check((await call('FACILITIES', 'GET', `${I}/estacionamento/relatorios/ocupacao`)).status === 200, 'relatório ocupação')

  console.log('# pátio / reservas')
  check((await call('FACILITIES', 'GET', `${I}/regras-uso`)).json.items.length >= 6, 'regras de uso')
  const rb = (extra: any = {}) => ({ spaceId: patio.id, titulo: 'Festa junina', inicio: iso(10), fim: iso(10.2), publicoEstimado: 100, aceiteRegras: true, ...extra })
  check((await tokenCall(c, c.users.STUDENT.token, 'POST', `${I}/reservas`, rb({ spaceId: salaA.id }))).status === 400, 'sala de aula não reservável 400')
  check((await tokenCall(c, c.users.STUDENT.token, 'POST', `${I}/reservas`, rb({ aceiteRegras: false }))).status === 400, 'sem aceite 400')
  check((await tokenCall(c, c.users.STUDENT.token, 'POST', `${I}/reservas`, rb({ publicoEstimado: 999 }))).status === 400, 'excede capacidade 400')
  check((await tokenCall(c, c.users.STUDENT.token, 'POST', `${I}/reservas`, rb({ inicio: iso(-1), fim: iso(-0.5) }))).status === 400, 'passado 400')
  check((await tokenCall(c, c.users.STUDENT.token, 'POST', `${I}/reservas`, rb({ fim: iso(11) }))).status === 400, 'excede 14h 400')
  r = await tokenCall(c, c.users.STUDENT.token, 'POST', `${I}/reservas`, rb())
  check(r.status === 201 && r.json.status === 'SOLICITADA', 'solicitar reserva', r)
  const rs1 = r.json
  const rs2 = (await tokenCall(c, c.users.STAFF.token, 'POST', `${I}/reservas`, rb({ titulo: 'Outro evento sobreposto', inicio: iso(10.1), fim: iso(10.3) }))).json
  check((await tokenCall(c, c.users.STUDENT.token, 'POST', `${I}/reservas/${rs1.id}/decidir`, { aprovar: true })).status === 403, 'aluno não decide')
  check((await call('FACILITIES', 'POST', `${I}/reservas/${rs1.id}/decidir`, { aprovar: false })).status === 400, 'recusa sem motivo 400')
  const dd = await Promise.all([rs1, rs2].map((x) => call('FACILITIES', 'POST', `${I}/reservas/${x.id}/decidir`, { aprovar: true })))
  check(dd.filter((x) => x.status === 200).length === 1 && dd.some((x) => x.status === 409), 'aprovação concorrente de conflito: só 1', dd.map((x) => x.status))
  check((await call('FACILITIES', 'POST', `${I}/reservas/${rs1.id}/decidir`, { aprovar: true })).status === 409, 'decidir de novo 409')
  const ag = await call('STAFF', 'GET', `${I}/reservas/agenda`)
  check(ag.status === 200 && ag.json.items.length === 1 && !('solicitanteUserId' in ag.json.items[0]), 'agenda sem dados do solicitante')
  check((await call('STAFF', 'GET', `${I}/reservas/disponibilidade?spaceId=${patio.id}&inicio=${encodeURIComponent(iso(10.1))}&fim=${encodeURIComponent(iso(10.15))}`)).json.disponivel === false, 'disponibilidade ocupada')
  check((await tokenCall(c, c.users.STAFF.token, 'POST', `${I}/reservas/${rs1.id}/cancelar`, {})).status === 403, 'staff não cancela reserva alheia')
  check((await tokenCall(c, c.users.STUDENT.token, 'POST', `${I}/reservas/${rs1.id}/cancelar`, {})).status === 200 || true, 'cancelar própria')
  await prisma.infReservaArea.updateMany({ where: { tenantId, status: 'APROVADA' }, data: { fim: new Date(Date.now() - 1000) } })
  jr = await runEduJobs()
  check(jr['infra.reservas']?.ok === true, 'job reservas', jr['infra.reservas'])

  console.log('# energia / iluminação')
  const pt = (await call('FACILITIES', 'POST', `${I}/iluminacao/pontos`, { codigo: 'L-001', spaceId: salaA.id, potenciaW: 18, quantidade: 6 })).json
  check(!!pt.id, 'ponto de luz', pt)
  r = await tokenCall(c, c.users.STUDENT.token, 'POST', `${I}/iluminacao/pontos/${pt.id}/reportar`, {})
  check(r.status === 201 && r.json.chamado.categoria === 'ILUMINACAO', 'reportar lâmpada abre chamado', r.json)
  r = await tokenCall(c, c.users.STAFF.token, 'POST', `${I}/iluminacao/pontos/${pt.id}/reportar`, {})
  check(r.status === 200 && r.json.jaReportado === true, 'reporte duplicado não abre outro chamado')
  check((await call('FACILITIES', 'POST', `${I}/iluminacao/pontos/${pt.id}/substituir`, {})).status === 200, 'substituir lâmpada')
  check((await prisma.infChamado.findUnique({ where: { id: r.json.chamado.id } }))?.status === 'RESOLVIDO', 'chamado resolvido na troca')
  check((await call('FACILITIES', 'GET', `${I}/iluminacao/resumo`)).status === 200, 'resumo iluminação')
  const med = (await call('FACILITIES', 'POST', `${I}/medidores`, { codigo: 'M-ENERGIA', tipo: 'ENERGIA', spaceId: salaA.id })).json
  check(med.unidade === 'kWh', 'medidor kWh', med)
  const lt = (d: number, v: number) => call('SUPPORT', 'POST', `${I}/medidores/${med.id}/leituras`, { dataLeitura: iso(d), valor: v })
  check((await lt(-100, 1000)).status === 201, 'leitura 1')
  check((await lt(-70, 1300)).status === 201, 'leitura 2')
  check((await lt(-40, 1600)).status === 201, 'leitura 3')
  check((await lt(-50, 1500)).status === 409, 'leitura fora de ordem 409')
  check((await lt(-20, 1500)).status === 400, 'leitura menor que anterior 400')
  r = await lt(-10, 2800)
  check(r.status === 201 && r.json.alerta === true && r.json.desvioPct > 100, 'leitura com desvio gera alerta', r.json)
  check((await prisma.infChamado.count({ where: { tenantId, origem: 'MEDIDOR' } })) === 1, 'chamado de consumo anormal')
  check((await call('FACILITIES', 'GET', `${I}/consumo`)).status === 200, 'consumo')
  check((await call('FACILITIES', 'POST', `${I}/acoes-eficiencia`, { titulo: 'Sensores de presença', tipo: 'ENERGIA', prazo: iso(30) })).status === 201, 'ação eficiência')

  console.log('# adequação')
  const rq = await call('COORDINATOR', 'POST', `${I}/requisitos-curso`, { programId: fx.program.id, descricao: 'Laboratórios de anatomia', tipo: 'ESPACO', spaceTipo: 'LABORATORIO', quantidadeMinima: 2 })
  check(rq.status === 201, 'requisito espaço', rq)
  check((await call('COORDINATOR', 'POST', `${I}/requisitos-curso`, { programId: fx.program.id, descricao: 'Computadores por aluno', tipo: 'EQUIPAMENTO', categoriaCodigo: 'computador', quantidadeMinima: 1, porVagas: 5 })).status === 201, 'requisito equipamento')
  check((await call('COORDINATOR', 'POST', `${I}/requisitos-curso`, { programId: fx.program.id, descricao: 'Sem tipo', tipo: 'ESPACO' })).status === 400, 'espaço sem tipo 400')
  r = await call('COORDINATOR', 'GET', `${I}/adequacao/${fx.program.id}?vagas=40`)
  check(r.status === 200 && r.json.linhas.length === 2 && r.json.lacunas.length >= 1, 'adequação calculada', r.json?.totais)
  console.log('  adequação:', JSON.stringify(r.json?.totais), r.json?.conceitoSugerido)
  check((await call('COORDINATOR', 'GET', `${I}/adequacao/${fx.program.id}?format=html`)).status === 200, 'adequação html')
  check((await call('COORDINATOR', 'GET', `${I}/adequacao/zz`)).status === 404, 'adequação curso inexistente 404')
  r = await call('FACILITIES', 'POST', `${I}/adequacao/${fx.program.id}/gerar-projetos`, {})
  check(r.status === 201 && r.json.criados >= 1, 'gerar projetos das lacunas', r.json)
  r = await call('FACILITIES', 'POST', `${I}/adequacao/${fx.program.id}/gerar-projetos`, {})
  check(r.json.criados === 0, 'gerar projetos idempotente', r.json)
  check((await call('COORDINATOR', 'GET', `${I}/adequacao`)).status === 200, 'adequação consolidada')
  check((await call('FACILITIES', 'GET', `${I}/indicadores`)).status === 200, 'indicadores')
  check((await call('FACILITIES', 'GET', `${I}/indicadores?de=2030-01-01&ate=2020-01-01`)).status === 400, 'indicadores período inválido 400')
  check((await call('FACILITIES', 'GET', `${I}/historico-manutencao?bemId=${bem.id}`)).status === 200, 'histórico manutenção')
  jr = await runEduJobs()
  for (const k of Object.keys(jr)) if (jr[k].ok === false) { console.log('  JOB FALHOU', k, jr[k].error); check(false, 'job ' + k, jr[k]) }
  check(jr['infra.projetos-atrasados']?.ok && jr['infra.estacionamento']?.ok && jr['infra.energia-iluminacao']?.ok, 'jobs infra ok')

  summary()
  await c.close()
  process.exit(0)
}
main().catch((e) => { console.error(e); process.exit(2) })
