-- DentalPos One — Chat 6: Cirurgia, Implantodontia e Prótese
-- Migration aditiva. NÃO EXECUTADA.
BEGIN;
CREATE TABLE IF NOT EXISTS "SurgeryCase" (
 "id" TEXT PRIMARY KEY,"clinicId" TEXT NOT NULL,"tenantId" TEXT NOT NULL,"patientId" TEXT NOT NULL,"treatmentItemId" TEXT,"clinicalEvolutionId" TEXT,"surgeryType" TEXT NOT NULL,"tooth" INTEGER,"region" TEXT,"diagnosis" TEXT NOT NULL,"planning" TEXT NOT NULL,"technique" TEXT NOT NULL,"anesthesia" TEXT,"anesthetic" TEXT,"medications" JSONB NOT NULL DEFAULT '[]'::jsonb,"biomaterials" JSONB NOT NULL DEFAULT '[]'::jsonb,"graft" TEXT,"membrane" TEXT,"suture" TEXT,"materialLots" JSONB NOT NULL DEFAULT '[]'::jsonb,"complications" TEXT,"instructions" TEXT,"surgeryDate" TIMESTAMP(3),"returnAt" TIMESTAMP(3),"professionalId" TEXT,"professionalName" TEXT,"status" TEXT NOT NULL DEFAULT 'PLANNED',"notes" TEXT,"createdById" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT "SurgeryCase_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT "SurgeryCase_treatmentItemId_fkey" FOREIGN KEY ("treatmentItemId") REFERENCES "TreatmentItem"("id") ON DELETE SET NULL ON UPDATE CASCADE,CONSTRAINT "SurgeryCase_clinicalEvolutionId_fkey" FOREIGN KEY ("clinicalEvolutionId") REFERENCES "ClinicalEvolution"("id") ON DELETE SET NULL ON UPDATE CASCADE);
CREATE INDEX IF NOT EXISTS "SurgeryCase_clinic_tenant_patient_idx" ON "SurgeryCase"("clinicId","tenantId","patientId"); CREATE INDEX IF NOT EXISTS "SurgeryCase_clinic_status_idx" ON "SurgeryCase"("clinicId","status");
CREATE TABLE IF NOT EXISTS "SurgeryFollowUp" (
 "id" TEXT PRIMARY KEY,"clinicId" TEXT NOT NULL,"tenantId" TEXT NOT NULL,"patientId" TEXT NOT NULL,"surgeryCaseId" TEXT NOT NULL,"followUpAt" TIMESTAMP(3) NOT NULL,"professionalId" TEXT,"professionalName" TEXT,"symptoms" TEXT,"healing" TEXT,"complications" TEXT,"instructions" TEXT,"nextReturnAt" TIMESTAMP(3),"notes" TEXT,"createdById" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT "SurgeryFollowUp_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT "SurgeryFollowUp_surgeryCaseId_fkey" FOREIGN KEY ("surgeryCaseId") REFERENCES "SurgeryCase"("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE INDEX IF NOT EXISTS "SurgeryFollowUp_case_date_idx" ON "SurgeryFollowUp"("surgeryCaseId","followUpAt");
CREATE TABLE IF NOT EXISTS "ImplantRecord" (
 "id" TEXT PRIMARY KEY,"clinicId" TEXT NOT NULL,"tenantId" TEXT NOT NULL,"patientId" TEXT NOT NULL,"surgeryCaseId" TEXT,"treatmentItemId" TEXT,"region" TEXT,"tooth" INTEGER,"brand" TEXT NOT NULL,"productLine" TEXT,"connection" TEXT NOT NULL,"platform" TEXT,"diameterMm" DECIMAL(6,2) NOT NULL,"lengthMm" DECIMAL(6,2) NOT NULL,"lot" TEXT NOT NULL,"serialNumber" TEXT,"installationDate" TIMESTAMP(3),"insertionTorqueNcm" DECIMAL(7,2),"primaryStability" TEXT,"isq" DECIMAL(5,2),"graft" TEXT,"prostheticComponent" TEXT,"healingAbutment" TEXT,"miniPillar" TEXT,"transmucosalHeightMm" DECIMAL(6,2),"componentTorqueNcm" DECIMAL(7,2),"prostheticDate" TIMESTAMP(3),"professionalId" TEXT,"professionalName" TEXT,"laboratoryWorkId" TEXT,"radiographRefs" JSONB NOT NULL DEFAULT '[]'::jsonb,"notes" TEXT,"complications" TEXT,"traceabilityCode" TEXT,"barcodeValue" TEXT,"qrValue" TEXT,"traceabilityPayload" JSONB NOT NULL DEFAULT '{}'::jsonb,"scanSource" TEXT,"createdById" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT "ImplantRecord_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT "ImplantRecord_surgeryCaseId_fkey" FOREIGN KEY ("surgeryCaseId") REFERENCES "SurgeryCase"("id") ON DELETE SET NULL ON UPDATE CASCADE,CONSTRAINT "ImplantRecord_treatmentItemId_fkey" FOREIGN KEY ("treatmentItemId") REFERENCES "TreatmentItem"("id") ON DELETE SET NULL ON UPDATE CASCADE,CONSTRAINT "ImplantRecord_laboratoryWorkId_fkey" FOREIGN KEY ("laboratoryWorkId") REFERENCES "LaboratoryWork"("id") ON DELETE SET NULL ON UPDATE CASCADE);
CREATE INDEX IF NOT EXISTS "ImplantRecord_clinic_tenant_patient_idx" ON "ImplantRecord"("clinicId","tenantId","patientId"); CREATE INDEX IF NOT EXISTS "ImplantRecord_lot_idx" ON "ImplantRecord"("clinicId","lot"); CREATE INDEX IF NOT EXISTS "ImplantRecord_traceability_idx" ON "ImplantRecord"("clinicId","traceabilityCode"); CREATE INDEX IF NOT EXISTS "ImplantRecord_barcode_idx" ON "ImplantRecord"("clinicId","barcodeValue"); CREATE INDEX IF NOT EXISTS "ImplantRecord_qr_idx" ON "ImplantRecord"("clinicId","qrValue"); CREATE UNIQUE INDEX IF NOT EXISTS "ImplantRecord_serial_unique_idx" ON "ImplantRecord"("clinicId","serialNumber") WHERE "serialNumber" IS NOT NULL AND "serialNumber"<>'';
CREATE TABLE IF NOT EXISTS "ProsthesisCase" (
 "id" TEXT PRIMARY KEY,"clinicId" TEXT NOT NULL,"tenantId" TEXT NOT NULL,"patientId" TEXT NOT NULL,"treatmentItemId" TEXT,"implantRecordId" TEXT,"laboratoryWorkId" TEXT,"prosthesisType" TEXT NOT NULL,"teeth" JSONB NOT NULL DEFAULT '[]'::jsonb,"region" TEXT,"material" TEXT NOT NULL,"shade" TEXT,"shadeGuide" TEXT,"conventionalImpression" BOOLEAN NOT NULL DEFAULT FALSE,"impressionNotes" TEXT,"intraoralScan" BOOLEAN NOT NULL DEFAULT FALSE,"scanSystem" TEXT,"stlFileRefs" JSONB NOT NULL DEFAULT '[]'::jsonb,"provisional" TEXT,"tryIn" TEXT,"framework" TEXT,"ceramic" TEXT,"adjustment" TEXT,"deliveryDate" TIMESTAMP(3),"cementation" TEXT,"screw" TEXT,"torqueNcm" DECIMAL(7,2),"warrantyUntil" TIMESTAMP(3),"warrantyTerms" TEXT,"maintenancePlan" TEXT,"status" TEXT NOT NULL DEFAULT 'PLANNED',"notes" TEXT,"createdById" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT "ProsthesisCase_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT "ProsthesisCase_treatmentItemId_fkey" FOREIGN KEY ("treatmentItemId") REFERENCES "TreatmentItem"("id") ON DELETE SET NULL ON UPDATE CASCADE,CONSTRAINT "ProsthesisCase_implantRecordId_fkey" FOREIGN KEY ("implantRecordId") REFERENCES "ImplantRecord"("id") ON DELETE SET NULL ON UPDATE CASCADE,CONSTRAINT "ProsthesisCase_laboratoryWorkId_fkey" FOREIGN KEY ("laboratoryWorkId") REFERENCES "LaboratoryWork"("id") ON DELETE SET NULL ON UPDATE CASCADE);
CREATE INDEX IF NOT EXISTS "ProsthesisCase_clinic_tenant_patient_idx" ON "ProsthesisCase"("clinicId","tenantId","patientId"); CREATE INDEX IF NOT EXISTS "ProsthesisCase_laboratoryWork_idx" ON "ProsthesisCase"("laboratoryWorkId");
CREATE TABLE IF NOT EXISTS "ProsthesisHistory" (
 "id" TEXT PRIMARY KEY,"clinicId" TEXT NOT NULL,"tenantId" TEXT NOT NULL,"patientId" TEXT NOT NULL,"prosthesisCaseId" TEXT NOT NULL,"stage" TEXT NOT NULL,"status" TEXT,"occurredAt" TIMESTAMP(3) NOT NULL,"professionalId" TEXT,"professionalName" TEXT,"notes" TEXT,"createdById" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT "ProsthesisHistory_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT "ProsthesisHistory_prosthesisCaseId_fkey" FOREIGN KEY ("prosthesisCaseId") REFERENCES "ProsthesisCase"("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE INDEX IF NOT EXISTS "ProsthesisHistory_case_date_idx" ON "ProsthesisHistory"("prosthesisCaseId","occurredAt");
COMMIT;
