import { useEffect, useMemo, useState } from "react";
import { Alert, Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Divider, MenuItem, Paper, TextField, ToggleButton, ToggleButtonGroup, Typography } from "@mui/material";
import AddIcon from "@mui/icons-material/Add"; import LinkIcon from "@mui/icons-material/Link"; import NotificationsActiveIcon from "@mui/icons-material/NotificationsActive";
import PageHeader from "../components/PageHeader"; import ProcedurePicker from "../components/ProcedurePicker"; import { useNavigate } from "react-router-dom";
import { createAppointment, getAppointments, getOperationalAlerts, subscribeOperations, changeAppointmentWithHistory } from "../services/OperationsHubService"; import { patientFinancialSummary } from "../services/FinanceHubService"; import { listPatients } from "../services/PatientClinicalService"; import { enqueueAppointmentReminders } from "../services/RevahQueueService"; import type { IntegratedAppointment } from "../types/operationsHub"; import type { AppointmentStatus } from "../types/appointment";
const iso=(d:Date)=>{const x=new Date(d);x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)}; const today=()=>iso(new Date()); const KEY="dentalpos.agenda.notification-settings.v1";
type View="day"|"week"|"month"; type Channel="WhatsApp"|"SMS"; type StatusFilter="Todos"|AppointmentStatus;
const defaultProfessionals=["Todos","Dr. Robson","Dra. Cássia"];
function dateLabel(value:string){return new Date(`${value}T12:00:00`).toLocaleDateString("pt-BR",{weekday:"short",day:"2-digit",month:"2-digit"})}
export default function Agenda(){
 const navigate=useNavigate(); const [items,setItems]=useState<IntegratedAppointment[]>(getAppointments); const [view,setView]=useState<View>("week"); const [date,setDate]=useState(today()); const [professional,setProfessional]=useState("Todos"); const [statusFilter,setStatusFilter]=useState<StatusFilter>("Todos"); const [open,setOpen]=useState(false); const [edit,setEdit]=useState<IntegratedAppointment|null>(null); const [channel,setChannel]=useState<Channel>(()=>{try{return JSON.parse(localStorage.getItem(KEY)||"{}")?.channel||"WhatsApp"}catch{return"WhatsApp"}}); const [form,setForm]=useState({patientName:"",patientPhone:"",professionalName:"Dr. Robson",procedure:"Consulta inicial / avaliação",nextProcedure:"Definir após atendimento",dateISO:date,time:"09:00",room:"Consultório 1",category:"1ª consulta" as NonNullable<IntegratedAppointment["category"]>});
 useEffect(()=>subscribeOperations(()=>setItems(getAppointments())),[]); useEffect(()=>{localStorage.setItem(KEY,JSON.stringify({channel,booking:true,oneDayBefore:true,onDay:true}))},[channel]);
 const range=useMemo(()=>{const base=new Date(`${date}T12:00:00`);if(view==="day")return[date];if(view==="week"){const day=base.getDay()||7;base.setDate(base.getDate()-day+1);return Array.from({length:7},(_,i)=>{const d=new Date(base);d.setDate(base.getDate()+i);return iso(d)})}const y=base.getFullYear(),m=base.getMonth(),days=new Date(y,m+1,0).getDate();return Array.from({length:days},(_,i)=>iso(new Date(y,m,i+1)) )},[date,view]);
 const baseFiltered=useMemo(()=>items.filter(a=>range.includes(a.dateISO)&&(professional==="Todos"||a.professionalName===professional)).sort((a,b)=>(a.dateISO+a.time).localeCompare(b.dateISO+b.time)),[items,range,professional]);
 const filtered=useMemo(()=>baseFiltered.filter(a=>statusFilter==="Todos"||a.status===statusFilter),[baseFiltered,statusFilter]);
 const statusMetrics=useMemo(()=>({total:baseFiltered.length,confirmed:baseFiltered.filter(a=>a.status==="Confirmado").length,waiting:baseFiltered.filter(a=>a.status==="Aguardando").length,inCare:baseFiltered.filter(a=>a.status==="Em atendimento").length,noShow:baseFiltered.filter(a=>a.status==="Faltou").length}),[baseFiltered]);
 const professionals=useMemo(()=>Array.from(new Set([...defaultProfessionals,...items.map(x=>x.professionalName)])),[items]); const alerts=getOperationalAlerts().filter(a=>["Agenda","Pacientes","Laboratório","Financeiro"].includes(a.area)).slice(0,12);
 const save=()=>{if(!form.patientName.trim()||!form.procedure.trim())return;const a=createAppointment({...form,status:"Agendado",source:"Interno",reminders:{onBooking:true,oneDayBefore:true,onDay:true}});enqueueAppointmentReminders({appointmentId:a.id,patientName:a.patientName,phone:a.patientPhone,dateISO:a.dateISO,time:a.time,channel});setOpen(false);setItems(getAppointments())};
 const move=(delta:number)=>{const d=new Date(`${date}T12:00:00`);d.setDate(d.getDate()+delta*(view==="day"?1:view==="week"?7:30));setDate(iso(d))};
 const copyBooking=async()=>{const url=`${window.location.origin}${import.meta.env.BASE_URL}agendamento-online`;try{await navigator.clipboard.writeText(url);alert("Link de agendamento online copiado.")}catch{prompt("Copie o link de agendamento online:",url)}};
 return <Box><PageHeader title="Agenda inteligente" description="Dia, semana ou mês; todos os dentistas ou um profissional; financeiro e pendências visíveis sem abrir o prontuário." actionLabel="Nova consulta" actionIcon={<AddIcon/>} onAction={()=>{setForm({...form,dateISO:date});setOpen(true)}}/>
 <Paper variant="outlined" sx={{p:2,borderRadius:3,mb:2}}><Box sx={{display:"flex",gap:1.5,alignItems:"center",flexWrap:"wrap"}}><ToggleButtonGroup exclusive value={view} onChange={(_,v)=>v&&setView(v)} size="small"><ToggleButton value="day">Dia</ToggleButton><ToggleButton value="week">Semana</ToggleButton><ToggleButton value="month">Mês</ToggleButton></ToggleButtonGroup><TextField size="small" type="date" value={date} onChange={e=>setDate(e.target.value)}/><TextField size="small" select label="Agenda" value={professional} onChange={e=>setProfessional(e.target.value)} sx={{minWidth:220}}>{professionals.map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField><Button onClick={()=>move(-1)}>Anterior</Button><Button onClick={()=>setDate(today())}>Hoje</Button><Button onClick={()=>move(1)}>Próximo</Button><Button startIcon={<LinkIcon/>} onClick={copyBooking}>Agendamento online</Button><TextField size="small" select label="Avisos ao paciente" value={channel} onChange={e=>setChannel(e.target.value as Channel)} sx={{minWidth:180}}><MenuItem value="WhatsApp">WhatsApp</MenuItem><MenuItem value="SMS">SMS</MenuItem></TextField></Box><Box sx={{display:"flex",gap:1,flexWrap:"wrap",mt:1.5,mb:1}}>{([
   ["Todos",statusMetrics.total],["Confirmado",statusMetrics.confirmed],["Aguardando",statusMetrics.waiting],["Em atendimento",statusMetrics.inCare],["Faltou",statusMetrics.noShow]
 ] as Array<[StatusFilter,number]>).map(([label,count])=><Chip key={label} clickable onClick={()=>setStatusFilter(label)} variant={statusFilter===label?"filled":"outlined"} color={label==="Faltou"?"error":label==="Confirmado"?"success":"default"} label={`${label} • ${count}`}/>)}</Box><Typography variant="caption" color="text.secondary"><NotificationsActiveIcon sx={{fontSize:14,verticalAlign:"middle"}}/> Confirmação no agendamento + 1 dia antes + no dia. Canal escolhido pela clínica: {channel}.</Typography></Paper>
 <Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",lg:"minmax(0,2.2fr) minmax(320px,1fr)"},gap:2}}><Paper variant="outlined" sx={{borderRadius:3,overflow:"hidden"}}><Box sx={{p:2,bgcolor:"action.hover"}}><Typography sx={{fontWeight:900}}>{view==="month"?new Date(`${date}T12:00:00`).toLocaleDateString("pt-BR",{month:"long",year:"numeric"}):`${dateLabel(range[0])}${view==="week"?` a ${dateLabel(range[range.length-1])}`:""}`}</Typography></Box>{filtered.length===0?<Box sx={{p:5,textAlign:"center"}}><Typography color="text.secondary">Nenhuma consulta no período.</Typography></Box>:filtered.map(a=>{const f=patientFinancialSummary(a.patientName);const overdueCount=(()=>{try{return JSON.parse(localStorage.getItem("dentalpos.financial.entries.v3")||"[]").filter((x:any)=>x.type==="Receita"&&x.personName?.toLowerCase()===a.patientName.toLowerCase()&&x.status==="Vencido").length}catch{return 0}})();return <Box key={a.id}><Box sx={{p:2,display:"grid",gridTemplateColumns:{xs:"1fr",md:"120px 1fr auto"},gap:2,alignItems:"center",cursor:"pointer"}} onClick={()=>setEdit(a)}><Box><Typography sx={{fontWeight:900}}>{dateLabel(a.dateISO)}</Typography><Typography color="text.secondary">{a.time}</Typography></Box><Box><Typography sx={{fontWeight:900}}>{a.patientName} <Chip size="small" color={f.status==="Em dia"?"success":"error"} label={overdueCount?`${overdueCount} parcela(s) em atraso`:f.status==="Em dia"?"Financeiro OK":"Pendência"}/></Typography><Typography color="text.secondary">{a.professionalName} • {a.category||"Consulta"} • {a.procedure} • {a.room}</Typography></Box><Chip label={a.status} color={a.status==="Confirmado"||a.status==="Finalizado"?"success":a.status==="Faltou"||a.status==="Cancelado"?"error":"default"}/></Box><Divider/></Box>})}</Paper>
 <Paper variant="outlined" sx={{p:2,borderRadius:3}}><Typography variant="h6" sx={{fontWeight:900,mb:1}}>Pendências até resolver</Typography><Typography color="text.secondary" variant="body2" sx={{mb:2}}>Financeiro, faltas, laboratório e agenda ficam visíveis para a equipe.</Typography>{alerts.length===0?<Alert severity="success">Nenhuma pendência crítica agora.</Alert>:alerts.map(a=><Alert key={a.id} severity={a.severity} sx={{mb:1}}><b>{a.title}</b><br/>{a.description}</Alert>)}</Paper></Box>
 <Dialog open={open} onClose={()=>setOpen(false)} fullWidth maxWidth="md"><DialogTitle>Nova consulta</DialogTitle><DialogContent sx={{display:"grid",gridTemplateColumns:{xs:"1fr",md:"1fr 1fr"},gap:2,pt:"12px!important"}}><TextField label="Paciente" value={form.patientName} onChange={e=>{const name=e.target.value,p=listPatients().find(x=>x.fullName.toLowerCase()===name.toLowerCase());setForm({...form,patientName:name,patientPhone:p?.phone||form.patientPhone})}}/><TextField label="Celular" value={form.patientPhone} onChange={e=>setForm({...form,patientPhone:e.target.value})}/><TextField label="Profissional" value={form.professionalName} onChange={e=>setForm({...form,professionalName:e.target.value})}/><TextField label="Sala" value={form.room} onChange={e=>setForm({...form,room:e.target.value})}/><TextField select label="Categoria" value={form.category} onChange={e=>setForm({...form,category:e.target.value as NonNullable<IntegratedAppointment["category"]>})}>{["1ª consulta","Em tratamento","Retorno","Pagamento","Periódico","Marketing","Indicação","Urgência","Outro"].map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField><Box sx={{gridColumn:{md:"1/-1"}}}><ProcedurePicker value={form.procedure} onChange={(name)=>setForm({...form,procedure:name})}/></Box><TextField type="date" label="Data" slotProps={{inputLabel:{shrink:true}}} value={form.dateISO} onChange={e=>setForm({...form,dateISO:e.target.value})}/><TextField type="time" label="Horário" slotProps={{inputLabel:{shrink:true}}} value={form.time} onChange={e=>setForm({...form,time:e.target.value})}/><Box sx={{gridColumn:{md:"1/-1"}}}><ProcedurePicker label="Próximo procedimento sugerido" value={form.nextProcedure} onChange={(name)=>setForm({...form,nextProcedure:name})}/></Box></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancelar</Button><Button variant="contained" onClick={save}>Agendar e gerar lembretes</Button></DialogActions></Dialog>
 <Dialog open={!!edit} onClose={()=>setEdit(null)} fullWidth maxWidth="sm"><DialogTitle>{edit?.patientName}</DialogTitle><DialogContent sx={{display:"grid",gap:2,pt:"12px!important"}}>{edit&&<><Typography><b>{edit.dateISO} às {edit.time}</b> • {edit.professionalName}</Typography><Typography>{edit.procedure}</Typography><TextField select label="Status" value={edit.status} onChange={e=>{const status=e.target.value as AppointmentStatus;changeAppointmentWithHistory(edit.id,{status,requestedBy:"Clínica",reason:"Atualização pela agenda"});setItems(getAppointments());setEdit({...edit,status})}}>{["Agendado","Confirmado","Aguardando","Sala em preparação","Em atendimento","Finalizado","Cancelado","Faltou"].map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField><TextField type="date" label="Remarcar data" value={edit.dateISO} onChange={e=>setEdit({...edit,dateISO:e.target.value})}/><TextField type="time" label="Remarcar horário" value={edit.time} onChange={e=>setEdit({...edit,time:e.target.value})}/></>}</DialogContent><DialogActions sx={{display:"flex",gap:1,flexWrap:"wrap",justifyContent:"flex-end"}}>{edit&&(()=>{const patient=listPatients().find(p=>p.fullName.toLowerCase()===edit.patientName.toLowerCase());return <><Button disabled={!patient} onClick={()=>patient&&navigate(`/prontuario?patientId=${encodeURIComponent(patient.id)}`)}>Prontuário</Button><Button onClick={()=>navigate(`/financeiro?paciente=${encodeURIComponent(edit.patientName)}`)}>Financeiro</Button></>})()}<Button onClick={()=>setEdit(null)}>Fechar</Button>{edit&&<Button variant="contained" onClick={()=>{changeAppointmentWithHistory(edit.id,{dateISO:edit.dateISO,time:edit.time,requestedBy:"Clínica",reason:"Remarcação pela agenda"});setItems(getAppointments());setEdit(null)}}>Salvar remarcação</Button>}</DialogActions></Dialog></Box>;
}
