import { Alert, Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Divider, Paper, Tab, Tabs, TextField, Typography } from "@mui/material";
import AddIcon from "@mui/icons-material/Add"; import EventAvailableIcon from "@mui/icons-material/EventAvailable"; import PrintIcon from "@mui/icons-material/Print"; import RequestQuoteIcon from "@mui/icons-material/RequestQuote";
import { useMemo, useState } from "react"; import { useNavigate, useSearchParams } from "react-router-dom";
import PageHeader from "../components/PageHeader"; import Odontogram from "../components/Odontogram"; import ProcedurePicker from "../components/ProcedurePicker";
import { completeMarksForEvolution, getPatient, listEvolutions, listOdontogram, listTreatmentItems, saveEvolution } from "../services/PatientClinicalService";
import type { ClinicalEvolutionEntry, OdontogramMark } from "../types/patientClinical"; import { createAppointment, getAppointments } from "../services/OperationsHubService";

export default function ClinicalRecord(){
 const [params]=useSearchParams(); const navigate=useNavigate(); const patient=getPatient(params.get("patientId")||params.get("patient")||"")||getPatient("Maria Oliveira");
 const patientId=patient?.id||"p-maria"; const patientName=patient?.fullName||"Maria Oliveira";
 const [marks,setMarks]=useState<OdontogramMark[]>(()=>listOdontogram(patientId)); const [items,setItems]=useState<ClinicalEvolutionEntry[]>(()=>listEvolutions(patientId)); const [tab,setTab]=useState(0); const [open,setOpen]=useState(false); const [schedule,setSchedule]=useState(false); const [selectedIds,setSelectedIds]=useState<string[]>([]);
 const [form,setForm]=useState({professional:"Dr. Responsável",procedure:"",notes:"",nextProcedure:"",dateISO:new Date().toISOString().slice(0,10),time:"09:00"});
 const treatmentItems=listTreatmentItems(patientId); const pending=useMemo(()=>marks.filter(m=>m.state==="pending").length,[marks]); const agendaHistory=useMemo(()=>getAppointments().filter(a=>a.patientName.toLowerCase()===patientName.toLowerCase()).sort((a,b)=>(b.dateISO+b.time).localeCompare(a.dateISO+a.time)),[patientName]);
 const save=()=>{if(!form.procedure.trim()||!form.notes.trim()||!form.nextProcedure.trim()||selectedIds.length===0)return; const id=`e-${Date.now()}`; const updatedMarks=completeMarksForEvolution(patientId,selectedIds,id); const e:ClinicalEvolutionEntry={id,patientId,dateISO:new Date().toISOString(),professional:form.professional,procedure:form.procedure,notes:form.notes,nextProcedure:form.nextProcedure,selectedMarkIds:selectedIds,odontogramSnapshot:updatedMarks,nextAppointmentCreated:schedule,createdAt:new Date().toISOString()}; saveEvolution(patientId,e); if(schedule){createAppointment({patientName,professionalName:form.professional,procedure:form.nextProcedure,nextProcedure:"Definir após atendimento",dateISO:form.dateISO,time:form.time,room:"Consultório 1",status:"Agendado",source:"Interno",reminders:{onBooking:true,oneDayBefore:true,onDay:true}})} setMarks(updatedMarks);setItems(listEvolutions(patientId));setSelectedIds([]);setOpen(false);setForm({...form,procedure:"",notes:"",nextProcedure:""}); };
 return <Box><PageHeader title={`Prontuário • ${patientName}`} description="Prontuário, odontograma e plano clínico integrados. O procedimento realizado deve estar vinculado ao odontograma e sempre indicar o próximo passo." actionLabel="Nova evolução" actionIcon={<AddIcon/>} onAction={()=>setOpen(true)}/>
 <Paper variant="outlined" sx={{p:2,borderRadius:3,mb:2}}><Box sx={{display:"flex",justifyContent:"space-between",gap:2,flexWrap:"wrap"}}><Box><Typography sx={{fontWeight:900}}>{patientName}</Typography><Typography color="text.secondary">{patient?.phone} • {patient?.treatment||"Tratamento não definido"}</Typography></Box><Box sx={{display:"flex",gap:1,flexWrap:"wrap"}}><Chip color={pending?"warning":"success"} label={`${pending} pendência(s) odontológicas`}/><Button startIcon={<RequestQuoteIcon/>} onClick={()=>navigate(`/orcamentos-tratamentos?patient=${encodeURIComponent(patientName)}&patientId=${encodeURIComponent(patientId)}`)}>Gerar orçamento</Button><Button startIcon={<PrintIcon/>} onClick={()=>window.print()}>Imprimir</Button></Box></Box></Paper>
 <Tabs value={tab} onChange={(_,v)=>setTab(v)} sx={{mb:2}}><Tab label="Odontograma"/><Tab label="Evoluções"/><Tab label="Plano de tratamento"/><Tab label="Dados clínicos"/><Tab label="Histórico da Agenda"/></Tabs>
 {tab===0&&<Paper variant="outlined" sx={{p:2.5,borderRadius:3}}><Typography variant="h6" sx={{fontWeight:900}}>Odontograma clínico</Typography><Typography color="text.secondary" sx={{mb:2}}>Vermelho claro = necessita tratamento. Azul = realizado. Clique novamente em uma marcação fora do modo de evolução para alternar seu estado.</Typography><Odontogram patientId={patientId} patientName={patientName} onChange={setMarks}/></Paper>}
 {tab===1&&<Box sx={{display:"grid",gap:2}}>{items.length===0?<Paper variant="outlined" sx={{p:3}}>Ainda não há evoluções.</Paper>:items.map(x=><Paper key={x.id} variant="outlined" sx={{p:2.5,borderRadius:3}}><Typography sx={{fontWeight:900}}>{new Date(x.dateISO).toLocaleString("pt-BR")} • {x.professional}</Typography><Divider sx={{my:1}}/><Typography><b>Realizado:</b> {x.procedure}</Typography><Typography><b>Evolução:</b> {x.notes}</Typography><Typography color="primary.main" sx={{fontWeight:800}}><b>Próximo procedimento:</b> {x.nextProcedure}</Typography><Typography variant="caption" color="text.secondary">Odontograma vinculado: {x.selectedMarkIds.length} marcação(ões) • Próxima consulta: {x.nextAppointmentCreated?"agendada":"não agendada"}</Typography></Paper>)}</Box>}
 {tab===2&&<Box sx={{display:"grid",gap:1.5}}>{treatmentItems.length===0?<Alert severity="info">O plano será alimentado automaticamente pelas marcações do odontograma.</Alert>:treatmentItems.map(x=><Paper key={x.id} variant="outlined" sx={{p:2,borderRadius:2,display:"flex",justifyContent:"space-between",gap:2}}><Box><Typography sx={{fontWeight:800}}>{x.tooth?`Dente ${x.tooth} • `:""}{x.procedure}</Typography><Typography variant="caption" color="text.secondary">Origem: {x.origin}{x.surfaces?.length?` • Face(s): ${x.surfaces.join(", ")}`:""}</Typography></Box><Chip label={x.status} color={x.status==="Concluído"?"success":x.status==="Em tratamento"?"info":"warning"}/></Paper>)}</Box>}
 {tab===3&&<Paper variant="outlined" sx={{p:2.5,borderRadius:3,display:"grid",gap:1}}><Typography><b>Queixa principal:</b> {patient?.mainComplaint||"Não informada"}</Typography><Typography><b>Alergias:</b> {patient?.allergies||"Não informadas"}</Typography><Typography><b>Medicamentos:</b> {patient?.medications||"Não informados"}</Typography><Typography><b>Histórico médico:</b> {patient?.medicalHistory||"Não informado"}</Typography><Typography><b>Observações:</b> {patient?.notes||"Sem observações"}</Typography></Paper>}
 {tab===4&&<Box sx={{display:"grid",gap:1.5}}>{agendaHistory.length===0?<Alert severity="info">Ainda não há histórico de agenda para este paciente.</Alert>:agendaHistory.map(a=><Paper key={a.id} variant="outlined" sx={{p:2,borderRadius:2}}><Typography sx={{fontWeight:900}}>{a.dateISO.split("-").reverse().join("/")} às {a.time} • {a.status}</Typography><Typography color="text.secondary">{a.procedure} • {a.professionalName}</Typography>{(a.history||[]).length?<Box sx={{mt:1,display:"grid",gap:.5}}>{[...(a.history||[])].reverse().map(h=><Typography key={h.id} variant="body2"><b>{h.action}</b> • {new Date(h.atISO).toLocaleString("pt-BR")}{h.requestedBy?" • solicitado por "+h.requestedBy:""}{h.reason?" • "+h.reason:""}{h.previousDateISO&&h.newDateISO&&h.action==="Remarcado"?" • de "+h.previousDateISO.split("-").reverse().join("/")+" "+(h.previousTime||"")+" para "+h.newDateISO.split("-").reverse().join("/")+" "+(h.newTime||""):""}</Typography>)}</Box>:null}</Paper>)}</Box>}
 <Dialog open={open} onClose={()=>setOpen(false)} fullWidth maxWidth="lg"><DialogTitle>Nova evolução clínica</DialogTitle><DialogContent sx={{pt:"12px!important"}}><Alert severity="warning" sx={{mb:2}}>Para salvar a evolução, selecione no odontograma abaixo pelo menos uma face/achado tratado. As marcações selecionadas serão concluídas e ficarão azuis.</Alert><Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",md:"1fr 1fr"},gap:2,mb:3}}><TextField label="Profissional" value={form.professional} onChange={e=>setForm({...form,professional:e.target.value})}/><ProcedurePicker required label="Procedimento realizado" value={form.procedure} onChange={(name)=>setForm({...form,procedure:name})}/><TextField required multiline rows={3} label="Anotações / evolução" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} sx={{gridColumn:{md:"1/-1"}}}/><Box sx={{gridColumn:{md:"1/-1"}}}><ProcedurePicker required label="Próximo procedimento (obrigatório)" value={form.nextProcedure} onChange={(name)=>setForm({...form,nextProcedure:name})}/></Box><Button variant={schedule?"contained":"outlined"} startIcon={<EventAvailableIcon/>} onClick={()=>setSchedule(!schedule)}>{schedule?"Próximo agendamento será criado":"Agendar próxima consulta agora"}</Button>{schedule&&<><TextField type="date" label="Data" value={form.dateISO} onChange={e=>setForm({...form,dateISO:e.target.value})} slotProps={{inputLabel:{shrink:true}}}/><TextField type="time" label="Horário" value={form.time} onChange={e=>setForm({...form,time:e.target.value})} slotProps={{inputLabel:{shrink:true}}}/></>}</Box><Odontogram patientId={patientId} patientName={patientName} selectionMode selectedIds={selectedIds} onSelectionChange={setSelectedIds} onChange={setMarks}/></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancelar</Button><Button variant="contained" disabled={!form.procedure.trim()||!form.notes.trim()||!form.nextProcedure.trim()||selectedIds.length===0} onClick={save}>Salvar evolução e atualizar odontograma</Button></DialogActions></Dialog>
 </Box>;
}
