import { Alert, Box, Button, Chip, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, Paper, Tab, Tabs, TextField, Typography } from "@mui/material";
import HistoryIcon from "@mui/icons-material/History"; import PrintIcon from "@mui/icons-material/Print"; import SaveIcon from "@mui/icons-material/Save";
import { useEffect, useState } from "react"; import { useNavigate, useSearchParams } from "react-router-dom";
import PageHeader from "../components/PageHeader";
import ClinicalAnamnesisForm from "../components/clinical/ClinicalAnamnesisForm";
import ClinicalRevisionHistory from "../components/clinical/ClinicalRevisionHistory";
import { loadClinicalRecord, saveClinicalRecord } from "../services/ClinicalAnamnesisApi";
import type { ClinicalRecordBundle, ClinicalRecordData, ClinicalRecordRevision } from "../types/clinicalAnamnesis";

export default function ClinicalRecord(){
 const [params]=useSearchParams();const navigate=useNavigate();const patientId=params.get("patientId")||"";
 const [bundle,setBundle]=useState<ClinicalRecordBundle|null>(null);const [data,setData]=useState<ClinicalRecordData|null>(null);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [success,setSuccess]=useState("");const [tab,setTab]=useState(0);const [reason,setReason]=useState("");const [professional,setProfessional]=useState("");const [revision,setRevision]=useState<ClinicalRecordRevision|null>(null);
 const reload=async()=>{if(!patientId){setError("Selecione um paciente real para abrir o prontuário.");setLoading(false);return}setLoading(true);setError("");try{const result=await loadClinicalRecord(patientId);setBundle(result);setData(result.record.data);setProfessional(result.record.responsibleProfessionalName||"")}catch(e){setError(e instanceof Error?e.message:"Erro ao carregar prontuário.")}finally{setLoading(false)}};
 useEffect(()=>{void reload()},[patientId]);
 const save=async()=>{if(!bundle||!data||professional.trim().length<2||reason.trim().length<5)return;setSaving(true);setError("");setSuccess("");try{await saveClinicalRecord(patientId,{data,expectedRevision:bundle.record.revisionNumber,changeReason:reason,responsibleProfessionalName:professional,status:"ACTIVE"});setReason("");setSuccess("Nova revisão clínica registrada com autoria, data e hora.");await reload()}catch(e){setError(e instanceof Error?e.message:"Erro ao salvar prontuário.")}finally{setSaving(false)}};
 if(loading)return <Box sx={{display:"grid",placeItems:"center",minHeight:320}}><CircularProgress/></Box>;
 if(!bundle||!data)return <Box><PageHeader title="Prontuário clínico" description="Ficha clínica e anamnese vinculadas ao cadastro do paciente."/><Alert severity="error">{error||"Prontuário indisponível."}</Alert></Box>;
 return <Box><PageHeader title={`Prontuário • ${bundle.patient.fullName}`} description="Ficha clínica versionada: cada salvamento cria uma revisão permanente com autoria e data/hora."/>
  {error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}{success&&<Alert severity="success" sx={{mb:2}}>{success}</Alert>}{bundle.record.riskFlags.length>0&&<Alert severity="warning" sx={{mb:2}}><b>Alertas ativos:</b> {bundle.record.riskFlags.join(" • ")}</Alert>}
  <Paper variant="outlined" sx={{p:2,borderRadius:3,mb:2}}><Box sx={{display:"flex",justifyContent:"space-between",gap:2,flexWrap:"wrap"}}><Box><Typography sx={{fontWeight:900}}>{bundle.patient.fullName}</Typography><Typography color="text.secondary">{bundle.patient.phone}{bundle.patient.cpf?` • CPF ${bundle.patient.cpf}`:""}</Typography></Box><Box sx={{display:"flex",gap:1,alignItems:"center",flexWrap:"wrap"}}><Chip icon={<HistoryIcon/>} label={`Revisão ${bundle.record.revisionNumber}`}/><Chip color={bundle.record.status==="ACTIVE"?"success":"default"} label={bundle.record.status}/><Button startIcon={<PrintIcon/>} onClick={()=>window.print()}>Imprimir</Button></Box></Box><Box sx={{display:"flex",gap:1,flexWrap:"wrap",mt:2}}><Button size="small" onClick={()=>navigate(`/odontograma-periodontograma?patientId=${encodeURIComponent(patientId)}`)}>Odontograma / Periodonto</Button><Button size="small" onClick={()=>navigate(`/orcamentos-tratamentos?patientId=${encodeURIComponent(patientId)}`)}>Plano / Orçamento</Button><Button size="small" onClick={()=>navigate(`/arquivos-exames-clinicos?patientId=${encodeURIComponent(patientId)}`)}>Arquivos / Exames</Button><Button size="small" onClick={()=>navigate(`/cirurgia-implantes-protese?patientId=${encodeURIComponent(patientId)}`)}>Cirurgia / Implantes / Prótese</Button><Button size="small" onClick={()=>navigate(`/clinico-especializado?patientId=${encodeURIComponent(patientId)}`)}>Ortodontia / OFM / DTM</Button><Button size="small" onClick={()=>navigate(`/documentos-clinicos?patientId=${encodeURIComponent(patientId)}`)}>Documentos</Button></Box></Paper>
  <Tabs value={tab} onChange={(_,value)=>setTab(value)} sx={{mb:2}}><Tab label="Ficha clínica e anamnese"/><Tab label={`Histórico (${bundle.revisions.length+bundle.evolutions.length})`}/></Tabs>
  {tab===0&&<><ClinicalAnamnesisForm data={data} onChange={setData} customFields={bundle.customFields}/><Paper variant="outlined" sx={{p:2.5,borderRadius:3,mt:2}}><Typography variant="h6" sx={{fontWeight:900,mb:2}}>Responsabilidade e registro da alteração</Typography><Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",md:"1fr 1fr"},gap:2}}><TextField required label="Profissional responsável" value={professional} onChange={e=>setProfessional(e.target.value)}/><TextField required label="Motivo/resumo desta alteração" value={reason} onChange={e=>setReason(e.target.value)} helperText="Obrigatório; será preservado no histórico."/><Button sx={{gridColumn:{md:"1/-1"},justifySelf:"end"}} variant="contained" startIcon={saving?<CircularProgress size={18}/>:<SaveIcon/>} disabled={saving||professional.trim().length<2||reason.trim().length<5} onClick={save}>Salvar como nova revisão</Button></Box></Paper></>}
  {tab===1&&<ClinicalRevisionHistory revisions={bundle.revisions} evolutions={bundle.evolutions} onSelect={setRevision}/>}
  <Dialog open={Boolean(revision)} onClose={()=>setRevision(null)} fullWidth maxWidth="lg"><DialogTitle>Revisão {revision?.revisionNumber} • somente leitura</DialogTitle><DialogContent sx={{pt:"12px!important"}}>{revision&&<><Alert severity="info" sx={{mb:2}}>Registrada por {revision.authorName} em {new Date(revision.createdAt).toLocaleString("pt-BR")}. Motivo: {revision.changeReason}</Alert><ClinicalAnamnesisForm data={revision.dataSnapshot} onChange={()=>{}} customFields={bundle.customFields} readOnly/></>}</DialogContent><DialogActions><Button onClick={()=>setRevision(null)}>Fechar</Button></DialogActions></Dialog>
 </Box>
}
