import { useState } from "react";
import { Alert, Box, Button, MenuItem, Paper, TextField, Typography } from "@mui/material";
import CameraAltIcon from "@mui/icons-material/CameraAlt";
import PageHeader from "../components/PageHeader";
import { listFinanceEntries, saveFinanceEntries, type FinanceEntryType } from "../services/FinanceHubService";
export default function FinancialScanner(){
 const [fileName,setFileName]=useState(""); const [form,setForm]=useState({description:"",personName:"",type:"Despesa" as FinanceEntryType,value:"",dueDate:"",barcode:"",accountingMode:"Empresa" as "Livro Caixa"|"Empresa",documentType:"Boleto" as "Boleto"|"Nota fiscal"|"Recibo"|"Comprovante"|"Outro"}); const [saved,setSaved]=useState(false);
 const save=()=>{if(!form.description||!form.personName||!form.value||!form.dueDate)return;const rows=listFinanceEntries();saveFinanceEntries([{id:Date.now(),description:form.description,category:"Digitalizado",personName:form.personName,type:form.type,status:form.dueDate<new Date().toISOString().slice(0,10)?"Vencido":"Pendente",value:Number(form.value),dueDate:form.dueDate,origin:"Manual",provider:"Manual",accountingMode:form.accountingMode,documentType:form.documentType,barcode:form.barcode,notes:fileName?`Arquivo capturado: ${fileName}`:undefined},...rows]);setSaved(true)};
 return <Box><PageHeader title="Digitalizar financeiro" description="Contas a pagar, contas pagas, boletos, notas, recibos e comprovantes; classificação por Livro Caixa ou Empresa."/><Alert severity="info" sx={{mb:2}}>No navegador, a câmera/arquivo é capturado e o lançamento é conferido antes de entrar no financeiro. OCR e leitura bancária automática podem ser ligados depois ao backend.</Alert><Paper variant="outlined" sx={{p:3,borderRadius:3,maxWidth:900}}>{saved&&<Alert severity="success" sx={{mb:2}}>Documento registrado no financeiro.</Alert>}<Button component="label" variant="outlined" startIcon={<CameraAltIcon/>}>Capturar foto / arquivo<input hidden type="file" accept="image/*,application/pdf" capture="environment" onChange={e=>setFileName(e.target.files?.[0]?.name||"")}/></Button>{fileName&&<Typography sx={{mt:1}}>{fileName}</Typography>}<Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",md:"1fr 1fr"},gap:2,mt:3}}><TextField select label="Tipo de documento" value={form.documentType} onChange={e=>setForm({...form,documentType:e.target.value as typeof form.documentType})}>{["Boleto","Nota fiscal","Recibo","Comprovante","Outro"].map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField><TextField select label="Escrituração" value={form.accountingMode} onChange={e=>setForm({...form,accountingMode:e.target.value as typeof form.accountingMode})}><MenuItem value="Livro Caixa">Livro Caixa</MenuItem><MenuItem value="Empresa">Empresa</MenuItem></TextField><TextField select label="Natureza" value={form.type} onChange={e=>setForm({...form,type:e.target.value as FinanceEntryType})}><MenuItem value="Despesa">Conta / despesa</MenuItem><MenuItem value="Receita">Recebimento / receita</MenuItem></TextField><TextField label="Código de barras / linha digitável" value={form.barcode} onChange={e=>setForm({...form,barcode:e.target.value})}/><TextField label="Descrição" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><TextField label="Pessoa / fornecedor / paciente" value={form.personName} onChange={e=>setForm({...form,personName:e.target.value})}/><TextField type="number" label="Valor" value={form.value} onChange={e=>setForm({...form,value:e.target.value})}/><TextField type="date" label="Vencimento / data" slotProps={{inputLabel:{shrink:true}}} value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></Box><Button sx={{mt:3}} variant="contained" onClick={save}>Conferir e lançar</Button></Paper></Box>;
}
