import { useEffect, useMemo, useState } from "react";
import { Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, IconButton, MenuItem, Paper, TextField, Tooltip, Typography } from "@mui/material";
import AddIcon from "@mui/icons-material/Add";
import DeleteOutlinedIcon from "@mui/icons-material/Delete";
import PaymentsIcon from "@mui/icons-material/Payments";
import AccountBalanceWalletIcon from "@mui/icons-material/AccountBalanceWallet";
import PageHeader from "../components/PageHeader";
import { enqueueCollection } from "../services/RevahQueueService";
import { useNavigate, useSearchParams } from "react-router-dom";
import { deleteFinanceEntry, listFinanceEntries, saveFinanceEntries, setFinanceEntryStatus, type FinanceEntry, type FinanceEntryType, type PaymentMethod, type PaymentProvider } from "../services/FinanceHubService";

const money=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v||0);
const brDate=(iso:string)=>iso?iso.split("-").reverse().join("/"):"—";
const statusColor=(s:FinanceEntry["status"]):"success"|"error"|"warning"|"default"=>s==="Pago"?"success":s==="Vencido"?"error":s==="Pendente"?"warning":"default";

export default function Financial(){
 const navigate=useNavigate();
 const [searchParams]=useSearchParams();
 const initialType=searchParams.get("tipo");
 const [entries,setEntries]=useState<FinanceEntry[]>(()=>listFinanceEntries());
 const [open,setOpen]=useState(false); const [filter,setFilter]=useState(initialType==="Receita"||initialType==="Despesa"?initialType:"Todos"); const [search,setSearch]=useState("");
 const [form,setForm]=useState({description:"",category:"",personName:"",type:"Despesa" as FinanceEntryType,value:"",dueDate:"",competenceDate:"",paymentMethod:"Transferência" as PaymentMethod,provider:"Manual" as PaymentProvider,notes:""});
 const refresh=()=>setEntries(listFinanceEntries());
 useEffect(()=>{const fn=()=>refresh();window.addEventListener("dentalpos:finance-changed",fn);return()=>window.removeEventListener("dentalpos:finance-changed",fn)},[]);
 useEffect(()=>{const type=searchParams.get("tipo");if(type==="Receita"||type==="Despesa")setFilter(type)},[searchParams]);
 const totals=useMemo(()=>{const valid=entries.filter(e=>e.status!=="Cancelado");const paidIncome=valid.filter(e=>e.type==="Receita"&&e.status==="Pago").reduce((a,e)=>a+e.value,0);const paidExpense=valid.filter(e=>e.type==="Despesa"&&e.status==="Pago").reduce((a,e)=>a+e.value,0);const receivable=valid.filter(e=>e.type==="Receita"&&e.status!=="Pago").reduce((a,e)=>a+e.value,0);const payable=valid.filter(e=>e.type==="Despesa"&&e.status!=="Pago").reduce((a,e)=>a+e.value,0);const overdue=valid.filter(e=>e.status==="Vencido").reduce((a,e)=>a+e.value,0);return{receivable,payable,cash:paidIncome-paidExpense,overdue}},[entries]);
 const visible=useMemo(()=>entries.filter(e=>(filter==="Todos"||e.status===filter||e.type===filter)&&(!search||`${e.description} ${e.personName} ${e.category} ${e.origin||""}`.toLowerCase().includes(search.toLowerCase()))),[entries,filter,search]);
 const add=()=>{if(!form.description.trim()||!form.personName.trim()||!form.value||!form.dueDate)return;const row:FinanceEntry={id:Date.now(),description:form.description.trim(),category:form.category.trim()||"Geral",personName:form.personName.trim(),type:form.type,status:form.dueDate<new Date().toISOString().slice(0,10)?"Vencido":"Pendente",value:Number(form.value),dueDate:form.dueDate,competenceDate:form.competenceDate||undefined,paymentMethod:form.paymentMethod,provider:form.provider,origin:"Manual",notes:form.notes||undefined};saveFinanceEntries([row,...entries]);refresh();setOpen(false);setForm({description:"",category:"",personName:"",type:"Despesa",value:"",dueDate:"",competenceDate:"",paymentMethod:"Transferência",provider:"Manual",notes:""})};
 const changeStatus=(id:number,status:FinanceEntry["status"])=>{setFinanceEntryStatus(id,status);refresh()};
 const remove=(id:number)=>{if(window.confirm("Excluir este lançamento?")){deleteFinanceEntry(id);refresh()}};
 const sendCollection=(e:FinanceEntry)=>{enqueueCollection({financeId:e.id,patientName:e.personName,amount:e.value,dueDate:e.dueDate,paymentMethod:e.paymentMethod});alert("Cobrança adicionada à fila do REVAH. As mensagens serão interrompidas quando a parcela for baixada no fluxo de integração.")};
 const paymentCode=(e:FinanceEntry,kind:"PIX"|"Boleto")=>{const code=`DENTALPOS-${kind}-${e.id}-${Math.round(e.value*100)}`;navigator.clipboard?.writeText(code);alert(`${kind} preparado para integração com ${e.provider||"provedor"}. Código de teste copiado: ${code}`)};
 const exportCsv=()=>{const head=["Paciente/Pessoa","Descrição","Tipo","Status","Valor","Vencimento","Forma","Provedor"];const rows=visible.map(e=>[e.personName,e.description,e.type,e.status,e.value,e.dueDate,e.paymentMethod||"",e.provider||""]);const csv=[head,...rows].map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(";")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}));a.download="dentalpos-financeiro.csv";a.click();URL.revokeObjectURL(a.href)};
 return <Box><PageHeader title="Financeiro" description="Contas a pagar/receber, caixa realizado, vencimentos e integração com orçamentos e recebimentos." actionLabel="Novo lançamento" actionIcon={<AddIcon/>} onAction={()=>setOpen(true)}/>
 <Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",md:"repeat(4,1fr)"},gap:2,mb:3}}>{[["A receber",totals.receivable,<PaymentsIcon/>],["A pagar",totals.payable,<PaymentsIcon/>],["Caixa realizado",totals.cash,<AccountBalanceWalletIcon/>],["Total vencido",totals.overdue,<PaymentsIcon/>]].map(([t,v,i])=><Paper key={String(t)} sx={{p:2.5,borderRadius:3}}><Box sx={{display:"flex",justifyContent:"space-between",gap:2}}><Box><Typography color="text.secondary">{t}</Typography><Typography variant="h5" sx={{fontWeight:900}}>{money(Number(v))}</Typography></Box>{i}</Box></Paper>)}</Box>
 <Paper variant="outlined" sx={{p:2,mb:2,borderRadius:3}}><Box sx={{display:"flex",gap:1,flexWrap:"wrap",alignItems:"center"}}><Button variant="contained" onClick={()=>navigate("/pagamentos")}>Central de cobrança</Button><Button onClick={()=>navigate("/integracoes")}>Integrações</Button><Button onClick={()=>navigate("/financeiro/digitalizar")}>Digitalizar conta/nota</Button><Button onClick={()=>navigate("/revah")}>Cobranças REVAH</Button></Box></Paper><Box sx={{display:"flex",gap:1,mb:2,flexWrap:"wrap",alignItems:"center"}}><TextField size="small" placeholder="Buscar lançamento..." value={search} onChange={e=>setSearch(e.target.value)} sx={{minWidth:280}}/>{["Todos","Pendente","Vencido","Pago","Receita","Despesa"].map(x=><Chip key={x} label={x} color={filter===x?"primary":"default"} onClick={()=>setFilter(x)}/>)}<Button onClick={exportCsv}>Exportar CSV</Button></Box>
 <Paper sx={{overflow:"hidden",borderRadius:3}}>{visible.length===0?<Typography sx={{p:3}} color="text.secondary">Nenhum lançamento encontrado.</Typography>:visible.map(e=><Box key={e.id} sx={{display:"grid",gridTemplateColumns:{xs:"1fr",md:"2fr 1fr .8fr .8fr auto"},gap:2,p:2,borderBottom:"1px solid",borderColor:"divider",alignItems:"center"}}><Box><Typography sx={{fontWeight:800}}>{e.description}</Typography><Typography variant="body2" color="text.secondary">{e.personName} • {e.category} • {e.origin||"Manual"}{e.paymentMethod?` • ${e.paymentMethod}`:""}{e.provider?` / ${e.provider}`:""}</Typography></Box><Typography sx={{fontWeight:800}} color={e.type==="Receita"?"success.main":"error.main"}>{e.type==="Despesa"?"− ":"+ "}{money(e.value)}</Typography><Typography>{brDate(e.dueDate)}</Typography><Chip size="small" label={e.status} color={statusColor(e.status)}/><Box sx={{display:"flex",gap:.5,flexWrap:"wrap"}}>{e.type==="Receita"&&e.status!=="Pago"&&e.status!=="Cancelado"&&<><Button size="small" onClick={()=>sendCollection(e)}>REVAH</Button>{e.provider==="Asaas"&&<><Button size="small" onClick={()=>paymentCode(e,"PIX")}>PIX</Button><Button size="small" onClick={()=>paymentCode(e,"Boleto")}>Boleto</Button></>}</>}{e.status!=="Pago"&&e.status!=="Cancelado"&&<Button size="small" onClick={()=>changeStatus(e.id,"Pago")}>Baixar</Button>}{e.status!=="Cancelado"&&e.status!=="Pago"&&<Button size="small" color="inherit" onClick={()=>changeStatus(e.id,"Cancelado")}>Cancelar</Button>}<Tooltip title="Excluir"><IconButton size="small" onClick={()=>remove(e.id)}><DeleteOutlinedIcon fontSize="small"/></IconButton></Tooltip></Box></Box>)}</Paper>
 <Dialog open={open} onClose={()=>setOpen(false)} fullWidth maxWidth="sm"><DialogTitle>Novo lançamento</DialogTitle><DialogContent sx={{display:"grid",gap:2,pt:"12px!important"}}><TextField required label="Descrição" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><TextField required label="Pessoa / fornecedor / paciente" value={form.personName} onChange={e=>setForm({...form,personName:e.target.value})}/><TextField label="Categoria" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/><TextField select label="Tipo" value={form.type} onChange={e=>setForm({...form,type:e.target.value as FinanceEntryType})}><MenuItem value="Receita">Receita</MenuItem><MenuItem value="Despesa">Despesa</MenuItem></TextField><TextField required label="Valor" type="number" value={form.value} onChange={e=>setForm({...form,value:e.target.value})}/><Box sx={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:2}}><TextField required label="Vencimento" type="date" slotProps={{inputLabel:{shrink:true}}} value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/><TextField label="Competência" type="date" slotProps={{inputLabel:{shrink:true}}} value={form.competenceDate} onChange={e=>setForm({...form,competenceDate:e.target.value})}/></Box><Box sx={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:2}}><TextField select label="Forma" value={form.paymentMethod} onChange={e=>setForm({...form,paymentMethod:e.target.value as PaymentMethod})}>{["PIX","Cartão","Boleto","Transferência","Dinheiro"].map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField><TextField select label="Provedor" value={form.provider} onChange={e=>setForm({...form,provider:e.target.value as PaymentProvider})}>{["Asaas","Stripe","Banco / Open Finance","Manual"].map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField></Box><TextField multiline minRows={2} label="Observações" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancelar</Button><Button variant="contained" onClick={add}>Salvar lançamento</Button></DialogActions></Dialog></Box>;
}
