import { useMemo, useState } from "react";
import {
  Alert, Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Divider, MenuItem,
  Paper, Tab, Tabs, TextField, Typography,
} from "@mui/material";
import AddIcon from "@mui/icons-material/Add";
import EditIcon from "@mui/icons-material/Edit";
import PageHeader from "../components/PageHeader";
import { employees as seedEmployees } from "../services/HumanResourcesService";
import type {
  AttendanceRecord, DisciplinaryAction, Employee, EmployeeCategory, EmployeeStatus, EmploymentModel,
  HRDocument, PayrollClosing, PayrollEntry, VacationControl,
} from "../types/humanResources";
import { repairObjectText } from "../utils/textEncoding";

const KEYS = {
  employees: "dentalpos.hr.employees.v3",
  attendance: "dentalpos.hr.attendance.v3",
  payroll: "dentalpos.hr.payroll.v3",
  closings: "dentalpos.hr.closings.v3",
  vacations: "dentalpos.hr.vacations.v3",
  documents: "dentalpos.hr.documents.v3",
  discipline: "dentalpos.hr.discipline.v3",
};
const money=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v);
const today=()=>new Date().toISOString().slice(0,10);
const load=<T,>(key:string,fallback:T):T=>{try{const raw=JSON.parse(localStorage.getItem(key)||"null")??fallback;const fixed=repairObjectText<T>(raw);localStorage.setItem(key,JSON.stringify(fixed));return fixed}catch{return fallback}};
const persist=<T,>(key:string,value:T,setter:(v:T)=>void)=>{setter(value);localStorage.setItem(key,JSON.stringify(value))};
const categoryOptions:EmployeeCategory[]=["Cirurgião-dentista","ASB","TSB","Técnico em Prótese Dentária","Auxiliar de Laboratório","Recepção","Administrativo","Financeiro","Comercial","Marketing","Zeladoria","Manutenção","Professor","Tutor","Representante","Estagiário","Outro"];
const employmentOptions:EmploymentModel[]=["CLT","PJ","Autônomo","Estágio","Diária","Percentual","Locação de espaço","Terceirizado"];
const statusOptions:EmployeeStatus[]=["Ativo","Experiência","Férias","Afastado","Aviso-prévio","Desligado"];

export default function HumanResources(){
  const [tab,setTab]=useState(0); const [search,setSearch]=useState(""); const [openEmployee,setOpenEmployee]=useState(false); const [editingId,setEditingId]=useState<number|null>(null);
  const [employees,setEmployees]=useState<Employee[]>(()=>load(KEYS.employees,seedEmployees));
  const [attendance,setAttendance]=useState<AttendanceRecord[]>(()=>load(KEYS.attendance,[]));
  const [payroll,setPayroll]=useState<PayrollEntry[]>(()=>load(KEYS.payroll,[]));
  const [closings,setClosings]=useState<PayrollClosing[]>(()=>load(KEYS.closings,[]));
  const [vacations,setVacations]=useState<VacationControl[]>(()=>load(KEYS.vacations,[]));
  const [documents,setDocuments]=useState<HRDocument[]>(()=>load(KEYS.documents,[]));
  const [discipline,setDiscipline]=useState<DisciplinaryAction[]>(()=>load(KEYS.discipline,[]));
  const [form,setForm]=useState({name:"",category:"Outro" as EmployeeCategory,position:"",department:"",employmentModel:"CLT" as EmploymentModel,status:"Ativo" as EmployeeStatus,admissionDate:today(),experienceEndDate:"",baseSalary:"",monthlyWorkload:"220",supervisor:"",phone:"",email:"",cpf:"",pixKey:"",notes:""});
  const [attendanceForm,setAttendanceForm]=useState({employeeId:"",date:today(),status:"Presente" as AttendanceRecord["status"],clockIn:"08:00",clockOut:"18:00",overtimeHours:"0",balanceHours:"0",observation:""});
  const [payrollForm,setPayrollForm]=useState({employeeId:"",description:"Salário-base",type:"Provento" as PayrollEntry["type"],value:"",reference:new Date().toLocaleDateString("pt-BR",{month:"2-digit",year:"numeric"})});
  const [vacationForm,setVacationForm]=useState({employeeId:"",acquisitionStart:today(),acquisitionEnd:today(),concessionDeadline:today(),scheduledStart:"",scheduledEnd:"",vacationDays:"30",soldDays:"0",status:"Disponível" as VacationControl["status"]});
  const [documentForm,setDocumentForm]=useState({employeeId:"",type:"Contrato CLT",title:"",issuedAt:today(),expiresAt:"",status:"Rascunho" as HRDocument["status"],digitallySigned:false,notes:""});
  const [disciplineForm,setDisciplineForm]=useState({employeeId:"",type:"Orientação" as DisciplinaryAction["type"],date:today(),reason:"",daysSuspended:"0"});

  const active=employees.filter(e=>e.status!=="Desligado"); const monthlyCost=useMemo(()=>active.reduce((a,e)=>a+e.baseSalary,0),[active]);
  const filtered=employees.filter(e=>`${e.name} ${e.position} ${e.department}`.toLowerCase().includes(search.toLowerCase()));
  const expiringExperience=active.filter(e=>e.experienceEndDate && new Date(e.experienceEndDate).getTime()-Date.now()<1000*60*60*24*15 && new Date(e.experienceEndDate)>=new Date());
  const expiredDocs=documents.filter(d=>d.expiresAt && d.expiresAt<today() && d.status!=="Cancelado"); const overdueVacations=vacations.filter(v=>v.status==="Vencida" || v.concessionDeadline<today());
  const alertCount=expiringExperience.length+expiredDocs.length+overdueVacations.length;

  const resetEmployee=()=>{setEditingId(null);setForm({name:"",category:"Outro",position:"",department:"",employmentModel:"CLT",status:"Ativo",admissionDate:today(),experienceEndDate:"",baseSalary:"",monthlyWorkload:"220",supervisor:"",phone:"",email:"",cpf:"",pixKey:"",notes:""})};
  const saveEmployee=()=>{if(!form.name.trim()||!form.position.trim())return;const existing=employees.find(e=>e.id===editingId);const data:Employee={id:existing?.id??Date.now(),name:form.name.trim(),employeeCode:existing?.employeeCode??`DP-${String(employees.length+1).padStart(4,"0")}`,category:form.category,department:form.department.trim()||"Geral",position:form.position.trim(),employmentModel:form.employmentModel,status:form.status,admissionDate:form.admissionDate,experienceEndDate:form.experienceEndDate||undefined,baseSalary:Number(form.baseSalary)||0,monthlyWorkload:Number(form.monthlyWorkload)||220,supervisor:form.supervisor,email:form.email,phone:form.phone,cpf:form.cpf,pixKey:form.pixKey,notes:form.notes};const next=existing?employees.map(e=>e.id===existing.id?data:e):[data,...employees];persist(KEYS.employees,next,setEmployees);setOpenEmployee(false);resetEmployee()};
  const editEmployee=(e:Employee)=>{setEditingId(e.id);setForm({name:e.name,category:e.category,position:e.position,department:e.department,employmentModel:e.employmentModel,status:e.status,admissionDate:e.admissionDate,experienceEndDate:e.experienceEndDate||"",baseSalary:String(e.baseSalary),monthlyWorkload:String(e.monthlyWorkload),supervisor:e.supervisor,phone:e.phone,email:e.email,cpf:e.cpf||"",pixKey:e.pixKey||"",notes:e.notes||""});setOpenEmployee(true)};
  const employeeName=(id:number)=>employees.find(e=>e.id===id)?.name||"Colaborador";
  const addAttendance=()=>{const id=Number(attendanceForm.employeeId);if(!id)return;const item:AttendanceRecord={id:Date.now(),employeeId:id,employeeName:employeeName(id),date:attendanceForm.date,clockIn:attendanceForm.clockIn||undefined,clockOut:attendanceForm.clockOut||undefined,workedHours:0,overtimeHours:Number(attendanceForm.overtimeHours)||0,balanceHours:Number(attendanceForm.balanceHours)||0,status:attendanceForm.status,observation:attendanceForm.observation};persist(KEYS.attendance,[item,...attendance],setAttendance)};
  const addPayroll=()=>{const id=Number(payrollForm.employeeId);if(!id||!Number(payrollForm.value))return;const item:PayrollEntry={id:Date.now(),employeeId:id,employeeName:employeeName(id),description:payrollForm.description,type:payrollForm.type,value:Number(payrollForm.value),reference:payrollForm.reference};persist(KEYS.payroll,[item,...payroll],setPayroll)};
  const createClosing=()=>{const ref=payrollForm.reference;const rows=payroll.filter(p=>p.reference===ref);const gross=rows.filter(p=>p.type==="Provento"||p.type==="Benefício").reduce((a,p)=>a+p.value,0);const discounts=rows.filter(p=>p.type==="Desconto").reduce((a,p)=>a+p.value,0);const charges=rows.filter(p=>p.type==="Encargo").reduce((a,p)=>a+p.value,0);const closing:PayrollClosing={id:Date.now(),referenceMonth:ref,employeeCount:new Set(rows.map(r=>r.employeeId)).size,grossPayroll:gross,discounts,employerCharges:charges,netPayroll:gross-discounts,paymentDate:today(),status:"Em cálculo"};persist(KEYS.closings,[closing,...closings.filter(c=>c.referenceMonth!==ref)],setClosings)};
  const addVacation=()=>{const id=Number(vacationForm.employeeId);if(!id)return;const item:VacationControl={id:Date.now(),employeeId:id,employeeName:employeeName(id),acquisitionStart:vacationForm.acquisitionStart,acquisitionEnd:vacationForm.acquisitionEnd,concessionDeadline:vacationForm.concessionDeadline,scheduledStart:vacationForm.scheduledStart||undefined,scheduledEnd:vacationForm.scheduledEnd||undefined,vacationDays:Number(vacationForm.vacationDays)||30,soldDays:Number(vacationForm.soldDays)||0,status:vacationForm.status};persist(KEYS.vacations,[item,...vacations],setVacations)};
  const addDocument=()=>{const id=Number(documentForm.employeeId);if(!id||!documentForm.title.trim())return;const item:HRDocument={id:Date.now(),employeeId:id,employeeName:employeeName(id),type:documentForm.type,title:documentForm.title,issuedAt:documentForm.issuedAt,expiresAt:documentForm.expiresAt||undefined,status:documentForm.status,digitallySigned:documentForm.digitallySigned,notes:documentForm.notes};persist(KEYS.documents,[item,...documents],setDocuments)};
  const addDiscipline=()=>{const id=Number(disciplineForm.employeeId);if(!id||!disciplineForm.reason.trim())return;const item:DisciplinaryAction={id:Date.now(),employeeId:id,employeeName:employeeName(id),type:disciplineForm.type,date:disciplineForm.date,reason:disciplineForm.reason,daysSuspended:Number(disciplineForm.daysSuspended)||undefined,status:"Aplicada"};persist(KEYS.discipline,[item,...discipline],setDiscipline)};

  return <Box>
    <PageHeader title="RH e Gestão de Pessoas" description="Admissão, contratos, ponto, banco de horas, folha, férias, documentos, ocorrências e desligamentos." actionLabel="Novo colaborador" actionIcon={<AddIcon/>} onAction={()=>{resetEmployee();setOpenEmployee(true)}}/>
    {alertCount>0&&<Alert severity="warning" sx={{mb:2}}>Há {alertCount} alerta(s) de RH: experiência próxima do vencimento, documentos vencidos ou férias em atenção.</Alert>}
    <Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",md:"repeat(4,1fr)"},gap:2,mb:2}}>{[["Colaboradores ativos",active.length],["Em experiência",active.filter(e=>e.status==="Experiência").length],["Custo-base mensal",money(monthlyCost)],["Alertas",alertCount]].map(([t,v])=><Paper key={String(t)} sx={{p:2.2,borderRadius:3}}><Typography color="text.secondary">{t}</Typography><Typography variant="h5" sx={{fontWeight:900}}>{v}</Typography></Paper>)}</Box>
    <Paper sx={{borderRadius:3,overflow:"hidden"}}><Tabs value={tab} onChange={(_,v)=>setTab(v)} variant="scrollable"><Tab label="Colaboradores"/><Tab label="Ponto e banco de horas"/><Tab label="Folha"/><Tab label="Férias"/><Tab label="Documentos"/><Tab label="Ocorrências"/></Tabs>
      {tab===0&&<Box><Box sx={{p:2}}><TextField size="small" placeholder="Buscar colaborador..." value={search} onChange={e=>setSearch(e.target.value)} sx={{minWidth:300}}/></Box>{filtered.map(e=><Box key={e.id} sx={{display:"grid",gridTemplateColumns:{xs:"1fr",md:"2fr 1.3fr 1fr 1fr auto"},gap:2,p:2,borderTop:"1px solid",borderColor:"divider",alignItems:"center"}}><Box><Typography sx={{fontWeight:800}}>{e.name}</Typography><Typography variant="body2" color="text.secondary">{e.employeeCode} • {e.department}</Typography>{e.experienceEndDate&&<Typography variant="caption" color="warning.main">Experiência até {e.experienceEndDate}</Typography>}</Box><Typography>{e.position}</Typography><Chip size="small" label={e.employmentModel}/><Box><Typography>{money(e.baseSalary)}</Typography><Chip size="small" label={e.status} color={e.status==="Ativo"?"success":e.status==="Experiência"?"warning":"default"}/></Box><Button size="small" startIcon={<EditIcon/>} onClick={()=>editEmployee(e)}>Editar</Button></Box>)}</Box>}
      {tab===1&&<Box sx={{p:2}}><SectionTitle title="Lançar ponto / ocorrência"/><Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",md:"2fr 1fr 1fr 1fr 1fr 1fr"},gap:1.5,mb:2}}><EmployeeSelect value={attendanceForm.employeeId} onChange={v=>setAttendanceForm({...attendanceForm,employeeId:v})} employees={employees}/><TextField type="date" label="Data" value={attendanceForm.date} onChange={e=>setAttendanceForm({...attendanceForm,date:e.target.value})} slotProps={{inputLabel:{shrink:true}}}/><TextField select label="Status" value={attendanceForm.status} onChange={e=>setAttendanceForm({...attendanceForm,status:e.target.value as AttendanceRecord["status"]})}>{["Presente","Atraso","Falta","Atestado","Folga","Férias","Home office"].map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField><TextField label="Entrada" value={attendanceForm.clockIn} onChange={e=>setAttendanceForm({...attendanceForm,clockIn:e.target.value})}/><TextField label="Saída" value={attendanceForm.clockOut} onChange={e=>setAttendanceForm({...attendanceForm,clockOut:e.target.value})}/><Button variant="contained" onClick={addAttendance}>Lançar</Button></Box><Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",md:"repeat(3,1fr)"},gap:1.5,mb:2}}><TextField label="Horas extras" type="number" value={attendanceForm.overtimeHours} onChange={e=>setAttendanceForm({...attendanceForm,overtimeHours:e.target.value})}/><TextField label="Saldo banco de horas" type="number" value={attendanceForm.balanceHours} onChange={e=>setAttendanceForm({...attendanceForm,balanceHours:e.target.value})}/><TextField label="Observação / justificativa" value={attendanceForm.observation} onChange={e=>setAttendanceForm({...attendanceForm,observation:e.target.value})}/></Box>{attendance.map(r=><Row key={r.id} left={`${r.employeeName} • ${r.date}`} middle={`${r.status} • ${r.clockIn||"—"} → ${r.clockOut||"—"}`} right={`HE ${r.overtimeHours}h • Banco ${r.balanceHours}h`}/>)}</Box>}
      {tab===2&&<Box sx={{p:2}}><SectionTitle title="Lançamentos da folha"/><Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",md:"2fr 2fr 1fr 1fr 1fr auto"},gap:1.5,mb:2}}><EmployeeSelect value={payrollForm.employeeId} onChange={v=>setPayrollForm({...payrollForm,employeeId:v})} employees={employees}/><TextField label="Descrição" value={payrollForm.description} onChange={e=>setPayrollForm({...payrollForm,description:e.target.value})}/><TextField select label="Tipo" value={payrollForm.type} onChange={e=>setPayrollForm({...payrollForm,type:e.target.value as PayrollEntry["type"]})}>{["Provento","Desconto","Encargo","Benefício"].map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField><TextField label="Valor" type="number" value={payrollForm.value} onChange={e=>setPayrollForm({...payrollForm,value:e.target.value})}/><TextField label="Referência" value={payrollForm.reference} onChange={e=>setPayrollForm({...payrollForm,reference:e.target.value})}/><Button variant="contained" onClick={addPayroll}>Lançar</Button></Box><Button onClick={createClosing} variant="outlined" sx={{mb:2}}>Gerar fechamento da referência</Button>{payroll.map(p=><Row key={p.id} left={`${p.employeeName} • ${p.reference}`} middle={`${p.type} • ${p.description}`} right={money(p.value)}/>)}<Divider sx={{my:2}}/><SectionTitle title="Fechamentos"/>{closings.map(c=><Row key={c.id} left={`${c.referenceMonth} • ${c.employeeCount} colaboradores`} middle={`Bruto ${money(c.grossPayroll)} • Descontos ${money(c.discounts)} • Encargos ${money(c.employerCharges)}`} right={`${money(c.netPayroll)} • ${c.status}`}/>)}</Box>}
      {tab===3&&<Box sx={{p:2}}><SectionTitle title="Controle de férias"/><Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",md:"2fr repeat(4,1fr) auto"},gap:1.5,mb:2}}><EmployeeSelect value={vacationForm.employeeId} onChange={v=>setVacationForm({...vacationForm,employeeId:v})} employees={employees}/><TextField type="date" label="Início aquisitivo" value={vacationForm.acquisitionStart} onChange={e=>setVacationForm({...vacationForm,acquisitionStart:e.target.value})} slotProps={{inputLabel:{shrink:true}}}/><TextField type="date" label="Fim aquisitivo" value={vacationForm.acquisitionEnd} onChange={e=>setVacationForm({...vacationForm,acquisitionEnd:e.target.value})} slotProps={{inputLabel:{shrink:true}}}/><TextField type="date" label="Limite concessão" value={vacationForm.concessionDeadline} onChange={e=>setVacationForm({...vacationForm,concessionDeadline:e.target.value})} slotProps={{inputLabel:{shrink:true}}}/><TextField select label="Status" value={vacationForm.status} onChange={e=>setVacationForm({...vacationForm,status:e.target.value as VacationControl["status"]})}>{["Em aquisição","Disponível","Programada","Em férias","Concluída","Vencida"].map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField><Button variant="contained" onClick={addVacation}>Salvar</Button></Box>{vacations.map(v=><Row key={v.id} left={v.employeeName} middle={`Aquisitivo ${v.acquisitionStart} a ${v.acquisitionEnd} • limite ${v.concessionDeadline}`} right={v.status}/>)}</Box>}
      {tab===4&&<Box sx={{p:2}}><SectionTitle title="Contratos e documentos"/><Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",md:"2fr 1.4fr 2fr 1fr 1fr auto"},gap:1.5,mb:2}}><EmployeeSelect value={documentForm.employeeId} onChange={v=>setDocumentForm({...documentForm,employeeId:v})} employees={employees}/><TextField label="Tipo" value={documentForm.type} onChange={e=>setDocumentForm({...documentForm,type:e.target.value})}/><TextField label="Título" value={documentForm.title} onChange={e=>setDocumentForm({...documentForm,title:e.target.value})}/><TextField type="date" label="Emissão" value={documentForm.issuedAt} onChange={e=>setDocumentForm({...documentForm,issuedAt:e.target.value})} slotProps={{inputLabel:{shrink:true}}}/><TextField type="date" label="Vencimento" value={documentForm.expiresAt} onChange={e=>setDocumentForm({...documentForm,expiresAt:e.target.value})} slotProps={{inputLabel:{shrink:true}}}/><Button variant="contained" onClick={addDocument}>Adicionar</Button></Box>{documents.map(d=><Row key={d.id} left={`${d.employeeName} • ${d.title}`} middle={`${d.type} • emissão ${d.issuedAt}${d.expiresAt?` • vence ${d.expiresAt}`:""}`} right={d.status}/>)}</Box>}
      {tab===5&&<Box sx={{p:2}}><SectionTitle title="Orientações, advertências e suspensões"/><Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",md:"2fr 1.5fr 1fr 3fr auto"},gap:1.5,mb:2}}><EmployeeSelect value={disciplineForm.employeeId} onChange={v=>setDisciplineForm({...disciplineForm,employeeId:v})} employees={employees}/><TextField select label="Tipo" value={disciplineForm.type} onChange={e=>setDisciplineForm({...disciplineForm,type:e.target.value as DisciplinaryAction["type"]})}>{["Orientação","Advertência verbal","Advertência escrita","Suspensão","Justa causa"].map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField><TextField type="date" label="Data" value={disciplineForm.date} onChange={e=>setDisciplineForm({...disciplineForm,date:e.target.value})} slotProps={{inputLabel:{shrink:true}}}/><TextField label="Motivo / descrição" value={disciplineForm.reason} onChange={e=>setDisciplineForm({...disciplineForm,reason:e.target.value})}/><Button variant="contained" onClick={addDiscipline}>Registrar</Button></Box>{discipline.map(d=><Row key={d.id} left={`${d.employeeName} • ${d.type}`} middle={`${d.date} • ${d.reason}`} right={d.status}/>)}</Box>}
    </Paper>
    <Dialog open={openEmployee} onClose={()=>setOpenEmployee(false)} fullWidth maxWidth="md"><DialogTitle>{editingId?"Editar colaborador":"Novo colaborador"}</DialogTitle><DialogContent sx={{display:"grid",gridTemplateColumns:{xs:"1fr",md:"repeat(2,1fr)"},gap:2,pt:"12px!important"}}><TextField required label="Nome" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><TextField select label="Categoria" value={form.category} onChange={e=>setForm({...form,category:e.target.value as EmployeeCategory})}>{categoryOptions.map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField><TextField required label="Cargo" value={form.position} onChange={e=>setForm({...form,position:e.target.value})}/><TextField label="Departamento" value={form.department} onChange={e=>setForm({...form,department:e.target.value})}/><TextField select label="Vínculo" value={form.employmentModel} onChange={e=>setForm({...form,employmentModel:e.target.value as EmploymentModel})}>{employmentOptions.map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField><TextField select label="Situação" value={form.status} onChange={e=>setForm({...form,status:e.target.value as EmployeeStatus})}>{statusOptions.map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField><TextField type="date" label="Admissão" value={form.admissionDate} onChange={e=>setForm({...form,admissionDate:e.target.value})} slotProps={{inputLabel:{shrink:true}}}/><TextField type="date" label="Fim do período de experiência" value={form.experienceEndDate} onChange={e=>setForm({...form,experienceEndDate:e.target.value})} slotProps={{inputLabel:{shrink:true}}}/><TextField label="Salário / base mensal" type="number" value={form.baseSalary} onChange={e=>setForm({...form,baseSalary:e.target.value})}/><TextField label="Carga mensal (h)" type="number" value={form.monthlyWorkload} onChange={e=>setForm({...form,monthlyWorkload:e.target.value})}/><TextField label="Supervisor" value={form.supervisor} onChange={e=>setForm({...form,supervisor:e.target.value})}/><TextField label="CPF" value={form.cpf} onChange={e=>setForm({...form,cpf:e.target.value})}/><TextField label="Telefone" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><TextField label="E-mail" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><TextField label="Chave PIX" value={form.pixKey} onChange={e=>setForm({...form,pixKey:e.target.value})}/><TextField label="Observações" multiline minRows={2} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></DialogContent><DialogActions><Button onClick={()=>setOpenEmployee(false)}>Cancelar</Button><Button variant="contained" onClick={saveEmployee}>Salvar colaborador</Button></DialogActions></Dialog>
  </Box>
}
function EmployeeSelect({value,onChange,employees}:{value:string;onChange:(v:string)=>void;employees:Employee[]}){return <TextField select label="Colaborador" value={value} onChange={e=>onChange(e.target.value)}>{employees.filter(e=>e.status!=="Desligado").map(e=><MenuItem key={e.id} value={String(e.id)}>{e.name}</MenuItem>)}</TextField>}
function SectionTitle({title}:{title:string}){return <Typography variant="h6" sx={{fontWeight:800,mb:2}}>{title}</Typography>}
function Row({left,middle,right}:{left:string;middle:string;right:string}){return <Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",md:"2fr 3fr 1.5fr"},gap:2,py:1.4,borderBottom:"1px solid",borderColor:"divider",alignItems:"center"}}><Typography sx={{fontWeight:700}}>{left}</Typography><Typography variant="body2" color="text.secondary">{middle}</Typography><Typography>{right}</Typography></Box>}
