import { useMemo, useState } from "react";
import { Alert, Box, Button, Chip, Divider, MenuItem, Paper, Switch, TextField, Typography } from "@mui/material";
import CreditCardIcon from "@mui/icons-material/CreditCard";
import PixIcon from "@mui/icons-material/Pix";
import SyncIcon from "@mui/icons-material/Sync";
import PageHeader from "../components/PageHeader";
import { listFinanceEntries, listProviderConfigs, saveProviderConfigs, type PaymentMethod, type PaymentProviderConfig } from "../services/FinanceHubService";

const money=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v||0);
export default function PaymentCenter(){
 const [providers,setProviders]=useState<PaymentProviderConfig[]>(()=>listProviderConfigs());
 const [amount,setAmount]=useState("350"); const [method,setMethod]=useState<PaymentMethod>("PIX"); const [provider,setProvider]=useState("asaas"); const [last,setLast]=useState("");
 const entries=listFinanceEntries();
 const totals=useMemo(()=>({open:entries.filter(x=>x.type==="Receita"&&x.status!=="Pago"&&x.status!=="Cancelado").reduce((a,x)=>a+x.value,0),paid:entries.filter(x=>x.type==="Receita"&&x.status==="Pago").reduce((a,x)=>a+x.value,0)}),[entries]);
 const persist=(next:PaymentProviderConfig[])=>{setProviders(next);saveProviderConfigs(next)};
 const simulate=()=>{const selected=providers.find(p=>p.id===provider);setLast(`Cobrança de teste preparada: ${money(Number(amount||0))} via ${method} • ${selected?.name||provider}. Nenhum valor real foi movimentado.`)};
 return <Box><PageHeader title="Pagamentos e Recebimentos" description="Camada única para PIX, cartão, boleto, Asaas, Stripe e bancos/Open Finance."/><Alert severity="warning" sx={{mb:3}}>Credenciais ficam somente no backend. Nesta Alpha, ativação e cobrança são simuladas; produção exige chaves, webhooks e homologação de cada provedor.</Alert>
 <Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",md:"1fr 1fr"},gap:2,mb:3}}><Paper sx={{p:2.5,borderRadius:3}}><Typography color="text.secondary">Recebimentos em aberto</Typography><Typography variant="h5" sx={{fontWeight:900}}>{money(totals.open)}</Typography></Paper><Paper sx={{p:2.5,borderRadius:3}}><Typography color="text.secondary">Recebido / baixado</Typography><Typography variant="h5" sx={{fontWeight:900}}>{money(totals.paid)}</Typography></Paper></Box>
 <Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",lg:"repeat(3,1fr)"},gap:2}}>{providers.map(p=><Paper key={p.id} variant="outlined" sx={{p:3,borderRadius:4}}><Box sx={{display:"flex",justifyContent:"space-between",gap:2}}><Box><Typography variant="h6" sx={{fontWeight:900}}>{p.name}</Typography><Typography variant="body2" color="text.secondary">{p.id==="asaas"?"PIX, cartão e boleto no Brasil":p.id==="stripe"?"Cartões e pagamentos internacionais":"PIX, transferências e conciliação bancária"}</Typography></Box><Switch checked={p.active} onChange={(_,v)=>persist(providers.map(x=>x.id===p.id?{...x,active:v}:x))}/></Box><Box sx={{display:"flex",gap:1,flexWrap:"wrap",my:2}}>{p.supports.map(x=><Chip size="small" key={x} label={x}/>)}</Box><TextField select fullWidth size="small" label="Ambiente" value={p.environment} onChange={e=>persist(providers.map(x=>x.id===p.id?{...x,environment:e.target.value as PaymentProviderConfig["environment"]}:x))}><MenuItem value="Teste">Teste</MenuItem><MenuItem value="Produção">Produção</MenuItem></TextField><Box sx={{mt:2,display:"grid",gap:.5}}><Typography variant="caption" color={p.credentialsConfigured?"success.main":"text.secondary"}>Credenciais: {p.credentialsConfigured?"configuradas":"pendentes"}</Typography><Typography variant="caption" color={p.webhookConfigured?"success.main":"text.secondary"}>Webhook: {p.webhookConfigured?"configurado":"pendente"}</Typography></Box></Paper>)}</Box>
 <Paper variant="outlined" sx={{mt:3,p:3,borderRadius:4}}><Typography variant="h6" sx={{fontWeight:900}}>Simulador de cobrança</Typography><Typography variant="body2" color="text.secondary" sx={{mb:2}}>Valida o fluxo de seleção antes de conectarmos as APIs reais.</Typography><Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",md:"1fr 1fr 1fr auto"},gap:2,alignItems:"center"}}><TextField label="Valor" type="number" value={amount} onChange={e=>setAmount(e.target.value)}/><TextField select label="Forma" value={method} onChange={e=>setMethod(e.target.value as PaymentMethod)}>{["PIX","Cartão","Boleto","Transferência"].map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField><TextField select label="Provedor" value={provider} onChange={e=>setProvider(e.target.value)}>{providers.map(p=><MenuItem key={p.id} value={p.id}>{p.name}</MenuItem>)}</TextField><Button variant="contained" startIcon={method==="PIX"?<PixIcon/>:<CreditCardIcon/>} onClick={simulate}>Simular</Button></Box>{last&&<><Divider sx={{my:2}}/><Alert icon={<SyncIcon/>} severity="success">{last}</Alert></>}</Paper>
 </Box>
}
