import { useMemo, useState } from "react";
import { Alert, Box, Button, MenuItem, Paper, TextField, Typography } from "@mui/material";
import EventAvailableIcon from "@mui/icons-material/EventAvailable";
import ProcedurePicker from "../components/ProcedurePicker";
import { createAppointment, getAppointments } from "../services/OperationsHubService";
const today=()=>new Date().toISOString().slice(0,10);
export default function PublicBooking(){
 const [sent,setSent]=useState(false); const [form,setForm]=useState({patientName:"",patientPhone:"",professionalName:"Dr. Robson",procedure:"Consulta inicial / avaliação",dateISO:today(),time:"09:00",room:"Consultório 1"});
 const occupied=useMemo(()=>new Set(getAppointments().filter(a=>a.dateISO===form.dateISO&&a.professionalName===form.professionalName&&!['Cancelado','Faltou'].includes(a.status)).map(a=>a.time)),[form.dateISO,form.professionalName]); const slots=["08:00","08:30","09:00","09:30","10:00","10:30","11:00","11:30","13:00","13:30","14:00","14:30","15:00","15:30","16:00","16:30","17:00"];
 const save=()=>{if(!form.patientName.trim()||!form.patientPhone.trim()||occupied.has(form.time))return;createAppointment({...form,nextProcedure:"Definir após atendimento",status:"Agendado",source:"Paciente",reminders:{onBooking:true,oneDayBefore:true,onDay:true}});setSent(true)};
 return <Box sx={{minHeight:"100vh",bgcolor:"#f6f8fb",display:"grid",placeItems:"center",p:2}}><Paper sx={{maxWidth:720,width:"100%",p:{xs:3,md:5},borderRadius:4}}><Typography variant="h4" sx={{fontWeight:900}}>DentalPos • Agendamento online</Typography><Typography color="text.secondary" sx={{mb:3}}>Escolha um horário disponível. A clínica poderá confirmar e enviar lembretes automaticamente.</Typography>{sent?<Alert severity="success" action={<Button onClick={()=>setSent(false)}>Novo agendamento</Button>}>Solicitação registrada. Você receberá a confirmação pelos canais configurados pela clínica.</Alert>:<Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",md:"1fr 1fr"},gap:2}}><TextField required label="Nome" value={form.patientName} onChange={e=>setForm({...form,patientName:e.target.value})}/><TextField required label="Celular / WhatsApp" value={form.patientPhone} onChange={e=>setForm({...form,patientPhone:e.target.value})}/><TextField select label="Profissional" value={form.professionalName} onChange={e=>setForm({...form,professionalName:e.target.value})}><MenuItem value="Dr. Robson">Dr. Robson</MenuItem><MenuItem value="Dra. Cássia">Dra. Cássia</MenuItem></TextField><TextField type="date" label="Data" slotProps={{inputLabel:{shrink:true}}} value={form.dateISO} onChange={e=>setForm({...form,dateISO:e.target.value})}/><Box sx={{gridColumn:{md:"1/-1"}}}><ProcedurePicker value={form.procedure} onChange={(name)=>setForm({...form,procedure:name})}/></Box><TextField select label="Horário" value={form.time} onChange={e=>setForm({...form,time:e.target.value})}>{slots.map(s=><MenuItem key={s} disabled={occupied.has(s)} value={s}>{s}{occupied.has(s)?" • indisponível":""}</MenuItem>)}</TextField><Box sx={{display:"flex",alignItems:"center"}}><Button fullWidth size="large" variant="contained" startIcon={<EventAvailableIcon/>} onClick={save}>Solicitar agendamento</Button></Box></Box>}</Paper></Box>;
}
