import { useEffect, useMemo, useState } from 'react';
import { Alert, Box, Button, Dialog, DialogActions, DialogContent, DialogTitle, LinearProgress, MenuItem, Paper, TextField, Typography } from '@mui/material';
import AddIcon from '@mui/icons-material/Add';
import PageHeader from '../components/PageHeader';
import { loadBackendPatients, type BackendPatient } from '../services/PatientApi';
import { createTreatmentItem, getTreatmentPlan, importOdontogram, updateTreatmentItem, type TreatmentPlanItem } from '../services/TreatmentPlanApi';
import { approveBudget, cancelBudget, createBudget, listBudgets, type BudgetRow } from '../services/BudgetApi';

const money=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v||0);
export default function TreatmentPlanning(){
 const [patients,setPatients]=useState<BackendPatient[]>([]),[patientId,setPatientId]=useState(''),[items,setItems]=useState<TreatmentPlanItem[]>([]),[progress,setProgress]=useState(0),[budgets,setBudgets]=useState<BudgetRow[]>([]),[error,setError]=useState(''),[open,setOpen]=useState(false);
 const [form,setForm]=useState<any>({procedure:'',tooth:'',region:'',phase:'1',priority:'NORMAL',specialty:'',professionalName:'',estimatedMinutes:60,unitValue:0,laboratoryRequired:false,status:'PLANNED'});
 const patient=patients.find(p=>p.id===patientId); const total=useMemo(()=>items.reduce((s,i)=>s+Number(i.planningData?.unitValue||0),0),[items]);
 async function refresh(id=patientId){if(!id){setItems([]);setProgress(0);return}try{const r=await getTreatmentPlan(id);setItems(r.items);setProgress(r.progressPercent);setBudgets((await listBudgets()).filter(b=>b.patientId===id));setError('')}catch(e:any){setError(e.message)}}
 useEffect(()=>{loadBackendPatients().then(setPatients).catch(e=>setError(e.message));listBudgets().then(setBudgets).catch(()=>{})},[]); useEffect(()=>{refresh(patientId)},[patientId]);
 async function save(){try{await createTreatmentItem(patientId,form);setOpen(false);setForm({...form,procedure:'',tooth:'',region:'',unitValue:0});await refresh()}catch(e:any){setError(e.message)}}
 async function createProposal(){if(!patientId||!items.length)return;const valid=new Date();valid.setDate(valid.getDate()+30);try{await createBudget({patientId,description:`Plano de tratamento • ${patient?.fullName||'Paciente'}`,totalAmount:total,installments:1,installmentValue:total,discountPercent:0,entryAmount:0,monthlyRatePercent:0,paymentMethod:'PIX',paymentProvider:'MANUAL',validUntil:valid.toISOString(),optionsJson:{treatmentItemIds:items.map(i=>i.id),versioned:true}});await refresh()}catch(e:any){setError(e.message)}}
 return <Box><PageHeader title="Plano de Tratamento e Orçamento Clínico" description="Plano por dente/região, fases, prioridades e orçamento persistidos no backend." actionLabel="Novo procedimento" actionIcon={<AddIcon/>} onAction={()=>setOpen(true)}/>
 {error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}
 <Paper variant="outlined" sx={{p:2,mb:2}}><TextField select fullWidth label="Paciente" value={patientId} onChange={e=>setPatientId(e.target.value)}>{patients.map(p=><MenuItem key={p.id} value={p.id}>{p.fullName}</MenuItem>)}</TextField></Paper>
 {patientId&&<><Paper variant="outlined" sx={{p:2,mb:2}}><Box sx={{display:'flex',justifyContent:'space-between',gap:2,flexWrap:'wrap'}}><Typography sx={{fontWeight:800}}>Execução do tratamento: {progress}%</Typography><Box><Button onClick={async()=>{await importOdontogram(patientId);await refresh()}}>Importar odontograma</Button><Button variant="contained" onClick={createProposal} disabled={!items.length}>Gerar orçamento</Button></Box></Box><LinearProgress variant="determinate" value={progress} sx={{mt:1}}/></Paper>
 {items.map(i=><Paper key={i.id} variant="outlined" sx={{p:2,mb:1}}><Box sx={{display:'flex',justifyContent:'space-between',gap:2,flexWrap:'wrap'}}><Box><Typography sx={{fontWeight:800}}>{i.procedure}</Typography><Typography variant="body2" color="text.secondary">{i.tooth?`Dente ${i.tooth} • `:''}{i.planningData?.region||'Geral'} • Fase {i.planningData?.phase||'1'} • {i.planningData?.priority||'NORMAL'} • {money(Number(i.planningData?.unitValue||0))}</Typography></Box><TextField select size="small" label="Status" value={i.status} onChange={async e=>{await updateTreatmentItem(i.id,{status:e.target.value,planningData:i.planningData});await refresh()}} sx={{minWidth:160}}>{['PLANNED','APPROVED','IN_PROGRESS','COMPLETED','CANCELLED'].map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField></Box></Paper>)}
 <Typography variant="h6" sx={{mt:3,mb:1}}>Orçamentos deste paciente</Typography>{budgets.filter(b=>b.patientId===patientId).map(b=><Paper key={b.id} variant="outlined" sx={{p:2,mb:1}}><Box sx={{display:'flex',justifyContent:'space-between',gap:2,flexWrap:'wrap'}}><Box><Typography sx={{fontWeight:800}}>{b.description}</Typography><Typography>{money(b.totalAmount)} • {b.status}</Typography></Box><Box><Button disabled={b.status==='APPROVED'} onClick={async()=>{await approveBudget(b.id);await refresh()}}>Aprovar</Button><Button color="error" disabled={b.status==='CANCELLED'} onClick={async()=>{await cancelBudget(b.id);await refresh()}}>Cancelar</Button></Box></Box></Paper>)}</>}
 <Dialog open={open} onClose={()=>setOpen(false)} maxWidth="md" fullWidth><DialogTitle>Novo procedimento</DialogTitle><DialogContent dividers><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'2fr 1fr 1fr'},gap:2}}><TextField label="Procedimento" value={form.procedure} onChange={e=>setForm({...form,procedure:e.target.value})}/><TextField label="Dente" value={form.tooth} onChange={e=>setForm({...form,tooth:e.target.value})}/><TextField label="Região" value={form.region} onChange={e=>setForm({...form,region:e.target.value})}/><TextField label="Fase" value={form.phase} onChange={e=>setForm({...form,phase:e.target.value})}/><TextField select label="Prioridade" value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}>{['URGENT','HIGH','NORMAL','LOW'].map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField><TextField label="Especialidade" value={form.specialty} onChange={e=>setForm({...form,specialty:e.target.value})}/><TextField label="Profissional" value={form.professionalName} onChange={e=>setForm({...form,professionalName:e.target.value})}/><TextField type="number" label="Duração (min)" value={form.estimatedMinutes} onChange={e=>setForm({...form,estimatedMinutes:Number(e.target.value)})}/><TextField type="number" label="Valor" value={form.unitValue} onChange={e=>setForm({...form,unitValue:Number(e.target.value)})}/></Box></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancelar</Button><Button variant="contained" disabled={!patientId||!form.procedure.trim()} onClick={save}>Salvar</Button></DialogActions></Dialog>
 </Box>}
