import { useState } from "react";
import { Box, Button, Divider, Paper, TextField, Typography } from "@mui/material";
import DarkModeIcon from "@mui/icons-material/DarkMode";
import LightModeIcon from "@mui/icons-material/LightMode";
import PaletteIcon from "@mui/icons-material/Palette";
import BusinessIcon from "@mui/icons-material/Business";
import PageHeader from "../components/PageHeader";
import { useAppTheme } from "../contexts/AppThemeContext";
const colors=[["Azul DentalPos","#1565C0"],["Azul Safira","#0B5FFF"],["Ciano Digital","#0891B2"],["Turquesa","#0F766E"],["Verde Clínica","#2E7D32"],["Esmeralda","#059669"],["Roxo Premium","#7B1FA2"],["Violeta","#6D28D9"],["Índigo","#4338CA"],["Magenta","#C026D3"],["Rosa","#DB2777"],["Vermelho","#C62828"],["Coral","#EA580C"],["Laranja Comercial","#EF6C00"],["Âmbar","#D97706"],["Dourado","#9A6700"],["Grafite","#334155"],["Preto Premium","#111827"]];
const ID_KEY="dentalpos.clinic.identity.v1";
export default function Settings(){
 const {mode,primaryColor,toggleMode,setPrimaryColor}=useAppTheme();
 const [identity,setIdentity]=useState(()=>{try{return JSON.parse(localStorage.getItem(ID_KEY)||"null")||{name:"Clínica DentalPos",doctor:"Dr. Robson",logo:""}}catch{return{name:"Clínica DentalPos",doctor:"Dr. Robson",logo:""}}});
 return <Box><PageHeader title="Configurações" description="Identidade da clínica, aparência, cores e preferências do sistema."/>
 <Paper elevation={0} sx={{p:3,borderRadius:4,border:"1px solid",borderColor:"divider",mb:3}}><Box sx={{display:"flex",alignItems:"center",gap:2,mb:2}}><BusinessIcon color="primary"/><Box><Typography variant="h6" sx={{fontWeight:800}}>Identidade da clínica</Typography><Typography variant="body2" color="text.secondary">Nome personalizável para login, cabeçalho e documentos.</Typography></Box></Box><Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",md:"1fr 1fr"},gap:2}}><TextField label="Nome da clínica" value={identity.name} onChange={e=>setIdentity({...identity,name:e.target.value})}/><TextField label="Nome do profissional / responsável" value={identity.doctor} onChange={e=>setIdentity({...identity,doctor:e.target.value})}/><TextField label="URL do logotipo (opcional)" value={identity.logo} onChange={e=>setIdentity({...identity,logo:e.target.value})}/><Button variant="contained" onClick={()=>localStorage.setItem(ID_KEY,JSON.stringify(identity))}>Salvar identidade</Button></Box></Paper>
 <Paper elevation={0} sx={{p:3,borderRadius:4,border:"1px solid",borderColor:"divider"}}><Box sx={{display:"flex",alignItems:"center",gap:2,mb:3}}><PaletteIcon color="primary"/><Box><Typography variant="h6" sx={{fontWeight:800}}>Paleta principal</Typography><Typography variant="body2" color="text.secondary">Escolha uma cor pronta ou use qualquer cor personalizada.</Typography></Box></Box><Box sx={{display:"grid",gridTemplateColumns:{xs:"repeat(2,1fr)",md:"repeat(6,1fr)"},gap:1.2}}>{colors.map(([name,value])=><Button key={value} onClick={()=>setPrimaryColor(value)} variant={primaryColor.toLowerCase()===value.toLowerCase()?"contained":"outlined"} sx={{minHeight:64,justifyContent:"flex-start",gap:1,textTransform:"none"}}><Box sx={{width:24,height:24,borderRadius:"50%",bgcolor:value,border:"2px solid #fff",boxShadow:"0 0 0 1px rgba(0,0,0,.2)"}}/><Typography variant="caption" sx={{fontWeight:700}}>{name}</Typography></Button>)}</Box><Divider sx={{my:3}}/><Box sx={{display:"flex",gap:2,alignItems:"center",flexWrap:"wrap"}}><Typography sx={{fontWeight:800}}>Cor personalizada</Typography><input aria-label="Cor personalizada" type="color" value={primaryColor} onChange={e=>setPrimaryColor(e.target.value)} style={{width:54,height:38,border:0,background:"transparent",cursor:"pointer"}}/><Typography variant="body2" color="text.secondary">{primaryColor}</Typography></Box></Paper>
 <Paper elevation={0} sx={{mt:3,p:3,borderRadius:4,border:"1px solid",borderColor:"divider"}}><Typography variant="h6" sx={{fontWeight:800,mb:1}}>Aparência</Typography><Typography variant="body2" color="text.secondary" sx={{mb:3}}>Alterne entre os modos claro e escuro.</Typography><Button variant="contained" onClick={toggleMode} startIcon={mode==="light"?<DarkModeIcon/>:<LightModeIcon/>}>{mode==="light"?"Ativar modo escuro":"Ativar modo claro"}</Button></Paper></Box>
}
